build.gradle.kts
see: https://github.com/node-gradle/gradle-node-plugin/blob/master/docs/faq.md
=> feat: only perform npm run build when input or output files have changed

.github/workflows/clean-up-cache-on-pr-close.yml
so that the cache can be used more efficiently
=> feat: clean up GitHub cache after a PR has been closed 

.github/CODEOWNERS
for automatic pull request assignment to our team
=> feat: added codeowners file

.github/workflows/build-test-deploy.yml, .github/workflows/codeql-analysis.yml
=> Feature/pz 410 add setup gradle GitHub action

docker-compose.yaml
This will fix all the
`FATAL:  role "root" does not exist`
Errors in console of the database containers
=> fix(docker-compose): fix errors in health checks

build.gradle.kts, src/test/kotlin/net/atos/zac/authentication/UserPrincipalFilterTest.kt, src/test/resources/kotest.properties
Added Kotest Kotlin unit test framework, added the first unit test using Kotest, added Detekt for static Kotlin code analysis.
Solves PZ-384
=> feat: add Kotest unit tests framework and first test

src/main/java/net/atos/zac/authentication/UserPrincipalFilter.java, src/test/kotlin/net/atos/zac/authentication/UserPrincipalFilterTest.kt
Switched to using the behavior (BDD) style for Kotlin Kotest unit tests.
Solves PZ-444
=> chore: use behavior kotest style

.github/workflows/build-test-deploy.yml
This will hopdefully fix the javascript error in the new trigger deploy step
new line
=> fix: fix build trigger

.github/workflows/build-test-deploy.yml
I copied the wrong var
I replaced it by the right one
=> Fix/fix: build trigger and tag

docker-compose.yaml
Removed data volume mapping for OpenLDAP Docker container.
Solves PZ-447
=> fix: fixed intermittent issue with starting openldap docker container in Docker Compose setup

build.gradle.kts, src/main/app/dummy-folder/README.md
Added a dummy output folder to the npmRunTest task.
Solves PZ-490
=> chore: removed dependency between war and npmRunTest Gradle tasks

scripts/docker-compose/imports/openzaak-database/database/1-setup-zaaktype.sql
changed sql script so we have a "melding klein evenement zaaktype" by default when you start the project
Solves PZ-391
=> feat: change sql script for melding klein evenement

.editorconfig
Revert editorconfig changes
Solves PZ-497
=> fix: revert editorconfig

src/main/app/src/app/admin/admin/admin.component.ts, src/main/app/src/assets/i18n/en.json, src/main/app/src/assets/i18n/nl.json
This pr will remove menuitems from the settings screen
Solves: PZ-401
=> chore: remove formulier definities menu item

.github/workflows/build-test-deploy.yml, docker-compose.yaml, start-docker-compose-with-zac.sh, start-docker-compose.sh
Set 'latest' Docker Image tag in GitHub build pipeline when on main branch and use this tag in our Docker Compose file.
Solves PZ-555.
=> feat: use 'latest' tag for ZAC Docker Image

dependabot.yml
This will hopefully add dependabot config for node, gradle and github actions
After merging we need to check the github repo settings
=> feat(dependabot): add file

.github/dependabot.yml
This will add a 0
Because it will not work without a 0
=> fix(dependabot): add 0

docker-compose.yaml, scripts/docker-compose/imports/keycloak/realm.json, stop-docker-compose.sh
Use project name in our Docker Compose stop script and made LDAP_URL configurable in our Docker Compose setup.
Solves PZ-573
=> feat: fix docker compose issues

.github/workflows/run-e2e.yml
this adds the actual code for the gh action
Solves PZ-590
=> feat: pz 590 run e2e action

.github/dependabot.yml
I ignored all the providedCompile packages
Remove when PZ-592 is done
=> Fix/dependabot: ignore package update

.github/workflows/run-e2e.yml
Forgot to deploy when something fails :)
Solves PZ-590
=> feat: always deploy to gh pages

.github/workflows/build-test-deploy.yml, build.gradle.kts, docker-compose.yaml, src/itest/kotlin/io/kotest/provided/ProjectConfig.kt, src/itest/kotlin/nl/info/zac/TestContainersSetup.kt, src/main/java/net/atos/zac/util/SolrDeployer.java
Added running the integration tests to the GitHub build, test and deploy pipeline.
Solves PZ-293.
=> feat: add integration tests to GitHub pipeline

.github/workflows/build-test-deploy.yml
Fixed broken build by reverting accidental removal of dependency in GitHub pipeline.
Solves PZ-619.
=> fix: fixed broken build by reverting removing of dependency in GitHub pipeline

.github/workflows/update-gradle-wrapper.yml
Added a GitHub workflow using the update Gradle GitHub action to automatically update our Gradle wrapper.
Solves PZ-625
=> feat: add GitHub workflow to automatically update our Gradle wrapper

README.md, scripts/wildfly/README.md, start-docker-compose-with-zac.sh, start-docker-compose.sh, startupwithenv.sh, stop-docker-compose.sh
This pr will fix a few urls to the docs
Solves PZ-560
=> fix: fix doc urls

src/main/app/src/app/shared/pipes/datum.pipe.spec.ts
This should fix tests
By removing tests
=> fix(test): fix unit test by not testing for UTC

helm/templates/config.yaml, helm/values.yaml
Added the option to set the optional SD_FIXED_USER_NAME env var to the ZAC Helm chart.
Solves PZ-718
=> feat: add option to set the optional SD_FIXED_USER_NAME env var to the ZAC Helm chart

docs/development/INSTALL.md, docs/development/end-to-end-testing.md
Fixed broken links in docs.
Solves PZ-127
=> chore: fixed broken links in docs

build.gradle.kts
Removed unneeded copy jar Gradle task.
Solves PZ-769
=> chore: remove unneeded copy jar Gradle task

.env.tpl, src/e2e/features/1-authentication.feature, src/e2e/features/2-zaken-toevoegen.feature, src/e2e/step-definitions/zaak.ts, src/e2e/support/worlds/world.ts
This pr will refactor e2e tests to run in dutch
Solves PZ-816
=> fix: e2e locale bug fixes

docs/development/end-to-end-testing.md, scripts/docker-compose/imports/keycloak/realm.json, src/e2e/step-definitions/common.ts, start-e2e-with-local-env.sh
THis pr will increare the timeout a little bit and also add docs for how to run the e2e test locally
Solves PZ-833
=> fix: failing test

build.gradle.kts
Upgraded OpenAPI generator Gradle plugin. Beating Dependabot to it.
Solves PZ-881
=> chore: upgradw OpenAPI generator Gradle plugin

.github/dependabot.yml, build.gradle.kts
Update dependabot.yml to run Dependabot nightly due to the large number of dependencies in our application.
Solves PZ-884
=> chore: update dependabot.yml to run nightly

src/main/java/net/atos/client/brp/BRPClientService.java, src/main/java/net/atos/client/zgw/brc/BRCClientService.java, src/main/java/net/atos/client/zgw/shared/util/ZGWClientHeadersFactory.java, src/main/java/net/atos/client/zgw/zrc/model/Point2D.java, src/main/java/net/atos/client/zgw/zrc/model/Rol.java, src/main/java/net/atos/client/zgw/zrc/model/RolMedewerker.java, src/main/java/net/atos/client/zgw/zrc/model/RolNatuurlijkPersoon.java, src/main/java/net/atos/client/zgw/zrc/model/RolNietNatuurlijkPersoon.java, src/main/java/net/atos/client/zgw/zrc/model/RolOrganisatorischeEenheid.java, src/main/java/net/atos/client/zgw/zrc/model/RolVestiging.java, src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java, src/main/java/net/atos/zac/documentcreatie/converter/DataConverter.java, src/main/java/net/atos/zac/event/AbstractEvent.java, src/main/java/net/atos/zac/signalering/SignaleringenJob.java, src/main/java/net/atos/zac/signalering/event/SignaleringEventObserver.java, src/main/java/net/atos/zac/util/JsonLoggingFilter.java, src/main/java/net/atos/zac/util/PeriodUtil.java, src/main/java/net/atos/zac/util/SolrDeployer.java, src/main/java/net/atos/zac/util/UriUtil.java, src/main/java/net/atos/zac/zoeken/IndexeerService.java
Fix most 'bugs' SonarQube Java code quality issues.
Solves PZ-189
=> fix: fix sonarqube quality issues - bugs

src/main/java/net/atos/zac/util/CMMNDeployer.java
To fix security vulnerability: https://rules.sonarsource.com/java/RSPEC-2755/
Solves PZ-970
=> fix: disable access to external entities in XML parsing

src/main/app/package-lock.json, src/main/app/package.json
This will fix the mistake I made in #282 
Sorry
=> fix(build): fix mistake

build.gradle.kts, pom.xml, scripts/wildfly/install-wildfly.sh, startupwithenv.sh
New WildFly!
Easy fix this time
=> feat(wildfly): upgrade to 30.0.1.Final

src/main/app/src/app/zaken/zaak-view/zaak-view.component.html
=> fix: remove tooltip

src/main/app/src/app/taken/taak-view/taak-view.component.ts
this pr will remove the "document maken" button when a task is in the "afgerond state"
Solves PZ-874
=> feat: remove button

src/main/app/src/app/plan-items/plan-items.service.ts
This will fix taak aanmaken
Sorry for breaking it
=> fix(taak): fix taak aanmaken

build.gradle.kts
Use latest version of webdav-servlet project in nl.lifely namspace.
Solves PZ-1035
=> chore: use latest version of webdav-servlet project

docs/development/testing.md, start-e2e-with-local-env.sh, start-e2e-with-test-env.sh, start-e2e.sh
Updated e2e tests developer docs a little. Also added missing shebang lines for e2e scripts.
Solves PZ-1050
=> chore: updated e2e tests developer documentation

src/main/app/src/app/shared/edit/edit-datum-groep/edit-datum-groep.component.html, src/main/app/src/app/shared/material-form-builder/form-components/autocomplete/autocomplete.component.html, src/main/app/src/app/shared/material-form-builder/form-components/google-maps/google-maps.component.html, src/main/app/src/app/shared/material-form-builder/form-components/html-editor/html-editor.component.html, src/main/app/src/app/shared/material-form-builder/form-components/input/input.component.html, src/main/app/src/app/shared/material-form-builder/form-components/medewerker-groep/medewerker-groep.component.html, src/main/app/src/app/shared/material-form-builder/form-components/medewerker-groep/medewerker-groep.component.less, src/main/app/src/app/shared/material-form-builder/form-components/radio/radio.component.html, src/main/app/src/app/shared/material-form-builder/form-components/select/select.component.html, src/main/app/src/app/shared/material-form-builder/form-components/textarea/textarea.component.html, src/main/app/src/app/shared/material-form-builder/material-form-builder.module.ts, src/main/app/src/app/shared/material/mat-zac-error.ts
add line-clamp to all mat-errors
Solves PZ-993
=> feat: add line-clamp to all mat-errors

docker-compose.yaml, scripts/docker-compose/imports/keycloak/realm.json
Upgraded our local Keycloak and our realm.json used in our Docker Compose local setup to Keycloak 23.0.4.
Solves PZ-1131
=> chore: upgrade keycloak to 23.0.4

docs/solution-architecture/README.md
Also updated architecture documenation index.
Solves PZ-1135
=> chore: added main architecture characteristics

src/e2e/step-definitions/authentication.ts
Fixes the failing tests
Solves PZ-1136
=> fix: e2e test

scripts/docker-compose/imports/openklant-database/database/1-setup-applicatie.sql
Added test data to OpenKlant for BRP Proxy test user with BSN number 999993896.
Solves PZ-1157
=> feat: add test data to OpenKlant for BRP Proxy test user 

scripts/docker-compose/imports/keycloak/realm.json, scripts/docker-compose/imports/openldap/zac-scripts/zac-ldap-setup-template.ldif
=> chore: Chore/change group name

src/itest/kotlin/nl/lifely/zac/itest/IdentityServiceTest.kt
This should fix the build
By fixing the test that fails
=> fix(test): fix id

scripts/docker-compose/imports/openldap/zac-scripts/zac-ldap-setup-template.ldif, src/itest/kotlin/io/kotest/provided/ProjectConfig.kt, src/itest/kotlin/nl/lifely/zac/itest/NotificationsTest.kt
Fix failing integration tests.
Solves PZ-1171
=> fix: fix failing itests due to recent change

.github/workflows/build-test-deploy.yml
Fixed issue with uploading Trivy SARIF security reports.
Solves PZ-1182
=> fix: fixed issue with uploading Trivy SARIF security reports

.github/workflows/build-test-deploy.yml, .github/workflows/trivy-code-scanning.yml
Ignore Trivy MEDIUM level issues; added cron to Trivy repo scanning workflow.
Solves PZ-1185
=> feat: ignore Trivy MEDIUM level issues & added cron to Trivy repo scan

docker-compose.yaml
Updated Solr in Docker Compose to 9.4.1 also to be in line with our test environment.
Solves PZ-1215
=> chore: update Solr in Docker Compose

docker-compose.yaml, src/itest/kotlin/io/kotest/provided/ProjectConfig.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt
Hopefully fixed failing itests on GitHub by adding Keycloak health checks and waiting to start the itests until Keycloak is healthy.
Solves PZ-1292
=> fix: fixed failing itests on GitHub by adding Keycloak health checks

.github/workflows/snyk-code-scanning.yml, .github/workflows/trivy-code-scanning.yml, package-lock.json
Added Snyk Gradle dependency scanner workflow.
Solves PZ-1289
=> feat: add snyk gradle dependencies scanner

src/main/app/src/app/informatie-objecten/informatie-object-add/informatie-object-add.component.ts, src/main/app/src/app/shared/material-form-builder/form-components/select/select.component.html, src/main/app/src/app/shared/material-form-builder/form-components/select/select.component.ts, src/main/app/src/app/shared/material-form-builder/model/abstract-choices-form-field-builder.ts, src/main/app/src/app/shared/material-form-builder/model/abstract-choices-form-field.ts
This pr will add a option to Select field to disable translated fields
Solves PZ-1263
=> feat: remove translation from select field

src/main/app/src/app/informatie-objecten/informatie-object-add/informatie-object-add.component.ts, src/main/app/src/app/shared/material-form-builder/form-components/select/select.component.html, src/main/app/src/app/shared/material-form-builder/material-form-builder.module.ts, src/main/app/src/app/shared/material-form-builder/model/abstract-choices-form-field-builder.ts, src/main/app/src/app/shared/material-form-builder/model/abstract-choices-form-field.ts, src/main/app/src/app/shared/pipes/capitalizeFirstLetter.pipe.ts
add capitalized first letter setting
Solves PZ-1326
=> feat: add capitalized first letter

docs/development/testing.md
add docs for test codegen
Solves PZ-1324
=> feat: add docs for test codegen

.github/workflows/run-e2e.yml, src/e2e/features/3-open-formulieren.feature, src/e2e/step-definitions/zaak.ts
Fixes gh action
Solves PZ-1331
=> feat: pz 1331 fix e2e gh action

src/main/java/net/atos/zac/app/taken/TakenRESTService.java, src/test/kotlin/net/atos/client/zgw/drc/model/DrcFixtures.kt, src/test/kotlin/net/atos/client/zgw/zrc/model/ZrcFixtures.kt, src/test/kotlin/net/atos/zac/app/identity/model/IdentityFixtures.kt, src/test/kotlin/net/atos/zac/app/taken/TakenRESTServiceTest.kt, src/test/kotlin/net/atos/zac/app/taken/model/TakenRESTFixtures.kt, src/test/kotlin/net/atos/zac/policy/output/PolicyOutputFixtures.kt
Fixed issue where taak could not be closed when document was signed due to enum having empty value (instead of null).
Solves PZ-1358
=> fix: fix issue where taak could not be closed when document was signed

docs/solution-architecture/iamArchitecture.md, docs/solution-architecture/systemContext.md
Extended ZAC system context diagram a bit.
Solves PZ-1415
=> chore: extend system context docs

build.gradle.kts, docs/development/updatingDependencies.md, pom.xml, scripts/wildfly/install-wildfly.sh, startupwithenv.sh
Upgraded to WildFly 31.0.0. Also added WildFly upgrade docs.
Solves PZ-1450
=> chore: upgraded WildFly to 31.0.0.Final. 

.mvn/wrapper/maven-wrapper.properties
Upgraded Maven wrapper to 3.9.6
Solves PZ-1486
=> chore: upgrade maven wrapper to 3.9.6

.github/workflows/build-test-deploy.yml, .github/workflows/codeql.yml, Dockerfile, build.gradle.kts, docs/development/INSTALL.md, src/main/java/net/atos/zac/app/klanten/converter/RESTPersoonConverter.java, src/main/java/net/atos/zac/mailtemplates/MailTemplateHelper.java
Upgraded the ZAC Java JDK to 21. Also set source and target compatibility to JDK 21. #minor
Solves PZ-1492
=> chore: upgraded to JDK 21

src/main/app/src/app/klanten/bedrijfsgegevens/bedrijfsgegevens.component.html, src/main/app/src/app/klanten/persoonsgegevens/persoonsgegevens.component.html, src/main/app/src/app/zaken/zaak-view/zaak-view.component.html, src/main/app/src/assets/i18n/en.json, src/main/app/src/assets/i18n/nl.json
this pr will add unlink icons to bagobjecten list and initiator bedrijf and person on a zaak
Solves PZ-1337
=> feat: add unlink icons

docs/development/testing.md
Fixes docker-compose.yml changes needed for local e2e test
Solves: PZ-1558
=> fix: e2e tests documentation

.github/workflows/build-test-deploy.yml
To improve build time.
Solves PZ-1587
=> chore: do not remove large-packages in free-disk-space GitHub action

.github/workflows/run-e2e.yml
=> feat: use node 20 for playwright

src/e2e/features/5-external-systems.feature, src/e2e/step-definitions/zaak.ts
Bob logged out in scenario 4 we cannot use it
Use Oscar instead
=> fix: use Oscar as Bob logged out in 4th scenario

.github/workflows/build-test-deploy.yml, build.gradle.kts, docker-compose.yaml, src/itest/kotlin/io/kotest/provided/ProjectConfig.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt
Added JaCoCo test coverage and Codecov upload for our integration tests.
Solves PZ-1623
=> chore: add JaCoCo test coverage for our integration tests

build.gradle.kts, src/e2e/features/1-authentication.feature, src/e2e/features/5-external-systems.feature, src/e2e/step-definitions/authentication.ts, src/e2e/step-definitions/common.ts, src/e2e/step-definitions/hooks.ts, src/e2e/step-definitions/zaak.ts, src/e2e/support/worlds/world.ts, start-e2e.sh
Add video generation to e2e tests
Enable headless mode for local run
Cleanup screenshots & videos before local execution
Increase timeouts for login and text check
=> feat: add videos to e2e tests

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.html, src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.ts, src/main/app/src/app/informatie-objecten/informatie-objecten.module.ts, src/main/app/src/app/informatie-objecten/model/file-format.ts, src/main/app/src/app/shared/pipes/mimetypeToExtension.pipe.spec.ts, src/main/app/src/app/shared/pipes/mimetypeToExtension.pipe.ts, src/main/app/src/app/taken/taak-view/taak-view.component.html, src/main/app/src/app/taken/taken.module.ts, src/main/app/src/app/zaken/besluit-view/besluit-view.component.html, src/main/app/src/app/zaken/zaak-view/zaak-view.component.html, src/main/app/src/app/zaken/zaken.module.ts
This pr will add a angula rpipe that converts mimetypes to extensions according to this mapping https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
Solves PZ-1368
=> feat: add mimetype conversion

build.gradle.kts, src/e2e/cucumber.js, src/e2e/generate-report.js, src/e2e/step-definitions/authentication.ts, src/e2e/step-definitions/common.ts, src/e2e/step-definitions/hooks.ts, src/e2e/step-definitions/open-forms.ts, src/e2e/step-definitions/zaak.ts, src/e2e/support/indienen-aansprakelijkstelling-door-derden/profiles/alice.ts, src/e2e/support/indienen-aansprakelijkstelling-door-derden/profiles/index.ts, src/e2e/support/indienen-aansprakelijkstelling-door-derden/profiles/robert.ts, src/e2e/support/indienen-aansprakelijkstelling-door-derden/profiles/types.ts, src/e2e/support/worlds/userProfiles.ts, src/e2e/support/worlds/world.ts, src/e2e/utils/TestStorage.service.ts, src/e2e/utils/schemes.ts
Add spotless formatting for e2e tests
=> feat: add spotless for e2e tests

src/itest/kotlin/io/kotest/provided/ProjectConfig.kt, src/itest/kotlin/nl/lifely/zac/itest/AppContainerTest.kt, src/itest/kotlin/nl/lifely/zac/itest/IdentityServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/InformatieObjectenTest.kt, src/itest/kotlin/nl/lifely/zac/itest/NotificationsTest.kt, src/itest/kotlin/nl/lifely/zac/itest/PlanItemsRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/TakenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZaakafhandelParametersTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZakenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/client/ItestHttpClient.kt, src/itest/kotlin/nl/lifely/zac/itest/client/KeycloakClient.kt, src/itest/kotlin/nl/lifely/zac/itest/client/ZacClient.kt
Refactored set up of integration test helper classes a bit.
Solve PZ-1668
=> chore: refactor integration test helper classes

docker-compose.yaml
Allows local development with Wildfly on Linux
Solves PZ-1726
=> feat: enable host.docker.internal for Linux

docs/development/README.md, src/main/java/net/atos/zac/flowable/TakenService.java, src/test/kotlin/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverterTest.kt, src/test/kotlin/net/atos/zac/app/informatieobjecten/model/InformatieObjectenRESTFixtures.kt
Added extra unit test for rest informatie object converter for converting to a zaak. Added IDE Config doc link to developer/readme.
Solves PZ-1767
=> chore: add extra unit test for rest informatie object converter

docs/development/ideConfig.md
Add debug configuration hint in the IDE doc
Solves PZ-1785
=> feat: add wildfly debug config hint

scripts/docker-compose/imports/zgw-referentielijsten/init-zgw-referentielijsten-database.sql
feat: add channels to zgw-referentielijsten database
Solves PZ-1716
=> feat: add channels to zgw-referentielijsten database

src/main/app/src/app/klanten/persoonsgegevens/persoonsgegevens.component.html, src/main/app/src/app/klanten/persoonsgegevens/persoonsgegevens.component.ts
remove betrokkene field opening automatically and refactor angular code a bit more
Solves: PZ-1738
=> fix: remove betrokkene field opening automatically

build.gradle.kts, src/main/app/jest.config.ts
Added Jest reports again.
Solves PZ-1830
=> chore: (re)added Jest reports

src/main/java/net/atos/zac/app/taken/converter/RESTTaakHistorieConverter.java, src/test/kotlin/net/atos/zac/app/taken/converter/RESTTaakHistorieConverterTest.kt
Use i18n translation label
Solves: PZ-1842
=> fix: PZ-1842 - use Status instead of open/closed in Wijziging column

docker-compose.yaml
localhost does not seem to work on Linux
Solves PZ-1858
=> fix: use 0.0.0.0 instead of localhost for healthcheck

src/itest/kotlin/nl/lifely/zac/itest/IdentityServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/NotificationsTest.kt, src/itest/kotlin/nl/lifely/zac/itest/PlanItemsRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/TakenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZakenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/client/ZacClient.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt, src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java
Added integration tests to assign and unassign zaken from a list. Also added test to retrieve a zaak.
Solves PZ-1863
=> chore: added integration tests to assign and unassign zaken from a list

src/itest/kotlin/nl/lifely/zac/itest/AppContainerTest.kt, src/itest/kotlin/nl/lifely/zac/itest/IdentityServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/InformatieObjectenTest.kt, src/itest/kotlin/nl/lifely/zac/itest/NotificationsTest.kt, src/itest/kotlin/nl/lifely/zac/itest/PlanItemsRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/TakenRESTServiceCompleteTest.kt, src/itest/kotlin/nl/lifely/zac/itest/TakenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZaakafhandelParametersTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZakenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt
Added integration tests to add a betrokkene to a zaak.
Solves PZ-1878
=> chore: add integration tests to add a betrokkene to a zaak

.github/CODEOWNERS
Thanks for the work guys!
Solves PZ-1883
=> chore: removed Rick & Jorann from our codeowners file and added Hristo & Felix 

src/main/kotlin/net/atos/zac/app/zaken/model/RESTZakenVerdeelGegevens.kt, src/main/kotlin/net/atos/zac/zaken/ZakenService.kt
Reason should be optional, as it is elsewhere.
Solves PZ-1898
=> fix: make reason optional when assigning tasks from a list

src/e2e/step-definitions/zaak.ts
And not a 'fake' domain like @test.nl because that will cause bounces and maybe worse.
Solves PZ-1934
=> chore: use @team-dimpact.info.nl email domain in our e2e tests

src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java, src/main/java/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverter.java, src/main/java/net/atos/zac/app/informatieobjecten/model/RESTEnkelvoudigInformatieFileUpload.java, src/main/java/net/atos/zac/app/informatieobjecten/model/RESTEnkelvoudigInformatieObjectVersieGegevens.java, src/main/java/net/atos/zac/app/informatieobjecten/model/RESTEnkelvoudigInformatieobject.java, src/main/java/net/atos/zac/app/informatieobjecten/model/validation/ValidRestEnkelvoudigInformatieFileUploadForm.java, src/main/java/net/atos/zac/app/informatieobjecten/model/validation/ValidRestEnkelvoudigInformatieFileUploadFormValidator.java, src/main/java/net/atos/zac/app/util/LocalDateReader.java, src/test/kotlin/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTServiceTest.kt, src/test/kotlin/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverterTest.kt, src/test/kotlin/net/atos/zac/app/informatieobjecten/model/InformatieObjectenRESTFixtures.kt, src/test/kotlin/net/atos/zac/app/informatieobjecten/model/validation/ValidRestEnkelvoudigInformatieobjectFileUploadFormValidatorTest.kt, src/test/kotlin/net/atos/zac/app/policy/model/AppPolicyFixtures.kt.kt, src/test/kotlin/net/atos/zac/app/util/LocalDateReaderTest.kt
Return 400 Bad Request on empty file upload
Solves PZ-1652
=> feat: disable empty file upload

build.gradle.kts, src/main/java/net/atos/zac/app/contactmomenten/ContactmomentenRESTService.java, src/main/java/net/atos/zac/policy/input/UserData.java, src/main/java/net/atos/zac/signalering/event/SignaleringEvent.java, src/main/kotlin/net/atos/client/zgw/ztc/ZTCClientService.kt, src/main/kotlin/net/atos/zac/app/zaken/ZakenRESTService.kt, src/main/kotlin/net/atos/zac/app/zaken/converter/RESTBesluitConverter.kt
Fixed a few minor code quality issues reported by Qodana (in Intellij).
Solves PZ-1948
=> chore: fixed a few code quality issues reported by Qodana (in Intellij)

src/test/kotlin/net/atos/zac/zaken/ZakenServiceTest.kt
Without changing the exception handing behaviour in the backend (for now).
Solves PZ-1956
=> chore: added a unit test just to test the current behavior of exception handling in the zakenservice - assign zaken method

src/main/app/src/app/shared/material-form-builder/form-components/file-input/file-input.component.ts, src/main/app/src/app/shared/material-form-builder/form-components/file/file.component.ts, src/main/app/src/app/shared/material-form-builder/form-components/taak-document-upload/taak-document-upload.component.ts
Adds a client side error message when the user tries to upload an empty file
Solves PZ-1654
=> feat: add client side error message for empty files

.github/workflows/run-e2e.yml
Do not overwrite github pages results
Solves PZ-1970
=> fix: notify on failed e2e tests

.github/workflows/run-e2e.yml
Notify on failure and PR results
Solves PZ-1970
=> fix: notify on all results from e2e tests

.github/workflows/run-e2e.yml
Publish e2e results to github pages after failure
Solves PZ-1970
=> fix: publish e2e results on failure

build.gradle.kts
=> fix: do not check e2e tests report JSON

src/itest/kotlin/nl/lifely/zac/itest/ZakenRESTServiceTest.kt
Grouped some integration tests together in a big when clause.
Solves PZ-2003
=> chore: refactor integration tests a bit

src/main/app/src/app/zaken/zaak-view/zaak-view.component.html, src/main/app/src/assets/i18n/en.json, src/main/app/src/assets/i18n/nl.json
Betrokkene verwijderen wordt Betrokkene ontkoppelen, in lijn met voorgaande wijzigingen.
Solves PZ-1945
=> fix: ontkoppel icon for Betrokkene

src/itest/kotlin/nl/lifely/zac/itest/ZakenRESTServiceTest.kt
Integration tests are failing
Solves PZ-2050
=> fix: integration tests are failing

src/main/java/net/atos/client/zgw/shared/cache/Caching.java, src/main/java/net/atos/zac/app/util/UtilRESTService.java, src/main/kotlin/net/atos/client/zgw/ztc/ZTCClientService.kt, src/test/kotlin/net/atos/client/zgw/ztc/ZTCClientServiceTest.kt
Expose cache stats for ZTC client
Solves PZ-2049
=> feat: add cache stats for util endpoint

.gitignore, src/itest/kotlin/nl/lifely/zac/itest/ZakenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt, src/main/java/net/atos/zac/websocket/event/ScreenEventType.java, src/main/kotlin/net/atos/zac/app/zaken/ZakenRESTService.kt, src/main/kotlin/net/atos/zac/app/zaken/model/RESTZakenVrijgevenGegevens.kt, src/main/kotlin/net/atos/zac/zaken/ZakenService.kt, src/test/kotlin/net/atos/zac/app/zaken/ZakenRESTServiceTest.kt, src/test/kotlin/net/atos/zac/zaken/ZakenServiceTest.kt
Made release zaken from list an async process using websockets to send back a screen event when it is done. No error handling for now. #minor
Solves PZ-1980
=> feat: make release zaken from list async

src/main/java/net/atos/zac/zoeken/IndexeerService.java
Removed unneeded Solr commit calls. Unneeded because we have auto-commit configured on our Solr on our test environment and it is also a default setting in our local Docker Compose Solr. Unit test will follow.
Solves PZ-2077
=> chore: remove Solr commit calls

src/main/java/net/atos/zac/app/util/UtilRESTService.java, src/main/java/net/atos/zac/zaaksturing/ZaakafhandelParameterBeheerService.java, src/main/java/net/atos/zac/zaaksturing/ZaakafhandelParameterService.java
Enable caching for ZaakafhandelParameterService
Solves PZ-2073
=> feat: enable caching for ZaakafhandelParameterService

CONTRIBUTING.md, src/itest/kotlin/nl/lifely/zac/itest/AppContainerTest.kt, src/itest/kotlin/nl/lifely/zac/itest/IdentityServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/InformatieObjectenTest.kt, src/itest/kotlin/nl/lifely/zac/itest/KlantenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/NotificationsTest.kt, src/itest/kotlin/nl/lifely/zac/itest/PlanItemsRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/SignaleringenRestServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/TakenRESTServiceCompleteTest.kt, src/itest/kotlin/nl/lifely/zac/itest/TakenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZaakafhandelParametersTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZakenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/client/ItestHttpClient.kt, src/itest/kotlin/nl/lifely/zac/itest/client/KeycloakClient.kt, src/itest/kotlin/nl/lifely/zac/itest/client/OpenZaakClient.kt, src/itest/kotlin/nl/lifely/zac/itest/client/ZacClient.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt, src/itest/kotlin/nl/lifely/zac/itest/util/WebSocketTestListener.kt, src/main/kotlin/net/atos/zac/app/util/InputValidationFailedException.kt, src/main/kotlin/net/atos/zac/app/zaken/ZakenRESTService.kt, src/main/kotlin/net/atos/zac/signalering/SignaleringenJob.kt, src/main/kotlin/net/atos/zac/zaken/ZakenService.kt
Also fixed some SPDX issues.
Solves PZ-2108
=> chore: updated the year in our SPDX copyright documentation

src/itest/kotlin/nl/lifely/zac/itest/IndexerenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/NotificationsTest.kt, src/itest/kotlin/nl/lifely/zac/itest/client/ItestHttpClient.kt, src/main/java/net/atos/zac/notificaties/NotificatieReceiver.java, src/main/java/net/atos/zac/util/IndexerenRESTService.java
Added integration tests for REST indexing service. 
Solves PZ-2093
=> chore: add integration tests for indexing rest service

src/main/java/net/atos/zac/zoeken/IndexeerService.java, src/main/java/net/atos/zac/zoeken/model/index/IndexResult.java
Fixed spotless issues on main branch.
Solves PZ-2132
=> chore: fixed spotless issues on main branch

src/main/app/src/app/dashboard/taak-zoeken-card/taak-zoeken-card.component.html, src/main/app/src/app/dashboard/taak-zoeken-card/taak-zoeken-card.component.ts, src/main/app/src/app/dashboard/zaak-zoeken-card/zaak-zoeken-card.component.html, src/main/app/src/app/dashboard/zaak-zoeken-card/zaak-zoeken-card.component.ts
The dashboard cards weren't taking the server side pagination into account.
Solves PZ-1899
=> feat: use server pagination in zoeken-cards

Dockerfile
Partly overriding labels inherited by the base Docker image that we use.
Solves PZ-2148
=> chore: set labels in our Dockerfile

src/test/kotlin/net/atos/zac/app/taken/TakenRESTServiceTest.kt, src/test/kotlin/org/flowable/task/api/history/ApiHistoryFixtures.kt
Check unnecessary stubs in TakenRESTServiceTest and fixed issues in the TakenRESTServiceTest class.
Solves PZ-2170
=> chore: fix issues in TakenRESTServiceTest

src/main/java/net/atos/zac/app/admin/converter/RESTCaseDefinitionConverter.java, src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java, src/main/java/net/atos/zac/documentcreatie/converter/DataConverter.java, src/main/java/net/atos/zac/flowable/FlowableTaskService.java, src/main/java/net/atos/zac/signalering/event/SignaleringEventObserver.java, src/main/java/net/atos/zac/zoeken/IndexeerService.java, src/main/java/net/atos/zac/zoeken/converter/TaakZoekObjectConverter.java, src/main/java/net/atos/zac/zoeken/converter/ZaakZoekObjectConverter.java, src/main/kotlin/net/atos/zac/app/signaleringen/SignaleringenRestService.kt, src/main/kotlin/net/atos/zac/app/taken/TakenRESTService.kt, src/main/kotlin/net/atos/zac/app/taken/converter/RESTTaakHistorieConverter.kt, src/main/kotlin/net/atos/zac/app/zaken/ZakenRESTService.kt, src/main/kotlin/net/atos/zac/app/zaken/converter/RESTOpenstaandeTakenConverter.kt, src/main/kotlin/net/atos/zac/signalering/SignaleringenJob.kt, src/main/kotlin/net/atos/zac/signalering/SignaleringenZACHelper.kt, src/test/kotlin/net/atos/zac/app/zaken/ZakenRESTServiceTest.kt, src/test/kotlin/net/atos/zac/zoeken/IndexeerServiceTest.kt, src/test/kotlin/net/atos/zac/zoeken/converter/ZaakZoekObjectConverterTest.kt, src/test/kotlin/net/atos/zac/zoeken/converter/ZoekenConverterFixtures.kt
Renamed TakenService to FlowableTaskService to make it more clear what it is and to prepare for a new TakenService
Fixes PZ-2171
=> feat: rename takenservice for more clarity

helm/Chart.lock, helm/Chart.yaml, helm/templates/config.yaml, helm/values.yaml
=> feat: add opentel collector to helm chart

build.gradle.kts, src/itest/kotlin/nl/lifely/zac/itest/PlanItemsRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/TakenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt, src/main/java/net/atos/zac/websocket/WebSocketServerEndPoint.java, src/main/java/net/atos/zac/websocket/event/ScreenEventObserver.java, src/main/java/net/atos/zac/websocket/event/ScreenEventType.java, src/main/kotlin/net/atos/zac/app/taken/TakenRESTService.kt, src/main/kotlin/net/atos/zac/app/taken/model/RESTTaakVerdelenGegevens.kt, src/main/kotlin/net/atos/zac/task/TaskService.kt, src/main/kotlin/net/atos/zac/zaken/ZakenService.kt, src/test/kotlin/net/atos/zac/app/taken/TakenRESTServiceTest.kt, src/test/kotlin/net/atos/zac/task/TaskServiceTest.kt, src/test/kotlin/net/atos/zac/zaken/ZakenServiceTest.kt
Made assigning tasks in task service asynchronous. 
Solves PZ-1958
=> feat: make assigning tasks asynchronous

.github/workflows/build-test-deploy.yml, .github/workflows/codeql.yml
According to: https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md
Solves PZ-2186
=> chore: upgraded obsolete Gradle GitHub actions 

scripts/docker-compose/imports/keycloak/realm.json
Add recordmanager to keycloak roles
Solves PZ-2189
=> feat: stack roles

src/main/kotlin/net/atos/zac/task/TaskService.kt, src/main/kotlin/net/atos/zac/zaken/ZakenService.kt, src/main/kotlin/nl/lifely/zac/opentelemetry/OpenTelemetry.kt, src/test/kotlin/net/atos/zac/task/TaskServiceTest.kt, src/test/kotlin/net/atos/zac/zaken/ZakenServiceTest.kt
Added OpenTelemetry tracing for releasing and assigning zaken and tasks.
Solves PZ-2198
=> chore: add opentelemetry tracing for releasing and assigning zaken and tasks

scripts/docker-compose/imports/keycloak/realm.json, src/main/java/net/atos/zac/authentication/UserPrincipalFilter.java, src/test/kotlin/net/atos/zac/authentication/UserPrincipalFilterTest.kt
In lijn met andere applicaties gaan we de rollen vastleggen in de property "rollen" in de root van het JWT.
Resolves PZ-1862
=> feat: use roles property directly in jwt

src/test/kotlin/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTServiceTest.kt, src/test/kotlin/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverterTest.kt, src/test/kotlin/net/atos/zac/app/planitems/PlanItemsRESTServiceTest.kt, src/test/kotlin/net/atos/zac/app/taken/TakenRESTServiceTest.kt, src/test/kotlin/net/atos/zac/app/zaken/ZakenRESTServiceTest.kt, src/test/kotlin/net/atos/zac/policy/output/PolicyOutputFixtures.kt, src/test/kotlin/net/atos/zac/shared/helper/OpschortenZaakHelperTest.kt
uses allDeny fixtures by default to test access/deny scenarios
Solves PZ-2219
=> feat: add unit tests for policies

src/main/app/src/app/informatie-objecten/informatie-objecten.service.ts, src/main/app/src/app/shared/utils/form-data.ts
There was a bug in the handling of dates when updating a document.
Resolves PZ-2235
=> fix: handling of dates in form data for documenten

src/itest/kotlin/nl/lifely/zac/itest/ZakenRESTServiceCompleteTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZakenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt, src/main/java/net/atos/client/zgw/shared/ZGWApiService.java, src/main/java/net/atos/zac/app/planitems/PlanItemsRESTService.java
Fixed failing integration test that completes (and re-opens) a zaak.
Solves PZ-2134
=> fix: fix failing integration test that completes (and re-opens) a zaak

src/main/kotlin/net/atos/client/zgw/ztc/ZTCClientService.kt, src/test/kotlin/net/atos/client/zgw/ztc/ZTCClientServiceTest.kt, src/test/kotlin/net/atos/zac/aanvraag/ProductaanvraagServiceTest.kt
Add unnecessary stubbing check to some more unit tests. Also switch to constructor injection in service classes.
Solves PZ-2181
=> chore: add unnecessary stubbing check to more unit tests

src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java, src/main/java/net/atos/zac/mail/MailService.java, src/test/kotlin/net/atos/client/zgw/shared/model/ZGWApiServiceTest.kt, src/test/kotlin/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTServiceTest.kt, src/test/kotlin/net/atos/zac/app/taken/TakenRESTServiceTest.kt, src/test/kotlin/net/atos/zac/app/taken/converter/RESTTaakHistorieConverterTest.kt, src/test/kotlin/net/atos/zac/mail/MailServiceTest.kt
Added unnecessary stub checks to a few more unit tests. Switched to constructor injection in services. Cleaned up unit tests.
Solves PZ-2248
=> chore: add unnecessary stub check to more unit tests

build.gradle.kts, gradle/libs.versions.toml, src/itest/kotlin/nl/lifely/zac/itest/CsvRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt, src/main/java/net/atos/zac/csv/CsvService.java
Added basic integration test for the CSV REST service.
Solves PZ-2260
=> chore: add integration test for the CSV REST service

src/main/java/net/atos/zac/policy/PolicyService.java, src/main/java/net/atos/zac/policy/output/WerklijstRechten.java, src/main/resources/policies/werklijst-rechten.rego, src/test/kotlin/net/atos/zac/policy/PolicyServiceTest.kt, src/test/kotlin/net/atos/zac/policy/output/PolicyOutputFixtures.kt
Actually using it will be done in another change.
Solves PZ-2056
=> feat: added zaken-taken-exporteer OPA permission

src/itest/kotlin/nl/lifely/zac/itest/NotificationsTest.kt
websockets integration test was brittle
Solves PZ-2284
=> chore: fix brittle integration test

src/main/java/net/atos/zac/mailtemplates/MailTemplateHelper.java, src/main/kotlin/net/atos/zac/app/taken/converter/RESTTaakConverter.kt
Check if task due date is null when sending signalering for task.
Solves PZ-2303
=> fix: check if task due date is null when sending signalering for task

src/main/kotlin/net/atos/zac/task/TaskService.kt, src/main/kotlin/net/atos/zac/zaak/ZaakService.kt
Added OpenTelemetry @SpanAttribute annotations to measure certain function arguments in the OpenTelemetry tracing data. See: https://opentelemetry.io/docs/languages/java/automatic/annotations/
Solves PZ-2312
=> chore: added OpenTelemetry @SpanAttribute annotations

.github/workflows/build-test-deploy.yml, src/test/kotlin/net/atos/zac/task/TaskServiceTest.kt
Use standard GitHub Docker build action to speed up build on GitHub.
Solves PZ-2329
=> chore: use standard GitHub Docker build action 

build.gradle.kts
Added Detekt check for our Gradle build file.
Solves PZ-2326
=> chore: add Detekt check for our Gradle build file

docs/solution-architecture/accessControlPolicies.md, src/main/java/net/atos/zac/app/klanten/converter/RESTPersoonConverter.java
Updated the access control policies doc to explain how the new ZAC authorisation architecture works with regards to roles.
Solves PZ-2311
=> chore: updated the access control policies doc 

.env.example, docker-compose.yaml
=> feat: update BAG url to point to prod

src/main/kotlin/net/atos/zac/task/TaskService.kt, src/main/kotlin/net/atos/zac/zaak/ZaakService.kt, src/test/kotlin/net/atos/zac/app/taken/TakenRESTServiceTest.kt, src/test/kotlin/net/atos/zac/app/taken/model/TakenRESTFixtures.kt, src/test/kotlin/net/atos/zac/task/TaskServiceTest.kt, src/test/kotlin/net/atos/zac/zaak/ZakenServiceTest.kt
Release case / task during assignment when no employee is selected
Solves PZ-2217
=> chore: release case / task during assignment when no employee is selected

src/main/java/net/atos/zac/flowable/FlowableTaskService.java, src/main/java/net/atos/zac/flowable/exception/TaskNotFoundException.java, src/main/java/net/atos/zac/flowable/model/ValueChangeData.java, src/main/kotlin/net/atos/zac/app/taken/converter/RESTTaakHistorieConverter.kt, src/test/kotlin/net/atos/zac/flowable/FlowableTaskServiceTest.kt
Added custom task not found exception to be able to implement proper error handling when a task is not found.
Solves PZ-2287
=> chore: add custom task not found exception 

src/main/kotlin/net/atos/zac/task/TaskService.kt, src/test/kotlin/net/atos/zac/task/TaskServiceTest.kt, src/test/kotlin/net/atos/zac/zaak/ZaakServiceTest.kt
Continue with taken verdelen when an open task is not found. #minor
Solves PZ-2332
=> feat: continue taken verdelen when task is not found

src/main/java/net/atos/zac/flowable/FlowableTaskService.java, src/main/kotlin/net/atos/zac/task/TaskService.kt, src/test/kotlin/net/atos/zac/task/TaskServiceTest.kt
In assigning tasks only release a task if it was actually assigned. #minor
Solves PZ-2350
=> feat: in assigning tasks only release a task if it was actually assigned

src/main/kotlin/net/atos/zac/task/TaskService.kt
Change log level back to fine in task service after troubleshooting.
Solves PZ-2336
=> chore: change log level back to fine in task service

src/main/kotlin/net/atos/zac/signalering/SignaleringenService.kt
Added OpenTelemetry tracing span attribute for listZakenSignaleringen.
Solves PZ-2362
=> chore: added OpenTelemetry tracing span attribute for listZakenSignaleringen

src/main/kotlin/net/atos/zac/app/signaleringen/converter/RESTSignaleringInstellingenConverter.kt, src/main/kotlin/net/atos/zac/app/signaleringen/model/RESTSignaleringInstellingen.kt, src/main/kotlin/net/atos/zac/signalering/SignaleringenPredicateHelper.kt, src/main/kotlin/net/atos/zac/signalering/SignaleringenService.kt
Only enforce transactions for functions where data in our database is actually changed.
Solves PZ-2379
=> fix: do not enforce the creation of a transaction for reading signaleringen

docs/development/installDockerCompose.md, scripts/docker-compose/docker-compose.linux.override.yml, scripts/docker-compose/setup-linux.sh
Without override Postgres volumes get 999 as user and cannot be deleted on start
Solves PZ-2414
=> fix: restore docker override for Linux

src/main/kotlin/net/atos/zac/app/zaken/ZakenRESTService.kt, src/main/kotlin/net/atos/zac/signalering/SignaleringenService.kt
Removed a few unneeded calls to .stream() in Kotlin code.
Solves PZ-2423
=> chore: removed a few unneeded calls to .stream() in Kotlin code

docs/solution-architecture/README.md, docs/solution-architecture/observabilityArchitecture.md
Add a C4 Component diagram with details about the setup for operations' observability requirements.
Solves PZ-2266
=> feat(doc): observability architecture diagram

src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java, src/main/java/net/atos/zac/policy/PolicyService.java, src/main/java/net/atos/zac/policy/input/TaakData.java, src/main/resources/policies/taak-rechten.rego, src/test/resources/policies/taak-rechten_test.rego
Assume open taak means open zaak
Solves PZ-2413
=> feat: remove zaak_open check for taak-rechten policies

src/main/java/net/atos/client/brp/BRPClientService.java, src/main/java/net/atos/zac/aanvraag/ProductaanvraagService.java, src/main/java/net/atos/zac/notificaties/NotificatieReceiver.java, src/test/kotlin/net/atos/zac/aanvraag/ProductaanvraagServiceTest.kt, src/test/kotlin/net/atos/zac/notificaties/NotificatieReceiverTest.kt
No longer validate productaanvraag dimpact on name but instead on required attributes.
Solves PZ-2492
=> feat: no longer validate productaanvraag dimpact on name

src/main/app/src/app/core/service/util.service.ts, src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts
By first extracting the progress snackbar component from the zaken-werkvoorraad component, we can re-use it when consolidating the Task releasement/assignment UX
Solves PZ-2561
=> chore: extract progress snackbar component from zaken-werkvoorraad component

src/main/java/net/atos/zac/aanvraag/InboxProductaanvraagService.java, src/main/java/net/atos/zac/aanvraag/ProductaanvraagService.java, src/test/kotlin/net/atos/client/zgw/zrc/model/ZrcFixtures.kt, src/test/kotlin/net/atos/client/zgw/ztc/model/ZtcFixtures.kt, src/test/kotlin/net/atos/zac/aanvraag/AanvraagFixtures.kt, src/test/kotlin/net/atos/zac/aanvraag/ProductaanvraagServiceTest.kt
Fixed nullpointer exception when a productaanvraag results in an inbox productaanvraag.
Solves PZ-2500
=> fix: fixed nullpointer exception when a productaanvraag results in an inbox productaanvraag

build.gradle.kts
Reorganised Gradle build file a little bit by moving all tasks together.
Solves PZ-2548
=> chore: reorganised Gradle build file a little bit by moving all tasks together

start-docker-compose.sh
Added option to start Docker Compose environment with local ZAC Docker Image without (re)building it.
Solves PZ-2569
=> chore: added option to start Docker Compose environment with local ZAC Docker Image without (re)building it

src/main/java/net/atos/client/contactmomenten/ContactmomentenClient.java, src/main/java/net/atos/client/klanten/KlantenClient.java, src/main/java/net/atos/client/zgw/shared/util/ZGWClientHeadersFactory.java, src/main/java/net/atos/client/zgw/zrc/model/Geometry.java, src/main/java/net/atos/zac/app/contactmomenten/ContactmomentenRESTService.java
Clean up code a little.
Solves PZ-2590
=> chore: cleaned up code

src/main/java/net/atos/client/zgw/zrc/model/Zaak.java, src/main/java/net/atos/zac/documentcreatie/DocumentCreatieService.java, src/main/java/net/atos/zac/documentcreatie/converter/DataConverter.java, src/main/java/net/atos/zac/documentcreatie/model/Data.java, src/main/java/net/atos/zac/documentcreatie/model/DocumentCreatieGegevens.java, src/main/java/net/atos/zac/notificaties/NotificatieReceiver.java, src/test/kotlin/net/atos/client/sd/model/SdFixtures.kt, src/test/kotlin/net/atos/client/zgw/zrc/model/ZrcFixtures.kt, src/test/kotlin/net/atos/client/zgw/ztc/ZTCClientServiceTest.kt, src/test/kotlin/net/atos/client/zgw/ztc/model/ZtcFixtures.kt, src/test/kotlin/net/atos/zac/app/planitems/PlanItemsRESTServiceTest.kt, src/test/kotlin/net/atos/zac/documentcreatie/DocumentCreatieServiceTest.kt, src/test/kotlin/net/atos/zac/documentcreatie/model/DocumentCreatieFixtures.kt, src/test/kotlin/net/atos/zac/zoeken/IndexeerServiceTest.kt, src/test/kotlin/net/atos/zac/zoeken/converter/ZaakZoekObjectConverterTest.kt
Added unit test for DocumentCreatieService. Switched to constructor injection. Other minor code improvements.
Solves PZ-2594
=> chore: add unit test for DocumentCreatieService

helm/templates/config.yaml
=> feat: quote the integer snmp port

scripts/docker-compose/imports/objects-api/fixtures/demodata.json, src/main/java/net/atos/client/zgw/shared/util/JsonbConfiguration.java, src/main/java/net/atos/zac/aanvraag/ProductaanvraagService.java, src/main/java/net/atos/zac/aanvraag/util/GeometryTypeEnumJsonAdapter.java, src/test/kotlin/net/atos/zac/aanvraag/ProductaanvraagServiceTest.kt
Added support for converting coordinates in zaakgegevens in a productaanvraag to actual zaak coordinates.
Solves PZ-2497
=> feat: add support for converting coordinates in zaakgegevens in a productaanvraag to actual zaak coordinates

start-docker-compose.sh
Fail when specifying conflicting options (local and last-known-good ZAC image; build and use image; build and use local)
Solves: PZ-2605
=> fix: check for conflicting start-docker-compose options

src/e2e/features/7-taken-verdelen.feature, src/e2e/step-definitions/taken-verdelen.ts
Update the e2e tests to align with the new task release/assign UX
Solves PZ-2634
=> chore: update e2e tests for the new task release/assign UX

helm/Chart.yaml, helm/values.yaml
solves PZ-2385
thnx Andy for the suggestions!
=> feat: opentel overrides changed from null to {} to prevent warnings

src/itest/kotlin/nl/lifely/zac/itest/InformatieObjectenTest.kt, src/main/app/src/app/informatie-objecten/informatie-object-edit/informatie-object-edit.component.ts, src/main/app/src/app/informatie-objecten/informatie-objecten.service.ts, src/main/app/src/app/informatie-objecten/model/enkelvoudig-informatie-object-versie-gegevens.ts, src/main/java/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverter.java, src/main/java/net/atos/zac/app/informatieobjecten/model/RESTEnkelvoudigInformatieObjectVersieGegevens.java
Changing the document type for a new document version is now supported.
Solves PZ-2390
=> feat: allow changing the document type for a new document version

docs/solution-architecture/openFormulierenIntegration.md, src/main/java/net/atos/client/klanten/KlantenClientService.java, src/main/java/net/atos/client/kvk/KVKClientService.java, src/main/java/net/atos/client/zgw/shared/model/Results.java, src/main/java/net/atos/client/zgw/zrc/ZRCClientService.java, src/main/java/net/atos/zac/app/admin/ZaakafhandelParametersRESTService.java, src/main/java/net/atos/zac/app/admin/converter/RESTZaakafhandelParametersConverter.java, src/main/java/net/atos/zac/app/inboxdocumenten/InboxDocumentenRESTService.java, src/main/java/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectDownloadService.java, src/main/java/net/atos/zac/app/ontkoppeldedocumenten/OntkoppeldeDocumentenRESTService.java, src/main/java/net/atos/zac/configuratie/ConfiguratieService.java, src/main/java/net/atos/zac/documenten/InboxDocumentenService.java, src/main/java/net/atos/zac/enkelvoudiginformatieobject/EnkelvoudigInformatieObjectLockService.java, src/main/java/net/atos/zac/formulieren/FormulierDefinitieService.java, src/main/java/net/atos/zac/gebruikersvoorkeuren/GebruikersvoorkeurenService.java, src/main/java/net/atos/zac/healthcheck/HealthCheckService.java, src/main/java/net/atos/zac/mailtemplates/MailTemplateService.java, src/main/java/net/atos/zac/zaaksturing/ReferentieTabelService.java, src/main/java/net/atos/zac/zaaksturing/ZaakafhandelParameterBeheerService.java, src/main/java/net/atos/zac/zaaksturing/model/ZaakafhandelParameters.java, src/main/java/net/atos/zac/zoeken/ZoekenService.java, src/main/java/net/atos/zac/zoeken/converter/DocumentZoekObjectConverter.java
Cleaned up code a bit. Improved error handling in ZaakafhandelParameterBeheerService.
Solves PZ-2641
=> chore: cleaned up code a bit

src/main/app/src/app/informatie-objecten/informatie-object-edit/informatie-object-edit.component.ts
The field order in the new document version form did not match the new document form.
Solves PZ-2646
=> chore: re-arrange the field order for the new document version form to match the new document form

src/main/app/src/app/informatie-objecten/informatie-object-edit/informatie-object-edit.component.ts
Resolve a typo causing the main build to fail
Solves PZ-2654
=> fix: reference to wrong variable

docker-compose.yaml, src/itest/kotlin/nl/lifely/zac/itest/config/ProjectConfig.kt, start-docker-compose.sh
Use correct environment variable for SMTP user name
Fix start docker-compose with local image build
Remove unneeded SMTP environments for integration tests
Solves: PZ-2652
=> fix: local docker-compose setup

src/main/app/src/app/informatie-objecten/informatie-object-edit/informatie-object-edit.component.ts, src/main/app/src/app/shared/material-form-builder/form/form/form.component.ts, src/main/app/src/app/shared/material-form-builder/model/form-config-builder.ts, src/main/app/src/app/shared/material-form-builder/model/form-config.ts
Adding a new version of a document makes no sense if you don't change any data first.
Solves PZ-2406
=> feat: require the user to make changes before they can submit a new document version

src/main/app/src/app/dashboard/taken-card/taken-card.component.ts, src/main/app/src/app/signaleringen.service.ts, src/main/app/src/app/signaleringen/model/signalering-taak-summary.ts, src/main/kotlin/net/atos/zac/app/signaleringen/SignaleringenRestService.kt, src/main/kotlin/net/atos/zac/app/signaleringen/converter/RESTSignaleringTaakConverter.kt, src/main/kotlin/net/atos/zac/app/signaleringen/model/RESTSignaleringTaakSummary.kt, src/test/kotlin/net/atos/zac/app/signaleringen/converter/RESTSignaleringTaakConverterTest.kt
Only fetch relevant data for task alerts and skip unnecessary policy checks to improve performance.
Solves PZ-2413
=> feat: fetch task alerts in a more performant way

src/itest/kotlin/nl/lifely/zac/itest/NotificationsTest.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt, src/main/java/net/atos/zac/aanvraag/ProductaanvraagService.java, src/main/kotlin/net/atos/zac/aanvraag/AanvraagToZgwConverter.kt, src/test/kotlin/net/atos/zac/aanvraag/ProductaanvraagServiceTest.kt
Set zaakgeometry from productaanvraag zaakgegevens if present. #minor
Solves PZ-2669
=> feat: set zaakgeometry from productaanvraag

helm/templates/delete-old-signaleringen-cron-job.yaml, helm/values.yaml
Added delete old signaleringen kubernetes cronjob.  #minor
Solves PZ-2675
=> feat: add delete old signaleringen kubernetes cronjob

helm/templates/signaleren-cron-job.yaml, src/main/kotlin/net/atos/zac/app/admin/SignaleringAdminRESTService.kt, src/main/kotlin/net/atos/zac/mail/MailService.kt, src/main/kotlin/net/atos/zac/mail/model/Bronnen.kt, src/test/kotlin/net/atos/zac/mail/MailServiceTest.kt
Fixed failing task signaleringen emails.
Solves PZ-2710
=> fix: fixed failing task signaleringen emails

helm/templates/signaleren-delete-cron-job.yaml, src/main/kotlin/net/atos/zac/signalering/SignaleringenJob.kt
use delete http method in cronjob
Solves P-2786
=> fix: use delete http method in cronjob

src/main/kotlin/net/atos/zac/mail/MailService.kt, src/main/kotlin/net/atos/zac/signalering/SignaleringenService.kt
Decrease log level when sending emails as it is sensitive information.
Solves PZ-2787
=> chore: decrease log level when sending emails

src/main/app/src/app/shared/directives/file-drag-and-drop.directive.ts, src/main/app/src/app/shared/material-form-builder/form-components/file-input/file-input-control.ts, src/main/app/src/app/shared/material-form-builder/form-components/file-input/file-input.component.ts, src/main/app/src/app/shared/material-form-builder/form-components/file/file.component.ts
Simplified file input and fixed drag & drop.
Resolves PZ-2632
=> fix: drag & drop to file input

src/main/kotlin/net/atos/zac/smartdocuments/rest/SmartDocumentsRESTService.kt
Protect SmartDocuments REST endpoints with beheren policy
Solves PZ-2780
=> feat: use beheren for SmartDocuments template assignment

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.ts, src/main/app/src/app/shared/side-nav/menu-item/menu-item.ts, src/main/app/src/app/shared/side-nav/menu-item/subscription-button-menu-item.ts, src/main/app/src/app/shared/side-nav/side-nav.component.html, src/main/app/src/app/shared/side-nav/side-nav.component.less, src/main/app/src/app/shared/side-nav/side-nav.component.ts
Disable buttons in side-nav while waiting for backend to respond, to avoid errors caused by double clicking
Resolves PZ-2625
=> feat: disable buttons in side-nav while waiting for backend to respond

src/itest/kotlin/nl/lifely/zac/itest/SmartDocumentsTest.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt, src/main/kotlin/net/atos/zac/smartdocuments/SmartDocumentsException.kt, src/main/kotlin/net/atos/zac/smartdocuments/SmartDocumentsService.kt, src/main/kotlin/net/atos/zac/smartdocuments/rest/SmartDocumentsExceptionMapper.kt, src/main/kotlin/net/atos/zac/smartdocuments/rest/SmartDocumentsRESTService.kt, src/main/kotlin/net/atos/zac/smartdocuments/templates/SmartDocumentsTemplateConverter.kt, src/test/kotlin/net/atos/zac/smartdocuments/templates/SmartDocumentsTemplateConverterTest.kt
Validates that REST parameters are present in SmartDocuments templates and groups
Solves: PZ-2779
=> feat: implement rest parameters validation

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.ts, src/main/kotlin/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectRestService.kt
wait for event to re-enable (un)lock buttons
fix unlock policy check
Solves: PZ-2558
=> fix: wait for event to re-enable (un)lock buttons

src/main/kotlin/net/atos/zac/smartdocuments/templates/model/SmartDocumentsTemplate.kt, src/main/kotlin/net/atos/zac/smartdocuments/templates/model/SmartDocumentsTemplateGroup.kt, src/main/resources/schemas/V58__document_templates.sql, src/main/resources/schemas/V58__smartdocuments_document_creation_templates.sql
Rename template to document_creation_template
Rename template_group to document_creation_template_group
Solves: PZ-2876
=> feat: rename template and template_group DB tables to smartdocuments_document_creation_*

src/main/app/src/app/admin/admin.module.ts, src/main/app/src/app/admin/parameter-edit/parameter-edit.component.html, src/main/app/src/app/admin/parameter-edit/parameter-edit.component.ts, src/main/app/src/app/admin/parameter-edit/smart-documents/smart-documents-tree.component.spec.ts, src/main/app/src/app/admin/parameter-edit/smart-documents/smart-documents-tree.component.ts, src/main/app/src/app/admin/smart-documents.service.ts, src/main/app/src/app/shared/material/material.module.ts
Add the front end screen for managing the smart documents templates per case type.
Resolves PZ-2394
=> feat: smart documents beheerscherm

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.ts, src/main/app/src/app/policy/model/document-rechten.ts, src/main/app/src/app/policy/model/zaak-rechten.ts, src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts, src/main/java/net/atos/zac/app/policy/converter/RESTRechtenConverter.java, src/main/java/net/atos/zac/app/policy/model/RESTDocumentRechten.java, src/main/java/net/atos/zac/app/policy/model/RESTZaakRechten.java
Use correct rights in front end to enable/disable case/document functionality for recordmanager / functional manager
Resolves PZ-2820
=> chore: use correct rights in front end to enable/disable case/document functionality for recordmanager / functional manager

src/main/java/net/atos/zac/policy/PolicyService.java, src/test/kotlin/net/atos/client/zgw/drc/model/DrcFixtures.kt, src/test/kotlin/net/atos/zac/enkelvoudiginformatieobject/model/EnkelvoudigInformatieObjectFixtures.kt, src/test/kotlin/net/atos/zac/policy/PolicyServiceTest.kt
Signature flag for OPA is now correctly set
Solves: PZ-2909
=> fix: document signature flag for OPA

src/itest/kotlin/nl/lifely/zac/itest/SmartDocumentsTest.kt, src/main/kotlin/net/atos/client/smartdocuments/SmartDocumentsClient.kt, src/main/kotlin/net/atos/zac/smartdocuments/SmartDocumentsException.kt, src/main/kotlin/net/atos/zac/smartdocuments/SmartDocumentsService.kt, src/main/kotlin/net/atos/zac/smartdocuments/rest/RESTSmartDocumentsTemplate.kt, src/main/kotlin/net/atos/zac/smartdocuments/rest/RESTSmartDocumentsTemplateGroup.kt, src/main/kotlin/net/atos/zac/smartdocuments/rest/SmartDocumentsExceptionMapper.kt, src/main/kotlin/net/atos/zac/smartdocuments/templates/SmartDocumentsTemplateConverter.kt, src/main/kotlin/net/atos/zac/smartdocuments/templates/model/SmartDocumentsTemplate.kt, src/main/kotlin/net/atos/zac/smartdocuments/templates/model/SmartDocumentsTemplateGroup.kt, src/test/kotlin/net/atos/client/smartdocuments/model/SmartDocumentsResponseFixtures.kt, src/test/kotlin/net/atos/zac/smartdocuments/rest/SmartDocumentsRESTFixtures.kt, src/test/kotlin/net/atos/zac/smartdocuments/templates/SmartDocumentsTemplateConverterTest.kt, src/test/kotlin/net/atos/zac/smartdocuments/templates/model/SmartDocumentsModelFixtures.kt
Adds license headers
Solves PZ-2911
=> chore: add license headers in smartdocuments related files

docker-compose.yaml
Upgraded technical docker compose images.
Solves PZ-2920
=> chore: upgrade technical docker compose images

src/main/kotlin/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectRestService.kt, src/main/resources/policies/document-rechten.rego, src/test/resources/policies/document-rechten_test.rego
Locked unlinked documents should be allowed to be unlocked
Resolves PZ-2921
=> chore: allow unlocking unlinked documents

src/main/app/src/app/informatie-objecten/informatie-objecten.service.ts
Beschrijving was missing when uploading a new informatieobject
Resolves PZ-2741
=> chore: include beschrijving when creating an informatieobject

src/main/java/net/atos/zac/app/admin/ReferentieTabelRESTService.java, src/main/java/net/atos/zac/app/admin/ReferentieTabelRestService.java, src/main/java/net/atos/zac/app/admin/converter/RESTHumanTaskReferentieTabelConverter.java, src/main/java/net/atos/zac/app/admin/converter/RESTReferentieTabelConverter.java, src/main/java/net/atos/zac/app/admin/converter/RESTReferentieWaardeConverter.java, src/main/java/net/atos/zac/zaaksturing/ReferentieTabelBeheerService.java, src/main/java/net/atos/zac/zaaksturing/ReferentieTabelService.java, src/main/java/net/atos/zac/zaaksturing/model/ReferentieTabel.java, src/main/kotlin/net/atos/zac/smartdocuments/SmartDocumentsService.kt, src/main/resources/schemas/V59__referentie_tabel_server_error_pagina_tekst.sql, src/test/kotlin/net/atos/zac/app/admin/ReferentieTabelRestServiceTest.kt, src/test/kotlin/net/atos/zac/zaaksturing/model/ZaaksturingFixtures.kt
Add reference table for texts for server errors on error page in the backend.
Solves PZ-2668
=> feat: add reference table for texts for server errors on error page

src/main/java/net/atos/zac/app/admin/HealthCheckRESTService.java, src/main/java/net/atos/zac/app/admin/MailtemplateBeheerRESTService.java, src/main/java/net/atos/zac/app/admin/MailtemplateKoppelingRESTService.java, src/main/java/net/atos/zac/app/admin/converter/RESTCaseDefinitionConverter.java, src/main/java/net/atos/zac/app/admin/converter/RESTHumanTaskParametersConverter.java, src/main/java/net/atos/zac/app/admin/converter/RESTHumanTaskReferentieTabelConverter.java, src/main/java/net/atos/zac/app/admin/converter/RESTMailtemplateConverter.java, src/main/java/net/atos/zac/app/admin/converter/RESTMailtemplateKoppelingConverter.java, src/main/java/net/atos/zac/app/admin/converter/RESTReferentieTabelConverter.java, src/main/java/net/atos/zac/app/admin/converter/RESTReferentieWaardeConverter.java, src/main/java/net/atos/zac/app/admin/converter/RESTReplyToConverter.java, src/main/java/net/atos/zac/app/admin/converter/RESTUserEventListenerParametersConverter.java, src/main/java/net/atos/zac/app/admin/converter/RESTZaakAfzenderConverter.java, src/main/java/net/atos/zac/app/admin/converter/RESTZaakafhandelParametersConverter.java, src/main/java/net/atos/zac/app/admin/converter/RESTZaakbeeindigParameterConverter.java, src/main/java/net/atos/zac/app/admin/converter/RESTZaakbeeindigRedenConverter.java, src/main/java/net/atos/zac/app/admin/converter/RESTZaaktypeOverzichtConverter.java, src/main/java/net/atos/zac/app/mailtemplate/MailtemplateRESTService.java, src/main/kotlin/net/atos/zac/app/admin/ZaakafhandelParametersRESTService.kt, src/main/kotlin/net/atos/zac/app/zaken/ZakenRESTService.kt, src/test/kotlin/net/atos/zac/app/zaken/ZakenRESTServiceTest.kt
Refactor converters in app admin package by using static methods were applicable. This makes the code simpler and much easier to test and refactor.
Solves PZ-2932
=> chore: refactor converters in app admin package

src/itest/kotlin/nl/lifely/zac/itest/InformatieObjectenTest.kt, src/main/java/net/atos/client/zgw/shared/util/HistorieUtil.java, src/main/java/net/atos/zac/app/util/LocalDateReader.java
Use 24h format in history and converters
Solves: PZ-2760
=> fix: use hour of day instead hour of ampm

src/main/kotlin/net/atos/zac/app/admin/ZaakafhandelParametersRESTService.kt
Use the same style across `ZaakafhandelParametersRESTService`
Solves: PZ-2931
=> chore: remove redundant fully qualified PolicyService usage

src/main/app/src/app/documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.html, src/main/app/src/app/documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.less
Fix the alignment of action buttons in the unlinked document list.
Resolves PZ-2941
=> chore: fix layout of action buttons in unlinked document list

src/main/app/src/app/admin/referentie-tabel.service.ts, src/main/app/src/app/fout-afhandeling/fout-afhandeling.component.html, src/main/app/src/app/fout-afhandeling/fout-afhandeling.component.ts, src/main/app/src/app/fout-afhandeling/fout-afhandeling.service.spec.ts, src/main/app/src/app/fout-afhandeling/fout-afhandeling.service.ts
Show error texts for server errors on error page in case of server errors. #minor
Solves PZ-2923
=> feat: show error text for server errors on error page

src/main/java/net/atos/zac/app/mail/MailRestService.java, src/main/java/net/atos/zac/app/planitems/PlanItemsRESTService.java, src/main/java/net/atos/zac/app/planitems/model/RESTUserEventListenerData.java, src/main/java/net/atos/zac/util/ValidationUtil.java, src/main/kotlin/net/atos/zac/mail/MailService.kt, src/main/kotlin/net/atos/zac/mail/model/MailAdres.kt, src/test/kotlin/net/atos/zac/app/mail/model/MailFixtures.kt, src/test/kotlin/net/atos/zac/app/planitems/PlanItemsRESTServiceTest.kt, src/test/kotlin/net/atos/zac/app/planitems/model/PlanItemsFixtures.kt, src/test/kotlin/net/atos/zac/mail/model/MailAdresTest.kt
Send mail on Zaak close without checking for policy
Solves: PZ-2901
=> feat: send in Zaak close

docs/manuals/inrichting-zaakafhandelcomponent.md
Added documentation to installation manual about the new SERVER_ERROR_ERROR_PAGINA_TEKST referentietabel.
Solves PZ-2943
=> chore: add documentation to installation manual about the SERVER_ERROR_ERROR_PAGINA_TEKST referentietabel

startupwithenv.bat, startupwithenv.sh
Forgot to update the local startup scripts to WildFly 31.0.1..
Solves PZ-2982
=> fix: also update the local startup scripts to WildFly 31.0.1

docker-compose.yaml, scripts/docker-compose/docker-compose.linux.override.yml
Use current user to run Solr
Solves: PZ-2980
=> feature: use non-root container for Solr on Linux

src/main/app/src/app/fout-afhandeling/dialog/fout-detailed-dialog.component.html, src/main/app/src/app/fout-afhandeling/dialog/fout-detailed-dialog.component.ts, src/main/app/src/app/fout-afhandeling/fout-afhandeling.component.ts, src/main/app/src/app/fout-afhandeling/fout-afhandeling.service.spec.ts, src/main/app/src/app/fout-afhandeling/fout-afhandeling.service.ts, src/main/kotlin/net/atos/zac/app/util/exception/RestExceptionMapper.kt
Display errors in error dialog instead of redirecting to error page.
Solves PZ-2906
=> feat: display error in dialog 

src/main/app/src/app/fout-afhandeling/dialog/fout-detailed-dialog.component.html, src/main/app/src/app/fout-afhandeling/dialog/fout-detailed-dialog.component.ts
Fix styling for detailed error dialog component
Resolves PZ-2991
=> chore: fix styling for detailed error dialog component

src/main/java/net/atos/zac/app/ontkoppeldedocumenten/OntkoppeldeDocumentenRESTService.java, src/test/kotlin/net/atos/zac/app/ontkoppeldedocumenten/OntkoppeldeDocumentenRESTServiceTest.kt
Add unit tests for deleting unlinked documents
Resolves PZ-2987
=> chore: add unit tests for deleting unlinked documents

pom.xml, src/main/app/src/app/fout-afhandeling/dialog/fout-detailed-dialog.component.ts, src/main/java/net/atos/zac/util/FlywayIntegrator.java
Removed obsolete unused code; removed obsolete code comment.
Solves PZ-2992
=> chore: cleaned up code a little bit

src/main/app/src/app/fout-afhandeling/fout-afhandeling.service.ts
Show 400 errors the same way we used to
Resolves PZ-2996
=> fix: show 400 errors the same way we used to

src/main/app/src/app/informatie-objecten/informatie-object-edit/informatie-object-edit.component.ts, src/main/app/src/assets/i18n/en.json, src/main/app/src/assets/i18n/nl.json
Fix null reference error if taal is missing from informatieobject
Solves PZ-2993
=> chore: fix null reference error if taal is missing from informatieobject

codecov.yml
Fix code coverage reporting
Resolves PZ-3021
=> fix: code coverage reporting

src/e2e/features/2-zaken-toevoegen.feature, src/e2e/features/3-open-formulieren.feature, src/e2e/features/4-external-systems.feature, src/e2e/features/5-taken-toevoegen.feature, src/e2e/step-definitions/authentication.ts, src/e2e/step-definitions/common.ts, src/e2e/step-definitions/zaak.ts, src/e2e/support/worlds/userProfiles.ts
Fix e2e tests
Resolves PZ-2999
=> chore: fix e2e tests

src/main/app/src/app/informatie-objecten/informatie-object-edit/informatie-object-edit.component.ts
Fix mapping of language on new version of document
Resolves PZ-3015
=> fix: mapping of language on new version of document

src/main/app/src/app/informatie-objecten/informatie-object-edit/informatie-object-edit.component.ts
Fix mapping of existing language to new version document
Resolve PZ-3037
=> fix: mapping of existing language to new version document

docs/solution-architecture/smartDocumentsIntegration.md
Added docs about the extra step added in the ZAC - SD integration. Also added docs about the SmartDocument DMS plugin for reference.
Solves PZ-3035
=> chore: added docs about the extra step added in the ZAC - SD integration

src/itest/kotlin/nl/lifely/zac/itest/SmartDocumentsTest.kt, src/main/app/src/app/admin/parameter-edit/smart-documents/smart-documents-tree.component.ts, src/main/app/src/app/admin/smart-documents.service.ts, src/main/kotlin/net/atos/zac/app/admin/ZaakafhandelParametersRESTService.kt, src/main/kotlin/net/atos/zac/smartdocuments/SmartDocumentsService.kt, src/main/kotlin/net/atos/zac/smartdocuments/templates/SmartDocumentsTemplateConverter.kt, src/main/kotlin/net/atos/zac/smartdocuments/templates/model/SmartDocumentsTemplate.kt, src/main/kotlin/net/atos/zac/smartdocuments/templates/model/SmartDocumentsTemplateGroup.kt, src/main/resources/schemas/V60__smartdocuments_informatie_object_type.sql, src/test/kotlin/net/atos/zac/smartdocuments/templates/SmartDocumentsTemplateConverterTest.kt
Adds informatie_object_type_uuid column in SmartDocuments tables
Solves PZ-3006
=> feat: adds informatie_object_type_uuid column in SmartDocuments tables

src/main/kotlin/net/atos/client/zgw/ztc/ZtcClientService.kt, src/main/kotlin/net/atos/zac/app/zaken/ZakenRESTService.kt, src/main/kotlin/net/atos/zac/app/zaken/converter/RESTBesluitConverter.kt, src/main/kotlin/net/atos/zac/app/zaken/converter/RESTZaakConverter.kt, src/main/kotlin/net/atos/zac/app/zaken/converter/RestBesluitConverter.kt, src/main/kotlin/net/atos/zac/app/zaken/model/RESTBesluit.kt, src/main/kotlin/net/atos/zac/app/zaken/model/RESTBesluitVastleggenGegevens.kt, src/main/resources/api-specs/zgw/brc-openapi.yaml, src/test/kotlin/net/atos/client/zgw/ztc/model/ZtcFixtures.kt, src/test/kotlin/net/atos/zac/app/zaken/ZakenRESTServiceTest.kt, src/test/kotlin/net/atos/zac/app/zaken/converter/RestBesluitConverterTest.kt, src/test/kotlin/net/atos/zac/app/zaken/model/RestZakenFixtures.kt
upgraded BRC OpenAPI spec.
Solves PZ-3038
=> chore: upgrade BRC OpenAPI spec

docker-compose.yaml
Upgraded Solr and OpenLDAP Docker containers in our Docker Compose setup. 
Solves PZ-3084
=> chore: upgrade solr and openldap docker containers

src/main/java/net/atos/zac/app/informatieobjecten/model/RESTEnkelvoudigInformatieFileUpload.java, src/main/kotlin/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectRestService.kt
Fixed input validation in backend for enkelvoudiginformatieobjectrestservice.
Solves PZ-3085
=> fix: fix input validation in backend for enkelvoudiginformatieobjectrestservice

src/itest/kotlin/nl/lifely/zac/itest/SmartDocumentsTest.kt, src/main/app/src/app/admin/parameter-edit/smart-documents/smart-documents-tree.component.spec.ts, src/main/app/src/app/admin/parameter-edit/smart-documents/smart-documents-tree.component.ts, src/main/app/src/app/admin/smart-documents.service.ts, src/main/app/src/app/informatie-objecten/informatie-object-verplaats.service.ts, src/main/app/src/app/zaken/model/zaaktype.ts, src/main/kotlin/net/atos/zac/app/admin/ZaakafhandelParametersRESTService.kt, src/main/kotlin/net/atos/zac/smartdocuments/SmartDocumentsService.kt, src/main/kotlin/net/atos/zac/smartdocuments/rest/RESTSmartDocumentsTemplate.kt, src/main/kotlin/net/atos/zac/smartdocuments/templates/SmartDocumentsTemplateConverter.kt, src/main/kotlin/net/atos/zac/smartdocuments/templates/model/SmartDocumentsTemplateGroup.kt, src/main/resources/schemas/V61__smartdocuments_remove_informatie_object_type_from_group.sql, src/test/kotlin/net/atos/zac/smartdocuments/rest/SmartDocumentsRESTFixtures.kt, src/test/kotlin/net/atos/zac/smartdocuments/templates/SmartDocumentsTemplateConverterTest.kt, src/test/kotlin/net/atos/zac/smartdocuments/templates/model/SmartDocumentsModelFixtures.kt
feat: refactor smart documents admin to work with document types
Resolves PZ-3008
=> feat: refactor smart documents admin to work with document types

src/main/java/net/atos/zac/zoeken/IndexeerService.java
Renamed methods in IndexeerService that still refer to the old way of 'marking for indexing'.
Solves PZ-3104
=> chore: rename methods in IndexeerService

src/main/app/src/app/klanten/zoek/bedrijven/bedrijf-zoek.component.html, src/main/app/src/app/klanten/zoek/bedrijven/bedrijf-zoek.component.ts, src/main/app/src/app/klanten/zoek/personen/persoon-zoek.component.ts
Clear fields. Plus clear search result list, since after opening form, the previous found entries in the list can still be selected, but then there is information missing and linking fails (error in console).
Resolves: PZ-2882
=> feat: involved form - clear form fields and list after selecting and adding

scripts/docker-compose/imports/objects-api/fixtures/demodata.json, src/itest/kotlin/nl/lifely/zac/itest/CsvRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/InformatieObjectenTest.kt, src/itest/kotlin/nl/lifely/zac/itest/MailRestServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/NotificationsTest.kt, src/itest/kotlin/nl/lifely/zac/itest/PlanItemsRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/SignaleringenRestServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/TakenRESTServiceCompleteTest.kt, src/itest/kotlin/nl/lifely/zac/itest/TakenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZaakHistorieTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZakenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ProjectConfig.kt
Added second productaanvraag to integration tests to prepare for supporting productaanvragen with a vestiging as initiator.
Solves PZ-3124
=> chore: add second productaanvraag to integration tests

src/main/java/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverter.java, src/main/kotlin/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectRestService.kt, src/test/kotlin/net/atos/client/zgw/zrc/model/ZrcFixtures.kt, src/test/kotlin/net/atos/client/zgw/ztc/model/ZtcFixtures.kt, src/test/kotlin/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectRestServiceTest.kt, src/test/kotlin/net/atos/zac/app/informatieobjecten/model/InformatieObjectenRESTFixtures.kt
Fixed issue with incorrect conversion to mutablelist in ZAC. Part of the linking deelzaken to zaken functionality.
Solves PZ-3123
=> fix: fix issue with failing conversion to mutablelist

scripts/docker-compose/imports/objects-api/fixtures/demodata.json, src/itest/kotlin/nl/lifely/zac/itest/NotificationsTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZakenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt, src/main/java/net/atos/zac/flowable/CMMNService.java, src/main/kotlin/net/atos/zac/productaanvraag/ProductaanvraagService.kt, src/test/kotlin/net/atos/zac/productaanvraag/ProductaanvraagServiceTest.kt
Added handling of vestiging initiator in productaanvraag. #minor
Solves PZ-3125
=> feat: add support for vestiging initiator role in productaanvraag

src/itest/kotlin/nl/lifely/zac/itest/ZaakHistorieTest.kt, src/main/java/net/atos/zac/app/audit/model/RESTHistorieRegel.java, src/main/kotlin/net/atos/zac/app/audit/model/RESTHistorieActie.kt, src/main/kotlin/net/atos/zac/app/zaken/converter/historie/RESTZaakHistoriePartialUpdateConverter.kt, src/main/kotlin/net/atos/zac/app/zaken/converter/historie/RESTZaakHistorieRegelConverter.kt, src/test/kotlin/net/atos/zac/app/zaken/converter/historie/RESTZaakHistorieRegelConverterTest.kt
Added the new Action column to the Case history in the backend.
Resolves PZ-2440
=> chore: add Action field to Case history (backend)

scripts/solr/reindex-zac-solr-data.sh
Extend Solr reindex script to be able to to reindex document, taak or zaak data only if needed.
Solves PZ-3101
=> chore: extend solr reindex script

src/main/kotlin/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectRestService.kt
Made code more Kotlin idiomatic. Many thanks to @bas-info-nl for the code suggestions. :-)
Solves PZ-3155
=> chore: make code more Kotlin idiomatic

.gitignore, scripts/docker-compose/check-env.sh, scripts/docker-compose/check-for-running-containers.sh, scripts/docker-compose/fix-permissions.sh, scripts/docker-compose/setup-linux.sh, src/itest/kotlin/nl/lifely/zac/itest/config/ProjectConfig.kt, start-it-with-local-env.sh
Adds a script that can configure environment variable controlling this behaviour
Solves: PZ-3153
=> feature: Allow Docker Compose volumes to be kept after IT complete

src/main/java/net/atos/zac/documentcreatie/converter/DataConverter.java, src/main/kotlin/net/atos/zac/app/zaken/ZakenRESTService.kt, src/main/kotlin/net/atos/zac/productaanvraag/ProductaanvraagService.kt, src/test/kotlin/net/atos/zac/app/zaken/ZakenRESTServiceTest.kt, src/test/kotlin/net/atos/zac/productaanvraag/ProductaanvraagServiceTest.kt
Refactored productaanvraagservice. Re-ordered and renamed functions and other small improvements.
Solves PZ-3176
=> chore: refactor productaanvraagservice

docs/manuals/inrichting-zaakafhandelcomponent.md, src/main/java/net/atos/zac/zaaksturing/model/ReferentieTabel.java, src/main/resources/schemas/V62__referentie_tabel_communicatiekanaal.sql
Added 'systeem referentietabel' and added default list of communicatiekanalen as referentietabel in the database.
Solves PZ-3064
=> chore: added communicatiekanalen as referentietabel in the database

docker-compose.yaml, scripts/docker-compose/imports/kvk-wiremock/README.md, scripts/docker-compose/imports/kvk-wiremock/__files/kvk-zoekresultaat-vestigingsnummer-000012345678-body.json, scripts/docker-compose/imports/kvk-wiremock/mappings/kvk-mapping.json, scripts/docker-compose/imports/objects-api/fixtures/demodata.json, src/itest/kotlin/nl/lifely/zac/itest/KlantenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ProjectConfig.kt, src/main/java/net/atos/client/kvk/KvkClientService.java, src/main/java/net/atos/zac/app/klanten/KlantenRESTService.java, src/main/java/net/atos/zac/app/klanten/converter/RESTVestigingsprofielConverter.java
Added integration test and WireMock mock for KlantenRESTService endpoint that uses the KVK Zoeken API.
Solves PZ-3184
=> chore: added integration test and WireMock mock for KVK Zoeken API integration

src/main/java/net/atos/client/zgw/zrc/model/GeometryType.java, src/main/kotlin/net/atos/zac/app/zaken/converter/historie/MapUtils.kt, src/main/kotlin/net/atos/zac/app/zaken/converter/historie/RESTZaakHistoriePartialUpdateConverter.kt, src/main/kotlin/net/atos/zac/app/zaken/converter/historie/RESTZaakHistorieRegelConverter.kt, src/test/kotlin/net/atos/zac/app/zaken/converter/historie/RESTZaakHistorieRegelConverterTest.kt
Cleanup typings in case history based on comments in a previous PR.
Solves PZ-3177
=> chore: cleanup typings in case history

docker-compose.yaml, scripts/docker-compose/imports/kvk-wiremock/__files/kvk-zoekresultaat-vestigingsnummer-000012345678-body.json, scripts/docker-compose/imports/kvk-wiremock/mappings/kvk-mapping.json, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt, src/main/java/net/atos/client/kvk/KvkClientService.java, src/main/java/net/atos/client/kvk/ZoekenClient.java, src/main/java/net/atos/client/kvk/model/KvkZoekenParameters.java, src/main/java/net/atos/zac/app/klanten/KlantenRESTService.java, src/main/java/net/atos/zac/app/klanten/converter/RestBedrijfConverter.java, src/main/java/net/atos/zac/documentcreatie/DocumentCreatieService.java, src/main/java/net/atos/zac/documentcreatie/converter/DocumentCreatieDataConverter.java, src/main/java/net/atos/zac/documentcreatie/model/ZaakData.java, src/main/java/net/atos/zac/mailtemplates/MailTemplateHelper.java, src/main/resources/api-specs/kvk/zoeken-openapi.yaml, src/test/kotlin/net/atos/zac/documentcreatie/DocumentCreatieServiceTest.kt
Use the KVK Zoeken V2 API.
Solves PZ-3108
=> chore: use the KVK Zoeken V2 API

src/itest/kotlin/nl/lifely/zac/itest/KlantRestServiceTest.kt, src/main/java/net/atos/client/brp/BRPClientService.java, src/main/java/net/atos/client/kvk/ZoekenClient.java, src/main/java/net/atos/client/kvk/exception/KvkClientNoResultException.java, src/main/java/net/atos/client/kvk/exception/KvkClientNoResultExceptionMapper.java, src/main/java/net/atos/zac/app/klanten/KlantRestService.java, src/main/java/net/atos/zac/app/klanten/converter/RestBedrijfConverter.java, src/main/java/net/atos/zac/app/klanten/converter/RestPersoonConverter.java, src/main/java/net/atos/zac/app/klanten/converter/RestRoltypeConverter.java, src/main/java/net/atos/zac/app/klanten/converter/RestVestigingsprofielConverter.java, src/main/java/net/atos/zac/app/klanten/model/bedrijven/RESTVestigingsprofiel.java, src/main/java/net/atos/zac/app/klanten/model/bedrijven/RestBedrijf.java, src/main/java/net/atos/zac/app/klanten/model/bedrijven/RestKlantenAdres.java, src/main/java/net/atos/zac/app/klanten/model/bedrijven/RestListBedrijvenParameters.java, src/main/java/net/atos/zac/app/klanten/model/klant/RestContactGegevens.java, src/main/java/net/atos/zac/app/klanten/model/klant/RestKlant.java, src/main/java/net/atos/zac/app/klanten/model/klant/RestRoltype.java, src/main/java/net/atos/zac/app/klanten/model/personen/RestListPersonenParameters.java, src/main/java/net/atos/zac/app/klanten/model/personen/RestPersonenParameters.java, src/main/java/net/atos/zac/app/klanten/model/personen/RestPersoon.java, src/main/kotlin/net/atos/zac/app/zaken/ZakenRESTService.kt, src/test/kotlin/net/atos/client/klanten/KlantenFixtures.kt, src/test/kotlin/net/atos/client/kvk/zoeken/model/KvkZoekenFixtures.kt, src/test/kotlin/net/atos/zac/app/klanten/KlantRestServiceTest.kt
Added unit test for KlantenRestService.java. A bit of class renaming to comply with our code conventions. Simplified code.
Solves PZ-3195
=> chore: added unit test for KlantenRestService and renamed classes

scripts/docker-compose/imports/kvk-wiremock/mappings/kvk-zoeken-naam-mapping.json, src/itest/kotlin/nl/lifely/zac/itest/KlantRestServiceTest.kt, src/main/app/src/app/klanten/zoek/bedrijven/bedrijf-zoek.component.html, src/main/app/src/app/klanten/zoek/bedrijven/bedrijf-zoek.component.ts
Fixed issue where KVK search on company name was no longer working. Also added integration test for search on company name.
Solves PZ-3212
=> fix: fix issue where KVK search on company name was no longer working

src/main/kotlin/net/atos/zac/app/taken/TakenRESTService.kt, src/test/kotlin/net/atos/client/zgw/drc/model/DrcFixtures.kt, src/test/kotlin/net/atos/zac/app/taken/TakenRESTServiceTest.kt
Allow missing (null) description on completing a taak with send document.
Solves: PZ-3077
=> fix: allow missing description on taak completion

src/itest/kotlin/nl/lifely/zac/itest/TaskRestServiceCompleteTest.kt, src/itest/kotlin/nl/lifely/zac/itest/TaskRestServiceTest.kt, src/main/app/src/app/admin/parameter-edit/parameter-edit.component.ts, src/main/java/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverter.java, src/main/java/net/atos/zac/app/zoeken/model/RESTTaakZoekObject.java, src/main/java/net/atos/zac/flowable/FlowableTaskService.java, src/main/java/net/atos/zac/flowable/util/TaskUtil.java, src/main/java/net/atos/zac/zoeken/IndexeerService.java, src/main/java/net/atos/zac/zoeken/model/zoekobject/TaakZoekObject.java, src/main/kotlin/net/atos/zac/app/admin/ZaakafhandelParametersRESTService.kt, src/main/kotlin/net/atos/zac/app/task/TaskRestService.kt, src/main/kotlin/net/atos/zac/app/task/converter/RestTaskConverter.kt, src/main/kotlin/net/atos/zac/app/task/converter/RestTaskHistoryConverter.kt, src/main/kotlin/net/atos/zac/app/task/model/RestTask.kt, src/main/kotlin/net/atos/zac/app/task/model/RestTaskAssignData.kt, src/main/kotlin/net/atos/zac/app/task/model/RestTaskDistributeData.kt, src/main/kotlin/net/atos/zac/app/task/model/RestTaskDistributeTask.kt, src/main/kotlin/net/atos/zac/app/task/model/RestTaskDocumentData.kt, src/main/kotlin/net/atos/zac/app/task/model/RestTaskHistoryLine.kt, src/main/kotlin/net/atos/zac/app/task/model/RestTaskReleaseData.kt, src/main/kotlin/net/atos/zac/app/task/model/TaakSortering.kt, src/main/kotlin/net/atos/zac/app/task/model/TaakStatus.kt, src/main/kotlin/net/atos/zac/task/TaskService.kt, src/test/kotlin/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverterTest.kt, src/test/kotlin/net/atos/zac/app/task/TaskRestServiceTest.kt, src/test/kotlin/net/atos/zac/app/task/converter/RestTaskHistoryConverterTest.kt, src/test/kotlin/net/atos/zac/app/task/model/TaskRestFixtures.kt, src/test/kotlin/net/atos/zac/task/TaskServiceTest.kt
Renamed 'taken' backend package and code to comply with our coding conventions. Also translated to English.
Solves PZ-3225
=> chore: rename 'taken' package and code to comply with our coding conventions

src/itest/kotlin/nl/lifely/zac/itest/InformatieobjectenHistorieTest.kt, src/itest/kotlin/nl/lifely/zac/itest/InformatieobjectenTest.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt
Checks the file history
Solves: PZ-3226
=> feature: add integration test for Informatieobjecten historie

src/main/app/src/app/admin/parameter-edit/parameter-edit.component.ts
ZAPS - Save form fields intake and afronden status emails
Resolves: PZ-3044
=> fix: PZ-3044 - ZAPS - Save form fields intake and afronden status emails

src/main/app/src/app/admin/parameter-edit/smart-documents/smart-documents-tree.component.html, src/main/app/src/app/admin/parameter-edit/smart-documents/smart-documents-tree.component.less, src/main/app/src/app/admin/parameter-edit/smart-documents/smart-documents-tree.component.ts
Add vertrouwelijkheid to smart documents tree
Resolves: PZ-3168
=> feat: PZ-3168 - admin - smart documents - add vertrouwelijkheidsniveau - cherry picked

src/main/java/net/atos/zac/documentcreatie/converter/DocumentCreatieDataConverter.java, src/main/java/net/atos/zac/flowable/TaakVariabelenService.java, src/main/java/net/atos/zac/flowable/ZaakVariabelenService.java, src/main/java/net/atos/zac/mailtemplates/MailTemplateHelper.java, src/main/java/net/atos/zac/policy/PolicyService.java, src/main/java/net/atos/zac/zoeken/converter/TaakZoekObjectConverter.java, src/main/kotlin/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectRestService.kt, src/main/kotlin/net/atos/zac/app/task/TaskRestService.kt, src/main/kotlin/net/atos/zac/app/task/converter/RestTaskConverter.kt, src/main/kotlin/net/atos/zac/signalering/SignaleringService.kt
Cleaned up code.
Solves PZ-3257
=> chore: clean up code

.gitignore, start-it-with-local-env.sh
before starting integration tests run the script if available
Solves: PZ-3265
=> fix: use check-for-running-containers.sh when available

src/itest/kotlin/nl/lifely/zac/itest/InformatieobjectenHistorieTest.kt, src/main/kotlin/net/atos/zac/app/audit/converter/RESTHistorieRegelConverter.kt
Action is now converted from audit trail data
Solves: PZ-3263
=> feature: add action to the info object history response

src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.html, src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.ts
Refresh document list after unlinking and a minor aligning center issue when no data available
Resolves: PZ-3140
=> fix: PZ-3140 - refresh document list after unlinking

CODE_OF_CONDUCT.md, CONTRIBUTING.md
Added code of conduct. See: https://opensource.guide/code-of-conduct/
Solves PZ-3274
=> chore: added code of conduct

src/main/java/net/atos/zac/policy/PolicyService.java, src/test/kotlin/net/atos/client/zgw/shared/ZGWApiServiceTest.kt, src/test/kotlin/net/atos/client/zgw/ztc/ZTCClientServiceTest.kt, src/test/kotlin/net/atos/zac/app/admin/ReferentieTabelRestServiceTest.kt, src/test/kotlin/net/atos/zac/app/csv/CsvRESTServiceTest.kt, src/test/kotlin/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectRestServiceTest.kt, src/test/kotlin/net/atos/zac/app/ontkoppeldedocumenten/OntkoppeldeDocumentenRESTServiceTest.kt, src/test/kotlin/net/atos/zac/app/planitems/PlanItemsRESTServiceTest.kt, src/test/kotlin/net/atos/zac/app/signalering/converter/RESTSignaleringTaakConverterTest.kt, src/test/kotlin/net/atos/zac/app/task/TaskRestServiceTest.kt, src/test/kotlin/net/atos/zac/app/task/converter/RestTaskHistoryConverterTest.kt, src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt, src/test/kotlin/net/atos/zac/app/zaak/converter/historie/RESTZaakHistorieRegelConverterTest.kt, src/test/kotlin/net/atos/zac/authentication/UserPrincipalFilterTest.kt, src/test/kotlin/net/atos/zac/flowable/TaakVariabelenServiceTest.kt, src/test/kotlin/net/atos/zac/mail/MailServiceTest.kt, src/test/kotlin/net/atos/zac/policy/PolicyServiceTest.kt, src/test/kotlin/net/atos/zac/productaanvraag/ProductaanvraagServiceTest.kt, src/test/kotlin/net/atos/zac/shared/helper/OpschortenZaakHelperTest.kt, src/test/kotlin/net/atos/zac/signalering/SignaleringServiceTest.kt, src/test/kotlin/net/atos/zac/task/TaskServiceTest.kt, src/test/kotlin/net/atos/zac/util/JsonbConfigurationTest.kt, src/test/kotlin/net/atos/zac/websocket/SessionRegistryTest.kt, src/test/kotlin/net/atos/zac/zaak/ZaakServiceTest.kt, src/test/kotlin/net/atos/zac/zoeken/IndexeerServiceTest.kt, src/test/kotlin/nl/lifely/zac/test/config/ZacTestConfig.kt, src/test/kotlin/nl/lifely/zac/test/listener/MockkClearingTestListener.kt, src/test/resources/kotest.properties
Added overall ZacTestConfig where clearAllMocks is done. This simplifies our test code makes our test tests more unified.
Solves PZ-3276
=> chore: add overall ZacTestConfig where clearAllMocks is done

src/itest/kotlin/nl/lifely/zac/itest/ReferenceTableRestServiceTest.kt, src/main/kotlin/net/atos/zac/admin/ReferenceTableAdminService.kt, src/main/kotlin/net/atos/zac/admin/ReferenceTableService.kt, src/main/kotlin/net/atos/zac/admin/model/ReferenceTable.kt, src/main/kotlin/net/atos/zac/admin/model/ReferenceTableValue.kt, src/main/kotlin/net/atos/zac/app/admin/ReferenceTableRestService.kt, src/main/kotlin/net/atos/zac/app/admin/ZaakafhandelParametersRESTService.kt, src/main/kotlin/net/atos/zac/app/admin/model/RestReferenceTable.kt, src/main/kotlin/net/atos/zac/app/admin/model/RestReferenceTableValue.kt, src/test/kotlin/net/atos/zac/admin/ReferenceTableServiceTest.kt, src/test/kotlin/net/atos/zac/admin/model/AdminFixtures.kt, src/test/kotlin/net/atos/zac/app/admin/ReferenceTableRestServiceTest.kt
Added isSystemValue to RestReferenceTableValue and expose it in reference table endpoint. Added integration test.
Solves PZ-3293
=> feat: expose isSystemValue in reference table endpoint(s)

src/itest/kotlin/nl/lifely/zac/itest/ReferenceTableRestServiceTest.kt, src/main/kotlin/net/atos/zac/admin/ReferenceTableAdminService.kt, src/main/kotlin/net/atos/zac/admin/model/ReferenceTable.kt, src/main/kotlin/net/atos/zac/app/admin/ReferenceTableRestService.kt, src/main/kotlin/net/atos/zac/app/admin/model/RestReferenceTable.kt, src/main/kotlin/net/atos/zac/app/admin/model/RestReferenceTableUpdate.kt, src/main/kotlin/net/atos/zac/app/admin/model/RestReferenceTableValue.kt, src/test/kotlin/net/atos/zac/admin/ReferenceTableAdminServiceTest.kt, src/test/kotlin/net/atos/zac/admin/ReferenceTableServiceTest.kt, src/test/kotlin/net/atos/zac/admin/model/AdminFixtures.kt, src/test/kotlin/net/atos/zac/app/admin/AppAdminFixtures.kt, src/test/kotlin/net/atos/zac/app/admin/ReferenceTableRestServiceTest.kt, src/test/kotlin/net/atos/zac/app/task/TaskRestServiceTest.kt, src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt
Added backend validation for reference system tables and reference table system values.
Solves PZ-3345
=> feat: add backend validation for reference tables

src/main/app/src/app/admin/model/referentie-tabel-waarde.ts, src/main/app/src/app/admin/referentie-tabel/referentie-tabel.component.html, src/main/kotlin/net/atos/zac/app/admin/ReferenceTableRestService.kt, src/test/kotlin/net/atos/zac/app/admin/ReferenceTableRestServiceTest.kt
Do not show delete button for reference system values. #minor
Solves PZ-3294
=> feat: do not show delete button for reference system values

.github/workflows/clean-up-old-zac-docker-images.yml
Added GitHub Workflow to automatically remove ZAC Docker Images.  **DRAFT PR for now, just for testing**
Solves PZ-3351
=> feat: add GitHub Workflow to automatically remove ZAC Docker Images

src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt, src/test/kotlin/net/atos/zac/app/task/TaskRestServiceTest.kt, src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt
Attempt to improved handling of unit tests that test code in which coroutines are created.
Solves PZ-3383
=> chore: improve handling of unit tests that test code in which coroutines are created

src/main/java/net/atos/client/zgw/zrc/model/NatuurlijkPersoon.java
Do not use klant models in ZGW
Solves: PZ-3384
=> fix: remove dependency between ZGW and Klant models

src/itest/kotlin/nl/lifely/zac/itest/ReferenceTableRestServiceTest.kt, src/main/kotlin/net/atos/zac/admin/ReferenceTableAdminService.kt, src/main/kotlin/net/atos/zac/admin/ReferenceTableService.kt, src/main/kotlin/net/atos/zac/app/admin/ReferenceTableRestService.kt, src/main/kotlin/net/atos/zac/app/admin/model/RestReferenceTable.kt, src/main/kotlin/net/atos/zac/app/admin/model/RestReferenceTableUpdate.kt, src/main/resources/schemas/V65__referentie_tabel_constraint_upper_on_code.sql, src/test/kotlin/net/atos/zac/app/admin/AppAdminFixtures.kt
Made reference table code uppercase. Fixed issue where reference table code could no longer be changed.
Solves PZ-3360
=> feat: make reference table code uppercase

src/main/app/src/app/admin/referentie-tabel/referentie-tabel.component.html
Make reference table system values read only in frontend.
Solves PZ-3424
=> fix: make reference table system values read only in frontend

helm/Chart.yaml, helm/templates/config.yaml, helm/templates/secret.yaml, helm/values.yaml
merge into generic open klant 2 branch
=> feat: modification to helm chart for open klant 2.0

CONTRIBUTING.md, README.md
Added coding conventions to developer docs.
Solves PZ-3427
=> chore: add coding conventions to developer docs

scripts/docker-compose/imports/openzaak-database/database/4-setup-zac-config-after.sql
Updated additional OpenZaak database sequences so that a new zaaktype version can be created locally from the OpenZaak user interface.
Solves PZ-3467
=> chore: update additional OpenZaak database sequences

src/main/java/net/atos/zac/policy/PolicyService.java, src/main/java/net/atos/zac/zoeken/converter/ZaakZoekObjectConverter.java, src/main/java/net/atos/zac/zoeken/model/ZaakIndicatie.java, src/test/kotlin/net/atos/zac/policy/PolicyServiceTest.kt, src/test/kotlin/net/atos/zac/zoeken/converter/ZaakZoekObjectConverterTest.kt, src/test/resources/policies/zaak-rechten_test.rego
Enum values are displayed in the UI. New values should not appear there
Solves: PZ-3472
=> fix: remove BESLOTEN and INTAKE zaak indicatie

src/main/kotlin/net/atos/zac/app/zaak/model/RestBesluitVastleggenGegevens.kt
Made toelichting field optional when creating a besluit.
Solves PZ-3509
=> fix: toelichting should be optional when creating a besluit

src/e2e/features/2-zaken-toevoegen.feature, src/e2e/features/8-persoon.feature, src/e2e/step-definitions/persoon.ts, src/e2e/step-definitions/zaak.ts
open zaak 2.1 - e2e tests
Resolves: PZ-3523
=> feat: PZ-3523 - open zaak 2.1 - e2e tests

src/main/app/src/app/documenten/inbox-documenten-list/inbox-documenten-list.component.ts, src/main/app/src/app/documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.ts, src/main/app/src/app/klanten/klant-zaken-tabel/klant-zaken-tabel.component.ts, src/main/app/src/app/productaanvragen/inbox-productaanvragen-list/inbox-productaanvragen-list.component.ts, src/main/app/src/app/shared/dynamic-table/datasource/zoeken-data-source.ts, src/main/app/src/app/taken/taken-mijn/taken-mijn.component.ts, src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.ts, src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.ts, src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.ts, src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts
FE -  reset search page index on exiting lists
Resolves: PZ-3378
=> fix: PZ-3378 - FE -  reset search page index on exiting lists

src/e2e/step-definitions/zaak.ts
Fix for failing e2e test
Resolves: PZ-3567
=> fix: failing e2e test fixe

src/main/java/net/atos/zac/solr/SolrDeployerService.java, src/main/java/net/atos/zac/solr/schema/SolrSchemaV5.java, src/main/java/net/atos/zac/zoeken/model/ZaakIndicatie.java, src/test/kotlin/net/atos/zac/solr/SolrDeployerServiceTest.kt
Add unit test for solr deployer service, improved code and added code documentation.
Solves PZ-3603
=> chore: add unit test for solr deployer service

scripts/docker-compose/imports/keycloak/realm.json, src/test/kotlin/net/atos/zac/admin/model/AdminFixtures.kt, src/test/kotlin/net/atos/zac/app/planitems/PlanItemsRESTServiceTest.kt, src/test/kotlin/net/atos/zac/authentication/UserPrincipalFilterTest.kt, src/test/kotlin/net/atos/zac/signalering/ZaakTaskDueDateEmailNotificationServiceTest.kt
Cleaned up code and improved unit test and integration test data for zaakafhandelparameters and UserPrincipalFilterTest.
Solves PZ-3605
=> chore: clean up code and unit test and integration test data for zaakafhandelparameters and UserPrincipalFilterTest

docs/development/INSTALL.md, docs/development/README.md, docs/development/managingSolr.md, src/main/java/net/atos/zac/zoeken/model/ZaakIndicatie.java
Added developer docs on how to update the ZAC Solr schema.
Solves PZ-3544
=> docs: add developer docs on how to update the ZAC Solr schema

src/main/java/net/atos/zac/app/klant/KlantRestService.java, src/main/java/net/atos/zac/app/klant/converter/KlantcontactConverter.java, src/main/java/net/atos/zac/app/klant/converter/RestPersoonConverter.java, src/main/java/net/atos/zac/app/klant/converter/RestVestigingsprofielConverter.java, src/test/kotlin/net/atos/zac/app/klant/KlantRestServiceTest.kt
Improved klant converter Java classes by making methods that can be static static. This reduces complexity and increases testability.
Solves PZ-3607
=> chore: improve klant converter Java classes by making methods static

docker-compose.yaml
PZ-3602 - dev-local - maykinmedia-objecttypes-api to 2.1.3
Resolves: PZ-3602
=> chore: PZ-3602 - dev-local - maykinmedia-objecttypes-api to 2.1.3

docs/manuals/ZAC-gebruikershandleiding/ZAC-gebruikershandleiding.md
Textual additions and corrections to the ZAC manual and improvement for the convert to pdf option (page break). 
Solves PZ-2513 and 3381
=> docs: ZAC-gebruikershandleiding.md verbeteringen voor het converteren naar pdf

src/itest/kotlin/nl/lifely/zac/itest/DocumentCreationRestServiceTest.kt, src/main/kotlin/net/atos/zac/smartdocuments/SmartDocumentsTemplatesService.kt
Return 400 error instead of 500 when no template mapping exists
Solves: PZ-3643
=> feature: improve error handling on creating SmartDocuments DOC file

src/main/app/src/app/shared/dynamic-table/datasource/zoeken-data-source.ts
remove leftover console logs
Solves: orphaned PR
=> feat: remove leftover console logs

src/main/app/src/app/plan-items/model/user-event-listener-data.ts, src/main/app/src/app/zaken/intake-afronden-dialog/intake-afronden-dialog.component.ts, src/main/app/src/app/zaken/zaak-afhandelen-dialog/zaak-afhandelen-dialog.component.ts
Merge doUserEventListenerPlanItem and send/{zaakUuid} calls in frontend
Solves: PZ-3670
=> feat: PZ-3670 Merge doUserEventListenerPlanItem and send/{zaakUuid} calls in frontend

.github/dependabot.yml, gradle/libs.versions.toml, src/e2e/package-lock.json, src/e2e/package.json, src/main/app/package-lock.json, src/main/app/package.json
Use only node LTS version
Solves: PZ-3671
=> feature: use only node LTS version

src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt, src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt, src/test/kotlin/net/atos/zac/app/zaak/model/RestZakenFixtures.kt
Use existing logic for extending final date
Solves: PZ-3420
=> feature: shift task final dates according to zaak final date

src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt, src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt
Get rid of number of day calculation and add additional checks for back in time case
Solves: PZ-3691
=> feature: simplify fatal date shift logic

src/main/java/net/atos/zac/app/planitems/PlanItemsRESTService.java, src/test/kotlin/net/atos/zac/app/planitems/PlanItemsRESTServiceTest.kt
Task fatal date is now limited by zaak fatal date
Solves: PZ-3697
=> fix: new task fatal date is now limited by zaak fatal date

.github/dependabot.yml
Explicitly specify @types/node as package name
Solves: PZ-3671
=> fix: do not update node for e2e tests

src/main/java/net/atos/zac/admin/model/ZaakafhandelParameters.java, src/main/kotlin/net/atos/client/zgw/ztc/ZtcClientService.kt, src/main/kotlin/net/atos/zac/admin/model/ReferenceTable.kt, src/main/kotlin/net/atos/zac/app/documentcreation/DocumentCreationRestService.kt, src/main/kotlin/net/atos/zac/app/signalering/SignaleringRestService.kt, src/main/kotlin/net/atos/zac/app/signalering/converter/RESTSignaleringInstellingenConverter.kt, src/main/kotlin/net/atos/zac/app/signalering/converter/RestSignaleringInstellingenConverter.kt, src/main/kotlin/net/atos/zac/app/signalering/model/RestSignaleringInstellingen.kt, src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt, src/main/kotlin/net/atos/zac/app/zaak/converter/RestZaakConverter.kt, src/main/kotlin/net/atos/zac/app/zaak/converter/RestZaaktypeConverter.kt, src/main/kotlin/net/atos/zac/signalering/SignaleringPredicateHelper.kt, src/main/kotlin/net/atos/zac/signalering/SignaleringService.kt, src/main/kotlin/net/atos/zac/signalering/ZaakTaskDueDateEmailNotificationService.kt, src/test/kotlin/net/atos/zac/admin/model/AdminFixtures.kt, src/test/kotlin/net/atos/zac/app/zoeken/ZoekenFixtures.kt, src/test/kotlin/net/atos/zac/signalering/SignaleringServiceTest.kt, src/test/kotlin/net/atos/zac/signalering/ZaakTaskDueDateEmailNotificationServiceTest.kt
Remove unneeded Java stream() calls in Kotlin code. Clean Kotlin code up here and there.
Solves PZ-3703
=> core: remove unneeded java stream calls in kotlin code

pom.xml
Upgraded WildFly to 33.0.1.
Solves PZ-3712
=> chore: upgrade wildfly to 33.0.1

src/main/kotlin/net/atos/client/brp/BrpClientService.kt, src/main/kotlin/net/atos/zac/app/klant/KlantRestService.kt, src/test/kotlin/net/atos/client/klant/KlantFixtures.kt, src/test/kotlin/net/atos/zac/app/klant/KlantRestServiceTest.kt
Make retrievePersoon and retrievePersoonAsync methods more in sync so we can refactor this code later on.
Solves PZ-3752
=> chore: make retrievePersoon and retrievePersoonAsync methods more in sync

src/main/kotlin/net/atos/client/brp/BrpClientService.kt, src/main/kotlin/net/atos/zac/app/klant/KlantRestService.kt, src/test/kotlin/net/atos/client/brp/BrpClientServiceTest.kt, src/test/kotlin/net/atos/zac/app/klant/KlantRestServiceTest.kt
Run BRP and Klant API client calls in parallel.
Solves PZ-3586
=> feat: run brp and klant client calls in parallel

src/main/java/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverter.java, src/test/kotlin/net/atos/client/zgw/drc/model/DrcFixtures.kt, src/test/kotlin/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverterTest.kt
Fix vertrouwelijkheidsaanduiding in documentenlijst. Should be uppercase.
Solves PZ-3755
=> fix: fix Vertrouwelijkheidsaanduiding in documentenlijst

src/itest/kotlin/nl/lifely/zac/itest/EnkelvoudigInformatieObjectRestServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZaakRestServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/client/ZacClient.kt, src/main/java/net/atos/zac/app/informatieobjecten/converter/RestInformatieobjectConverter.java, src/main/kotlin/net/atos/zac/app/zaak/converter/RestZaakConverter.kt
Fixed vertrouwelijkheidaanduiding enum conversion when create new document version. Refactored related code.
Solves PZ-3776
=> fix: fix vertrouwelijkheidaanduiding enum conversion when create new document version

src/itest/kotlin/nl/lifely/zac/itest/ConfigurationRestServiceTest.kt, src/main/app/src/app/configuratie/configuratie.service.ts, src/main/kotlin/net/atos/zac/app/configuratie/ConfiguratieRestService.kt
Renamed configuratie service endpoints to comply with conventions.
Solves PZ-3795
=> chore: rename configuratie service endpoints to comply with conventions

src/main/app/src/app/klanten/bedrijfsgegevens/bedrijfsgegevens.component.html
removed duplicate telephone number in company details
Solves: PZ-3745
=> feat(app): removed duplicate telephone number in company details

helm/templates/config.yaml, helm/values.yaml
=> feat: add FEATURE_FLAG_BPMN_SUPPORT env var to helm chart and set to false by default

helm/templates/config.yaml, helm/values.yaml
=> fix: quote boolean as workaround

src/main/kotlin/net/atos/zac/zoeken/IndexingService.kt
Use WARNING for stopped reindexing process
Solves: PZ-3493
=> fix: increase log level for reindexing problems

src/main/java/net/atos/client/zgw/zrc/ZrcClient.java, src/main/java/net/atos/client/zgw/zrc/ZrcClientService.java, src/main/java/net/atos/client/zgw/zrc/model/ZaakUuid.java, src/main/kotlin/net/atos/zac/zoeken/IndexingService.kt, src/test/kotlin/net/atos/zac/zoeken/IndexingServiceTest.kt
Ignore exceptions during object conversion
Solves: PZ-3493
=> feature: list only Zaak UUIDs for reindexing

src/main/resources/formulieren/README.md
Added readme about BPMN PoC forms.
Solves PZ-3854
=> chore: add readme about BPMN PoC forms

docs/manuals/inrichting-zaakafhandelcomponent/inrichting-zaakafhandelcomponent.md, docs/solution-architecture/smartDocumentsIntegration.md
Remove DMS plugin section
Add redirect/callback steps
Add configuration section
Solves: PZ-3732
=> feature: Adapt the SmartDocuments integration documentation

scripts/docker-compose/imports/smartdocuments-wiremock/mappings/wsxmldeposit-wizard.json, src/main/kotlin/net/atos/client/smartdocuments/model/document/SmartDocumentsDocumentRequestDeclarations.kt, src/main/kotlin/net/atos/zac/documentcreation/DocumentCreationService.kt, src/main/kotlin/net/atos/zac/smartdocuments/SmartDocumentsTemplatesService.kt, src/main/resources/META-INF/persistence.xml
Do not load ZaakafhandelParameters on select
Disable template and template group selectors
Solves: PZ-3923
=> fix: disable template selectors for new document flow

src/main/app/package-lock.json, src/main/app/package.json
Reverts infonl/dimpact-zaakafhandelcomponent#1733
Breaks BPMN functionality
=> Revert "chore(deps): bump the npm_and_yarn group in /src/main/app with 5 updates"

src/itest/kotlin/nl/lifely/zac/itest/DocumentCreationRestServiceTest.kt, src/main/kotlin/net/atos/zac/app/documentcreation/DocumentCreationRestService.kt, src/test/kotlin/net/atos/zac/app/documentcreation/DocumentCreationRestServiceTest.kt
Cancel results in calling callback without file ID
Solves: PZ-3925
=> feature: support cancel in document creation flow

src/main/app/src/app/admin/zaakafhandel-parameters.service.ts
Use the correct backend endpoint name
Solves: PZ-3888
=> fix: url for listing zaakbeeindigredenen

gradle/libs.versions.toml
Reverts infonl/dimpact-zaakafhandelcomponent#1771
Solves: PZ-3953
=> Revert "chore(deps): bump jackson from 2.17.2 to 2.18.0"

src/main/app/src/app/zaken/zaak-view/zaak-view.component.html
Zaak view, display destroy or archiving data
Solves: PZ:3830
=> feat: zaak view - display destroy or archiving data

src/main/app/src/static/smart-documents-result.html
smart documents result page; ux feedback
Solves: PZ-4026
=> feat: smart documents result page - ux feedback

src/main/java/net/atos/zac/admin/ZaakafhandelParameterService.java, src/main/java/net/atos/zac/admin/model/ZaakafhandelParameters.java, src/main/java/net/atos/zac/admin/model/ZaakafhandelParametersBase.java, src/main/java/net/atos/zac/admin/model/ZaakafhandelParametersSummary.java, src/main/kotlin/net/atos/client/zgw/ztc/ZtcClientService.kt, src/main/kotlin/net/atos/zac/admin/ZaakafhandelParameterBeheerService.kt, src/main/kotlin/net/atos/zac/smartdocuments/SmartDocumentsTemplatesService.kt, src/main/kotlin/net/atos/zac/smartdocuments/rest/RestMappedSmartDocumentsTemplateGroup.kt, src/main/kotlin/net/atos/zac/smartdocuments/templates/model/SmartDocumentsTemplate.kt, src/main/kotlin/net/atos/zac/smartdocuments/templates/model/SmartDocumentsTemplateGroup.kt, src/test/kotlin/net/atos/zac/admin/model/AdminFixtures.kt, src/test/kotlin/net/atos/zac/smartdocuments/templates/SmartDocumentsTemplateConverterTest.kt
Reduce zaakafhandel cache size
Introduce new ZaakafhandelParametersSummary with lower memory consumption
Solves: PZ-4034
=> feature: reduce memory footprint when storing SD template mapping

Dockerfile
ZAC crashes under load on TEST
Solves: PZ-4059
=> feature: increase max heap of ZAC to 1700 MB

src/main/kotlin/net/atos/zac/app/util/UtilRestService.kt
Apache FileUtils rounds numbers (1.7GB is 1GB)
Solves: PZ-4058
=> fix: do not round memory numbers

src/main/kotlin/net/atos/zac/smartdocuments/SmartDocumentsTemplatesService.kt, src/test/kotlin/net/atos/zac/smartdocuments/SmartDocumentsTemplatesServiceTest.kt
Select only the uuid
Solves: PZ-4074
=> feature: reduce memory consumption finding information object uuid

src/main/app/src/app/klanten/koppel/klanten/klant-koppel-betrokkene.component.ts, src/main/app/src/app/klanten/koppel/klanten/klant-koppel-initiator.component.ts, src/main/app/src/app/klanten/zoek/bedrijven/bedrijf-zoek.component.ts, src/main/app/src/app/klanten/zoek/form-communicatie-service.ts, src/main/app/src/app/klanten/zoek/personen/persoon-zoek.component.ts
Betrokkene and initiator koppelen, using communications service between forms to clear data after selection
Solves: PZ-4065
=> feat: betrokkene and initiator koppelen - using communications service between forms to clear data after selection

src/main/kotlin/net/atos/client/smartdocuments/exception/SmartDocumentsBadRequestResponseExceptionMapper.kt
SmartDocuments returns BAD_REQUEST when user is not registered
Solves: PZ-4088
=> feature: improve message when unknown user is used in SD

start-docker-compose.sh
start-docker-compose script now uses proper profiles
Solves: PZ-4114
=> fix: enable ZAC to start locally

src/main/kotlin/net/atos/zac/smartdocuments/SmartDocumentsTemplatesService.kt, src/test/kotlin/net/atos/zac/smartdocuments/SmartDocumentsTemplatesServiceTest.kt
Improved error handling in case of missing mapping for SD template/group
Solves: PZ-4116
=> feature: handle not configured template or group on create document

gradle/libs.versions.toml, src/main/java/net/atos/zac/websocket/event/ScreenEventType.java
Use latest version
Solves: PZ-4039
=> feature: bump jackson to 2.18.0

src/e2e/step-definitions/zaak.ts
Change zaaktype to specific zaaktype for e2e test
Solves PZ-4075
=> feat: pz-4075-e2e-test-change

docker-compose.yaml, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt
Fixed failing Docker Compose Keycloak set up.
Solves PZ-4138
=> fix: fixed failing Docker Compose Keycloak set up

src/itest/kotlin/nl/lifely/zac/itest/DocumentCreationRestServiceTest.kt
Cover more parameters
Solves: PZ-4052
=> feature: extend document creation integration tests

src/main/kotlin/net/atos/zac/app/zaak/converter/historie/RESTZaakHistoriePartialUpdateConverter.kt, src/test/kotlin/net/atos/zac/app/zaak/converter/historie/RESTZaakHistoriePartialUpdateConverterTest.kt
Add another resource type to dates that should be d-m-y format
Solves: PZ-4146
=> fix: streefdatum is now formatted as dmy in history

gradle/libs.versions.toml, pom.xml
Upgraded to WildFly 33.0.2.
Solves PZ-4168
=> chore: upgrade to WildFly 33.0.2

src/main/kotlin/net/atos/zac/app/zaak/converter/historie/RESTZaakHistoriePartialUpdateConverter.kt, src/test/kotlin/net/atos/zac/app/zaak/converter/historie/RESTZaakHistoriePartialUpdateConverterTest.kt
Convert einddatumGepland in d-m-y format
Solves: PZ-4146
=> fix: use einddatumGepland for streefdatum

.github/workflows/update-docker-compose.yml
Added GitHub workflow to update Docker Images in our docker compose file.
Solves PZ-4172
=> chore: add GitHub workflow to update our docker compose file

src/main/app/src/styles.less
remove clearing cross from disabled input.
Solves: PZ-4087
=> feat: remove clearing cross from disabled input

src/main/app/package-lock.json, src/main/app/package.json
Upgraded eslint to 8.57.1 manually since Dependabot seems a bit broken for our frontend dependencies.
Solves PZ-4234
=> chore(deps): upgraded eslint to 8.57.1

pom.xml
Upgraded wildfly-datasources-galleon-pack to 8.0.1.Final since Dependabot does not update this dependency unfortunately.
Solves PZ-4234
=> chore(deps): upgraded wildfly-datasources-galleon-pack to 8.0.1.Final

docker-compose.yaml
Bump prometheus in Docker Compose
Automated PR created by GitHub Actions
=> docker-compose: bump prom/prometheus:v2.54.1

build.gradle.kts, src/main/app/package-lock.json
Simplified Kotlin and Java version Gradle configuration using a Gradle toolchain. See: https://www.baeldung.com/kotlin/gradle-kotlin-bytecode-version for details
Solves PZ-4245
=> chore: simplified Kotlin and Java version Gradle configuration

src/main/app/src/app/informatie-objecten/informatie-object-add/informatie-object-add.component.ts, src/main/app/src/app/informatie-objecten/informatie-object-create-attended/informatie-object-create-attended.component.ts, src/main/app/src/app/informatie-objecten/informatie-object-edit/informatie-object-edit.component.ts
fix cancel button and some more readable switch statements for form fields handling
Solves: PZ-4224
=> feat: fix cancel button

docs/solution-architecture/smartDocumentsIntegration.md
Use correct terms on SD timeline
Add Store operation in OpenZaak timeline
Solves: PZ-4274
=> fix: sequence diagram in SD solution architecture doc

renovate.json
Added Maven and Gradle wrapper support to Renovate configuration.
Solves PZ-4250
=> chore: add Maven and Gradle wrapper support to Renovate configuration

src/main/app/README.md
frontend updated readme
Solves: PZ-4269)
=> feat: frontend updated readme

src/e2e/step-definitions/external-systems.ts
E2E - auto rendered field renamed to match REST api
Solves: PZ-4251
=> feat: E2E - auto rendered field renamed to match REST api

src/main/app/src/app/shared/side-nav/side-nav.component.less
FE Fix menu button text touching right menu border
Solves: PZ-4336
=> feat: FE Fix menu button text touching right menu border

src/main/app/src/assets/i18n/en.json, src/main/app/src/assets/i18n/nl.json
Document send- mention PDF in paragraph.
Solves: PZ-4334
=> feat: document send- mention PDF in paragraph

src/main/java/net/atos/zac/app/planitems/PlanItemsRESTService.java, src/main/java/net/atos/zac/formulieren/FormulierRuntimeService.java, src/main/java/net/atos/zac/shared/helper/SuspensionZaakHelper.java, src/main/kotlin/net/atos/zac/app/task/TaskRestService.kt, src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt, src/test/kotlin/net/atos/zac/app/planitems/PlanItemsRESTServiceTest.kt, src/test/kotlin/net/atos/zac/app/task/TaskRestServiceTest.kt, src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt, src/test/kotlin/net/atos/zac/shared/helper/SuspensionZaakHelperTest.kt
Shift due and fatal dates in accordance with additional info task fatal date
Solves: PZ-3986
=> feature: shift zaak fatal date with additional info task

src/itest/kotlin/nl/lifely/zac/itest/PlanItemsRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/SignaleringRestServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/TaskRestServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZaakHistorieTest.kt
Adjust existing tests to take into account second task and new fatal date
Solves: PZ-3987
=> feature: add i-test to create task with fatal date later than zaak fatal

src/main/kotlin/net/atos/zac/app/task/model/RestTask.kt, src/main/kotlin/net/atos/zac/zoeken/IndexingService.kt, src/test/kotlin/net/atos/zac/app/task/model/TaskRestFixtures.kt
Some small code improvements in the IndexingService.kt and related classes.
Solves PZ-4410
=> chore: code improvements in the IndexingService.kt and related classes

src/e2e/features/4-external-systems.feature, src/e2e/step-definitions/external-systems.ts
Increased timeout for expect clause in e2e test for SmartDocuments flow for document to be visible in zaak.
Solves PZ-4423
=> chore: increase timeout for expect clause in e2e test for SmartDocuments flow for document to be visible in zaak

src/main/kotlin/net/atos/zac/zoeken/ZoekenService.kt
Improved error message in zoekservice (since it is currently shown in the frontend on errors) and refactored code a bit.
Solves PZ-4435
=> fix: improve error message in zoekservice 

src/itest/kotlin/nl/lifely/zac/itest/SignaleringRestServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt, src/main/java/net/atos/zac/policy/PolicyService.java, src/main/kotlin/net/atos/zac/app/signalering/SignaleringRestService.kt, src/main/kotlin/net/atos/zac/app/zaak/converter/RestZaakOverzichtConverter.kt, src/main/kotlin/net/atos/zac/signalering/SignaleringService.kt, src/test/kotlin/net/atos/zac/app/signalering/SignaleringRestServiceTest.kt, src/test/kotlin/net/atos/zac/app/signalering/model/SignaleringFixtures.kt, src/test/kotlin/net/atos/zac/app/zaak/converter/RestZaakOverzichtConverterTest.kt, src/test/kotlin/net/atos/zac/signalering/SignaleringServiceTest.kt
Add paging when fetching zaak signals
Solves: PZ-2610
=> feature: add paging when listing zaak signals

src/main/app/src/app/informatie-objecten/informatie-object-add/informatie-object-add.component.ts, src/main/app/src/app/informatie-objecten/informatie-object-create-attended/informatie-object-create-attended.component.ts, src/main/app/src/app/informatie-objecten/informatie-object-verzenden/informatie-object-verzenden.component.ts
document form findings and added subscription destroy
Solves: PZ-4256
=> feat: document form findings and added subscription destroy

helm/Chart.yaml
=> fix: remove dash from helm chart include

src/main/app/src/app/shared/batch-progress/batch-process.service.ts, src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.ts, src/main/app/src/app/zaken/zaken-vrijgeven-dialog/zaken-vrijgeven-dialog.component.html, src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts, src/main/app/src/assets/i18n/en.json, src/main/app/src/assets/i18n/nl.json
- [feat(BatchProcessService): allow option for passing a timeout](https://github.com/infonl/dimpact-zaakafhandelcomponent/commit/cf8f961d1a9de0fe2099ce0b11048d0e6b0ed0f3)
- [fix(Zaken,Taken): listen to ANY optcode for progression](https://github.com/infonl/dimpact-zaakafhandelcomponent/commit/76b4ae4a56d66832a993351735e15748688cace7)
- [chore(ZakenVrijgevenDialog): proper use of *ngIf](https://github.com/infonl/dimpact-zaakafhandelcomponent/commit/62585a7feb4de37ca183feb960d3d0444cb29d9d)
Closes [PZ-3977](https://dimpact.atlassian.net/browse/PZ-3977)
=> fix: listen to `SKIPPED` tasks on "zaak" and "taak" processing

scripts/docker-compose/imports/smartdocuments-wiremock/mappings/wsxmldeposit-wizard.json, src/itest/kotlin/nl/lifely/zac/itest/NotificationsTest.kt, src/itest/kotlin/nl/lifely/zac/itest/SignaleringRestServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZaakHistorieTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZoekenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt, src/main/kotlin/net/atos/zac/productaanvraag/ProductaanvraagService.kt, src/test/kotlin/net/atos/zac/productaanvraag/ProductaanvraagServiceTest.kt
Added productaanvraag mapping for omschrijving and toelichting zaakgegeven fields. #minor
Solves PZ-2959
=> feat: add productaanvraag mapping for omschrijving and toelichting zaakgegeven fields

src/main/kotlin/net/atos/zac/app/signalering/SignaleringRestService.kt, src/main/kotlin/net/atos/zac/signalering/SignaleringService.kt, src/test/kotlin/net/atos/zac/app/signalering/SignaleringRestServiceTest.kt, src/test/kotlin/net/atos/zac/signalering/SignaleringServiceTest.kt
No paging is needded for these dashboard types
Solves: PZ-4465
=> feature: remove paging for taken, information objects

src/main/app/src/app/shared/batch-progress/batch-process.service.ts
Resolves [PZ-4469](https://dimpact.atlassian.net/browse/PZ-4469)
=> fix(BatchProcessService): clear timeout when batch processing is stopped

docker-compose.yaml, scripts/docker-compose/imports/objects-api/fixtures/demodata.json, scripts/docker-compose/imports/objecttypes-api/fixtures/demodata.json
updates docker images and new env requirements 
solves PZ-4293 and PZ-4288
=> feat: objects and objecttypes api updates

src/itest/kotlin/nl/lifely/zac/itest/SignaleringRestServiceTest.kt, src/main/java/net/atos/zac/signalering/event/SignaleringEventObserver.java, src/main/java/net/atos/zac/signalering/model/SignaleringZoekParameters.java, src/main/kotlin/net/atos/zac/signalering/SignaleringPredicateHelper.kt, src/main/kotlin/net/atos/zac/signalering/SignaleringService.kt
Do not save a new signalering, but just update existing one's timestamp
Solves: PZ-2618
=> feature: replace existing signalering timestamp with latest

src/main/app/src/app/dashboard/zaken-card/zaken-card.component.html, src/main/app/src/app/dashboard/zaken-card/zaken-card.component.ts
Fix initial loading card with zaken with documents.
Solves: PZ-4474
=> feat: fix initial loading card with zaken with documents

src/main/resources/api-specs/or/objects-openapi.yaml, src/main/resources/api-specs/or/objecttypes-openapi.yaml
Updated both the Objects and Objecttypes OpenAPI specs. Needed to manually fix one issue in the Objects OpenAPI spec unfortunately (see code comment).
Solves PZ-4476
=> chore: updated both the Objects and Objecttypes OpenAPI specs

src/itest/kotlin/nl/lifely/zac/itest/SignaleringRestServiceTest.kt, src/main/kotlin/net/atos/zac/app/zaak/converter/RestZaakOverzichtConverter.kt, src/test/kotlin/net/atos/zac/app/zaak/converter/RestZaakOverzichtConverterTest.kt
omschrijving is needed for dashboards
Solves: PZ-4483
=> fix: return omschrijving and not toelichting for dashboards

src/itest/kotlin/nl/lifely/zac/itest/ZoekenRESTServiceTest.kt, src/main/app/src/app/shared/table-zoek-filters/facet-filter/facet-filter.component.ts, src/main/app/src/app/zoeken/model/filter-parameters.ts, src/main/app/src/app/zoeken/model/zoek-parameters.ts, src/main/app/src/app/zoeken/zoek/filters/multi-facet-filter/multi-facet-filter.component.ts, src/main/app/src/app/zoeken/zoek/zoek.component.ts, src/main/kotlin/net/atos/zac/zoeken/model/FilterParameters.kt
Use 'values' instead of 'waarden' FilterParameters.kt field also in API and frontend.
Solves PZ-4503
=> chore: use 'values' instead of 'waarden' FilterParameters.kt field also in API and frontend

.github/workflows/build-test-deploy.yml, .github/workflows/codeql.yml, CONTRIBUTING.md, docs/development/README.md, docs/development/paging.md
Describe PUT body and response
Solves: PZ-4482
=> feature: document paging specifics

.github/workflows/codeql.yml, SECURITY.md
Added a basic security policy to comply with open source community standards and because it is a good idea to have.
Solves PZ-4414
=> chore: added a basic security policy

src/main/app/src/app/informatie-objecten/informatie-object-create-attended/informatie-object-create-attended.component.ts, src/main/app/src/app/taken/taak-view/taak-view.component.html, src/main/app/src/app/taken/taak-view/taak-view.component.ts
FE; Add create attended doc form to Taak overview
Solves: PZ-4417
=> feat: FE - Add create attended doc form to Taak overview

src/main/app/src/static/smart-documents-result.html
FE - static smart documents result page - display task
Solves: PZ-4552
=> feat: FE - static smart documents result page - display task

.github/workflows/snyk-code-scan.yml, .github/workflows/trivy-docker-image-scan.yml
Add Snyk node scanning and push the results to GitHub security
solves: PZ-4558
=> fix: add Snyk node scanning and don't filter on threshold

src/main/java/net/atos/client/bag/BagClientService.java, src/main/java/net/atos/client/bag/api/AdresApi.java, src/main/java/net/atos/client/bag/api/AdresUitgebreidApi.java, src/main/java/net/atos/client/bag/api/AdresseerbaarObjectApi.java, src/main/java/net/atos/client/bag/api/AlgemeneInformatieApi.java, src/main/java/net/atos/client/bag/api/BronhouderApi.java, src/main/java/net/atos/client/bag/api/LigplaatsApi.java, src/main/java/net/atos/client/bag/api/NummeraanduidingApi.java, src/main/java/net/atos/client/bag/api/OpenbareRuimteApi.java, src/main/java/net/atos/client/bag/api/PandApi.java, src/main/java/net/atos/client/bag/api/StandplaatsApi.java, src/main/java/net/atos/client/bag/api/VerblijfsobjectApi.java, src/main/java/net/atos/client/bag/api/WoonplaatsApi.java, src/main/java/net/atos/client/klant/KlantClient.java, src/main/java/net/atos/client/kvk/BasisprofielClient.java, src/main/java/net/atos/client/kvk/VestigingsprofielClient.java, src/main/java/net/atos/client/kvk/ZoekenClient.java, src/main/java/net/atos/zac/app/productaanvragen/InboxProductaanvragenRESTService.java, src/main/java/net/atos/zac/util/MediaTypes.kt, src/main/java/net/atos/zac/webdav/WebdavHelper.java, src/main/kotlin/net/atos/client/brp/PersonenApi.kt, src/main/kotlin/net/atos/zac/app/csv/CsvRESTService.kt, src/main/kotlin/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectRestService.kt, src/main/kotlin/net/atos/zac/documentcreation/DocumentCreationService.kt, src/main/kotlin/net/atos/zac/mail/MailService.kt, src/main/kotlin/net/atos/zac/smartdocuments/SmartDocumentsService.kt
Use global constants for media types. Using https://gist.github.com/retheviper/9b4e28f66b354d9f706e43d399100676 as input. 
Solves PZ-4554
=> chore: use global constants for media types

.github/dependabot.yml, src/main/app/package-lock.json
Attempt at unfreezing dependabot 
Includes npm audit run to fix some low hanging fruit.
=> chore(deps): improve dependabot grouping

.github/pull_request_template.md
Added GitHub pull request template as recommended in the GitHub open source community guidelines. See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository for details.
Solves PZ-4579
=> chore: add GitHub pull request template

src/itest/kotlin/nl/lifely/zac/itest/HealthCheckRestServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt, src/main/app/src/app/admin/inrichtingscheck/inrichtingscheck.component.html, src/main/app/src/app/admin/model/zaaktype-inrichtingscheck.ts, src/main/app/src/assets/i18n/en.json, src/main/app/src/assets/i18n/nl.json, src/main/java/net/atos/zac/app/admin/HealthCheckRestService.java, src/main/java/net/atos/zac/app/admin/model/RESTZaaktypeInrichtingscheck.java, src/main/java/net/atos/zac/healthcheck/HealthCheckService.java, src/main/java/net/atos/zac/healthcheck/model/ZaaktypeInrichtingscheck.java, src/test/kotlin/net/atos/zac/healthcheck/HealthcheckFixtures.kt, src/test/kotlin/net/atos/zac/healthcheck/model/ZaaktypeInrichtingscheckTest.kt
Health-check for missing "additional info" status in zaak type
Solves PZ-4183
=> feature: check for additional info zaak status

src/e2e/features/5-taken-toevoegen.feature, src/e2e/utils/schemes.ts
Add the new Aanvullende informatie vereist zaak status
Solves: PZ-4590
=> fix: e2e tests

Dockerfile
Add a label to the docker image which refers to the git commit of zac. Should allow for better slack deployment messaging 
Solves PZ-4585
=> feature: added commithash as a docker image label

.github/workflows/remove-stale-branches.yml
This workflow will list branches (dry run only so far):
- no commits in last 100 days
- no open pr
- no protected branch
- no default branch
solves: PZ-4597
=> feat: remove stale branches

src/itest/kotlin/nl/lifely/zac/itest/MailRestServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZaakHistorieTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZoekenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt
Extended the mail rest service integration tests to generate a PDF from a sent email.
Solves PZ-4601
=> chore: extended the mail rest service integration tests to generate a PDF from a sent email

src/itest/kotlin/nl/lifely/zac/itest/ZaakafhandelParametersRestServiceSmartDocumentsTest.kt, src/main/kotlin/net/atos/zac/smartdocuments/rest/RestMappedSmartDocumentsTemplateGroup.kt, src/main/kotlin/net/atos/zac/smartdocuments/rest/RestSmartDocumentsTemplateGroup.kt, src/test/kotlin/net/atos/zac/smartdocuments/templates/SmartDocumentsTemplateConverterTest.kt
Removed redundant type-casts from converter code
Solves: PZ-4588
=> feature: remove redundant casts in code

src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt, src/main/kotlin/net/atos/zac/app/zaak/converter/historie/MapUtils.kt, src/main/kotlin/net/atos/zac/app/zaak/converter/historie/RestZaakHistoriePartialUpdateConverter.kt, src/main/kotlin/net/atos/zac/app/zaak/converter/historie/RestZaakHistorieRegelConverter.kt, src/main/kotlin/net/atos/zac/mail/MailMessageBuilder.kt, src/main/kotlin/net/atos/zac/mail/MailService.kt, src/main/kotlin/net/atos/zac/mail/model/Attachment.kt, src/main/kotlin/net/atos/zac/mail/model/Bronnen.kt, src/main/kotlin/net/atos/zac/mail/model/EMail.kt, src/main/kotlin/net/atos/zac/mail/model/EMails.kt, src/main/kotlin/net/atos/zac/mail/model/MailAdres.kt, src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt, src/test/kotlin/net/atos/zac/app/zaak/converter/historie/RESTZaakHistoriePartialUpdateConverterTest.kt, src/test/kotlin/net/atos/zac/app/zaak/converter/historie/RESTZaakHistorieRegelConverterTest.kt
Fix incorrect or missing spdx copyright headers.
Solves PZ-4607
=> chore: fix incorrect or missing spdx copyright headers

.github/workflows/build-test-deploy.yml, .github/workflows/check-for-conventional-commits.yml, .github/workflows/clean-up-cache-on-pr-close.yml, .github/workflows/clean-up-old-zac-docker-images.yml, .github/workflows/codeql.yml, .github/workflows/run-e2e.yml, .github/workflows/snyk-code-scan.yml, .github/workflows/trivy-docker-image-scan.yml, .github/workflows/update-gradle-wrapper.yml, .github/workflows/update-trivy-scanner-cache.yml
Pin GitHub Actions. Renovate/dependabot will be able to keep these up-to-date
Solves PZ-4614
=> chore: pin github actions.

.github/workflows/build-test-deploy.yml, scripts/file-templates/publiccode-yaml-template.yaml
Generate publiccode.yml file automatically using a simple template and the https://github.com/elieahd/templater GitHub Action.
Solves PZ-4628
=> chore: generate publiccode.yml file 

renovate.json
Rename packages in matchPackageNames to include docker.io registry
Solves: PZ-4650
=> chore: add docker.io registry to matchPackageNames

src/main/app/src/app/informatie-objecten/informatie-object-create-attended/informatie-object-create-attended.component.ts
FE - create document form - author input label fix
Solves PZ-4647
=> feat: FE - create document form - author input label fix

.env.tpl, .github/workflows/remove-stale-branches.yml, .licenserc.yaml, Dockerfile, build.gradle.kts, src/main/resources/schemas/V34__mail_template_defaults.sql, src/main/resources/schemas/V38__mail_template_defaults_revisited.sql, src/main/resources/schemas/V39__mail_template_defaults_revisited2.sql, src/main/resources/schemas/V40__taken_streef_naar_fataal.sql, src/main/resources/wildfly/configure-wildfly.cli, src/main/resources/wildfly/deploy-zaakafhandelcomponent.cli, start-it-with-local-env.sh
Added SPDX copyright header check for remaining files. Added missing SPDX headers.
Solves PZ-4622
=> chore: added SPDX copyright header check for remaining files

.github/workflows/build-test-deploy.yml, .github/workflows/run-e2e.yml, scripts/file-templates/publiccode-yaml-template.yaml
Fixed deprecated GitHub action usage (https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) and hardcodede the description fields in our publiccode.yaml template
Solves PZ-4669
=> chore: fixed deprecated GitHub action usage and hardcodede the description fields in our publiccode.yaml template

src/main/app/src/app/admin/parameter-edit/smart-documents-form/smart-documents-form.component.html, src/main/app/src/app/admin/parameter-edit/smart-documents-form/smart-documents-form.component.less, src/main/app/src/styles.less
FE fix regression introduced to other hip implementations
Solves PZ-4693
=> fix: FE fix regression introduced to other hip implementations

.gitignore
Ignore kotlin compilation dir
Solves: PZ-4695
=> feature: ignore .kotlin dir

src/main/resources/wildfly/configure-wildfly.cli
Reverted accidental increase in logging.
Solves PZ-4697
=> chore: reverted accidental increase in logging

scripts/docker-compose/imports/smartdocuments-wiremock/mappings/wsxmldeposit-wizard.json, src/itest/kotlin/nl/lifely/zac/itest/NotificationsTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZaakRestServiceHistoryTest.kt, src/itest/kotlin/nl/lifely/zac/itest/ZoekenRESTServiceTest.kt, src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt, src/main/kotlin/net/atos/zac/productaanvraag/ProductaanvraagService.kt, src/test/kotlin/net/atos/zac/productaanvraag/ProductaanvraagServiceTest.kt, src/test/kotlin/nl/lifely/zac/test/util/TestStringUtils.kt
Add default productaanvraag string to zaak explanation and no longer to zaak description.
Solves PZ-4633
=> feat: add default productaanvraag string to zaak explanation

.github/workflows/build-test-deploy.yml, .github/workflows/codeql.yml, helm/.gitignore, helm/.helmignore
Skip pull request build proces when the pull request only contains changes in the Helm Charts folder.
Solves PZ-4730
=> chore: skip pull request build proces when the pull request only contains changes in the Helm Charts folder

src/main/kotlin/net/atos/zac/app/admin/converter/RestZaakafhandelParametersConverter.kt, src/test/kotlin/net/atos/zac/app/admin/converter/RestZaakafhandelParametersConverterTest.kt
SmartDocuments is disabled by default for a zaak type
Solves: PZ-4694
=> fix: enabledForZaaktype is false by default

src/e2e/step-definitions/zaak.ts
E2E - fix Aanvullende informatie - check document instead of toast
Solves: PZ-4738
=> chore: E2E - fix Aanvullende informatie - check document instead of toast

src/main/kotlin/net/atos/zac/app/admin/ZaakafhandelParametersRestService.kt
Alternatively we can check for creeeren_document in zaak/taak
Solves: PZ-4768
=> fix: allow all users to list SmartDocuments mappings

.github/workflows/remove-stale-branches.yml
Send slack message when abandoned branches are detected
Solves PZ-4780
=> feat: alert on stale branches

.licenserc.yaml, src/main/kotlin/net/atos/client/smartdocuments/model/document/SmartDocumentsDocumentRequestDeclarations.kt, src/main/kotlin/net/atos/zac/documentcreation/converter/DocumentCreationDataConverter.kt
Upraded Galleon to 6.0.4.Final. Reorganized code a bit. Added a code comment.
Solves PZ-4791
=> chore: upraded Galleon to 6.0.4.Final

src/e2e/support/indienen-aansprakelijkstelling-door-derden/profiles/alice.ts
E2E test - grammer
Solves: PZ-4688
=> chore: E2E test - grammer

.github/workflows/remove-stale-branches.yml, docs/development/updatingDependencies.md
Remove references to dependabot documentation
Solves PZ-4860
=> chore: renovate documentation

src/main/app/src/app/zaken/zaak-create/zaak-create.component.html, src/main/app/src/app/zaken/zaak-create/zaak-create.component.less, src/main/app/src/app/zaken/zaak-create/zaak-create.component.ts, src/main/app/src/assets/i18n/en.json, src/main/app/src/assets/i18n/nl.json, src/main/app/src/styles.less
FE - Zaak create - add hint to zaak type select
Solves PZ-4312
=> feat: FE - Zaak create - add hint to zaak type select

src/main/app/src/app/zaken/intake-afronden-dialog/intake-afronden-dialog.component.html
FE - Fix detect state change radio button
Solves PZ-4901
=> feat: FE - Fix detect state change radio button

src/main/app/src/app/zaken/intake-afronden-dialog/intake-afronden-dialog.component.html, src/main/app/src/app/zaken/intake-afronden-dialog/intake-afronden-dialog.component.less, src/main/app/src/app/zaken/zaak-afhandelen-dialog/zaak-afhandelen-dialog.component.html, src/main/app/src/app/zaken/zaak-afhandelen-dialog/zaak-afhandelen-dialog.component.less
FE case close dialog styling and buttons aligment with forms
Solves: PZ-4911
=> feat: FE case close dialog styling and buttons aligment with forms

src/main/app/src/app/zaken/intake-afronden-dialog/intake-afronden-dialog.component.html, src/main/app/src/app/zaken/zaak-afhandelen-dialog/zaak-afhandelen-dialog.component.html, src/main/app/src/styles.less
FE use mat dialog title instead of a class
Solves PZ-4914
=> chore: FE use mat dialog title instead of a class

src/itest/kotlin/nl/lifely/zac/itest/client/HttpClientHelper.kt, src/itest/kotlin/nl/lifely/zac/itest/client/ItestHttpClient.kt, src/main/kotlin/net/atos/zac/admin/ZaakafhandelParameterBeheerService.kt, src/test/kotlin/net/atos/zac/admin/ZaakafhandelParameterBeheerServiceTest.kt, src/test/kotlin/net/atos/zac/smartdocuments/rest/RestSmartDocumentsTemplateGroupTest.kt, src/test/kotlin/net/atos/zac/smartdocuments/rest/SmartDocumentsRestFixtures.kt, src/test/kotlin/net/atos/zac/smartdocuments/rest/SmartDocumentsValidatorKtTest.kt, src/test/kotlin/net/atos/zac/smartdocuments/templates/SmartDocumentsTemplateConverterTest.kt
When publishing a new version of a zaaktype it will ensure the smart document settings are copied over
Solves [PZ-4793](https://dimpact.atlassian.net/browse/PZ-4793)
=> feat(ZaakafhandelParameterBeheerService): copy smart documents settings

src/main/kotlin/net/atos/zac/admin/ZaakafhandelParameterBeheerService.kt
Reverted code that left entities in the entitymanager, but detached, and failed on storing the entities.
Solves PZ-4793
=> fix: entitymanager storing detached entities fails

src/main/kotlin/net/atos/zac/app/documentcreation/DocumentCreationRestService.kt, src/main/kotlin/net/atos/zac/configuratie/ConfiguratieService.kt, src/main/kotlin/net/atos/zac/documentcreation/DocumentCreationService.kt, src/test/kotlin/net/atos/zac/app/documentcreation/DocumentCreationRestServiceTest.kt, src/test/kotlin/net/atos/zac/configuratie/ConfiguratieServiceTest.kt, src/test/kotlin/net/atos/zac/documentcreation/DocumentCreationServiceTest.kt
Move SmartDocuments related code to DocumentCreationService
Solves: PZ-4983
=> feature: move SmartDocuments URL building to DocumentCreationService

scripts/docker-compose/imports/openldap/zac-scripts/zac-ldap-setup-template.ldif, src/itest/kotlin/nl/info/zac/itest/IdentityServiceTest.kt, src/itest/kotlin/nl/info/zac/itest/config/ItestConfiguration.kt, src/main/java/net/atos/zac/formulieren/FormulierRuntimeService.java, src/main/java/net/atos/zac/mailtemplates/MailTemplateHelper.java, src/main/kotlin/net/atos/zac/identity/IdentityService.kt, src/main/kotlin/net/atos/zac/identity/model/User.kt, src/test/kotlin/net/atos/zac/documentcreation/converter/DocumentCreationDataConverterTest.kt, src/test/kotlin/net/atos/zac/identity/IdentityServiceTest.kt
Fix nulls in user full name when the user does not have a first name.
Solves PZ-4989
=> fix: fix nulls in user full name when the user does not have a first name

helm/templates/config.yaml
Treat RSIN numbers as strings and not numbers
Solves PZ-4845
=> fix: treat rsin numbers as string and not number

docker-compose.yaml
Add explanatory text in docker compose.yaml for ZAC Office Converter
Solves PZ-5019
=> chore: Add explanatory text in docker compose.yaml for ZAC Office Converter

docs/manuals/installation-guide/installation-guide.md
=> fix: links to helm chart from installation manual

.github/workflows/build-test-deploy.yml
Use the versioned docker image in the provisioning run
Solves PZ-1495
=> feat: trigger provisioning run with versioned tag

src/main/java/net/atos/zac/util/time/ZonedDateTimeAdapter.java, src/main/kotlin/net/atos/zac/app/admin/model/RESTBuildInformation.kt, src/main/kotlin/net/atos/zac/healthcheck/HealthCheckService.kt, src/main/kotlin/net/atos/zac/healthcheck/model/BuildInformatie.kt
Serialize/Deserialize ZonedDateTime with timezone
Use ZonedDateTime for build date
Solves PZ-5072
=> feature: provide timezone for build date

src/main/app/src/app/identity/model/group.ts, src/main/app/src/app/identity/model/user.ts, src/main/app/src/app/shared/material-form-builder/form-components/medewerker-groep/medewerker-groep.component.ts, src/main/app/src/app/zaken/zaak-create/zaak-create.component.ts
FE - zaak create set default user
Solves PZ-5087
=> fix(app): zaak create set default user

.github/workflows/build-test-deploy.yml, renovate.json
Attempt at renovate regexManager config for the publiccode.yaml file
Solves PZ-5082
=> feat: publiccode.yaml management by renovate

src/main/app/src/app/shared/version/version.component.html
FE - disable DEV build texts
Solves pz 5058
Local DEV OLD:
Local DEV NEW:
=> feat(app): disable local DEV build texts

renovate.json
Don't propose version updates that are known to be problematic
Solves PZ-5041
=> chore(deps): Pin versions in renovate config

src/main/app/src/app/shared/material-form-builder/form-components/medewerker-groep/medewerker-groep.component.spec.ts, src/main/app/src/app/shared/material-form-builder/form-components/medewerker-groep/medewerker-groep.component.ts, src/main/app/src/app/shared/order/order-util.spec.ts, src/main/app/src/app/shared/order/order-util.ts, src/main/app/src/app/zaken/zaak-create/zaak-create.component.spec.ts
- tests that the employee is being set when the group changes
- tests that the group is being set when the `zaaktype` changes
- Made de `OrderUtil.orderBy` type save & added tests
Solves [PZ-5078](https://dimpact.atlassian.net/browse/PZ-5078)
=> test(creat-zaak): added some tests to validate user is being properly set

.github/workflows/build-test-deploy.yml, renovate.json
Automerge the renovate updates to publiccode.yaml
Solves PZ-5115
=> feat: automerge renovate publiccode.yaml updates

build.gradle.kts, node_modules/.package-lock.json
Clean gradle configuration-cache
Clean App node_modules
Split clean task into cleanApp and cleanE2e
Solves: PZ-5068
=> chore(build): improve clean process

build.gradle.kts
Fix helm-docs download on darwin_arm64 (osx_aarch_64)
Solves PZ-5156
=> fix: helm-docs for darwin-arm64

src/main/resources/api-specs/brp/brp-openapi.yaml
Upgraded the BRP OpenAPI specification used by ZAC.
Solves PZ-5169
=> chore: upgraded the BRP OpenAPI specification used by ZAC

src/main/kotlin/net/atos/zac/admin/ZaakafhandelParameterBeheerService.kt, src/test/kotlin/net/atos/zac/admin/ZaakafhandelParameterBeheerServiceTest.kt, src/test/kotlin/net/atos/zac/admin/model/AdminFixtures.kt
Copy zaak afzenders in ZaakafhandelParameters
Solves PZ-5173
=> fix: copy zaak afzenders in ZaakafhandelParameter

src/main/kotlin/net/atos/zac/smartdocuments/SmartDocumentsService.kt, src/test/kotlin/net/atos/zac/smartdocuments/SmartDocumentsServiceTest.kt
Use Instance to make declarative ReastEasy client for SmartDocuments optional
Solves PZ-5188
=> fix: SmartDocuments ReastEasy client is now optional

gradle/libs.versions.toml
revert renovate patch kotlin monorepo back to 2.1.0
=> chore(deps): revert renovate patch kotlin monorepo back to 2.1.0

.github/workflows/build-test-deploy.yml
Add CodeCov test analytics in this build
Solves PZ-5193
=> chore(build): add codecov test analytics

renovate.json
Limit publiccode.yaml updates
Solves PZ-5238
=> feat: add schedule to renovate for publiccode.yaml updates

renovate.json
Pin Spotless to version < 7
Solves PZ-5241
=> feature: pin spotless to version 6

src/main/app/src/app/zaken/zaak-koppelen/zaak-koppelen-dialog.component.html, src/main/app/src/app/zaken/zaak-koppelen/zaak-koppelen-dialog.component.less, src/main/app/src/app/zaken/zaak-koppelen/zaak-koppelen-dialog.component.ts, src/main/app/src/app/zaken/zaak-opschorten-dialog/zaak-opschorten-dialog.component.html, src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts
FE- opschorten icons aligned + koppel dialog aligned
Solves PZ-5247
=> chore(app): opschorten icons aligned + koppel dialog aligned

src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts
Opens location side menu again after changes for active side menu item
Solves [PZ-5294](https://dimpact.atlassian.net/browse/PZ-5294)
=> fix(zaak-view.component): set active side action

scripts/docker-compose/imports/openzaak-database/database/4-setup-zac-config-after.sql, src/itest/kotlin/nl/info/zac/itest/CsvRESTServiceTest.kt, src/itest/kotlin/nl/info/zac/itest/ZaakRestServiceExtensionTest.kt, src/itest/kotlin/nl/info/zac/itest/ZaakRestServiceLinkParentChildZaken.kt, src/itest/kotlin/nl/info/zac/itest/ZoekenRESTServiceTest.kt, src/itest/kotlin/nl/info/zac/itest/config/ItestConfiguration.kt
Added integration test to test linking parent to child zaken. Includes configuration of the test zaaktypes in OpenZaak to allow this.
Solves PZ-5339
=> chore: add integration test for linking parent to child zaken

charts/zac/Chart.yaml, charts/zac/templates/deployment.yaml
fixes opa url in zac init container
Solves PZ-5431
=> feat: fix zac initcontainer

Dockerfile, renovate.json
Update eclipse-temurin base image to 21.0.6
Solves PZ-5346
=> feat: update JVM base image to 21.0.6

renovate.json
Modify renovate config and only allow version updates to *-jre-ubi9-minimal
Solves PZ-5366
=> fix: only propose eclipse-temurin updates matching /jre-ubi9-minimal$/

.github/workflows/check-for-conventional-commits.yml, .github/workflows/check-spdx-license-headers.yml, .github/workflows/clean-up-cache-on-pr-close.yml, .github/workflows/codeql.yml, .github/workflows/helm-chart-testing.yml, .github/workflows/remove-stale-branches.yml, .github/workflows/run-e2e.yml, .github/workflows/update-trivy-scanner-cache.yml
Set explicit permissions for the workflows.
See (for instance) https://github.com/infonl/dimpact-zaakafhandelcomponent/security/code-scanning/337
Solves PZ-5370
=> chore(workflows): add permissions

charts/zac/Chart.yaml
Helm version = 1.0.0
App version = 2.0.0
#major
Solves PZ-5176
=> feature: release app 2.0.0, helm 1.0.0

.github/workflows/clean-up-cache-on-pr-close.yml, .github/workflows/update-trivy-scanner-cache.yml
Fix two failing workflows by adding a missing permission to PR cache deletion and oras installation on ubuntu 24.x runners
Solves PZ-5371
=> fix: add missing permission to PR cache delete workflow

src/main/app/src/app/klanten/zoek/personen/persoon-zoek.component.html, src/main/app/src/flex.less
FE - Search form - persons tab - field prefix less wide; plus slightly fiddle other fields and checked and OK with and by Gina
Solves PZ-5351
=> fix(app): Search form - persons tab - field prefix less wide

src/itest/kotlin/nl/info/zac/itest/ZaakRestServiceLinkParentChildZaken.kt, src/itest/kotlin/nl/info/zac/itest/ZoekenRESTServiceTest.kt, src/main/app/src/app/zaken/model/zaak-ontkoppel-gegevens.ts, src/main/app/src/app/zaken/zaak-ontkoppelen/zaak-ontkoppelen-dialog.component.ts, src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts, src/main/app/src/app/zaken/zaken.service.ts, src/main/java/net/atos/client/zgw/zrc/model/HoofdzaakZaakPatch.java, src/main/java/net/atos/client/zgw/zrc/model/RelevantezaakZaakPatch.java, src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt, src/main/kotlin/net/atos/zac/app/zaak/model/RestZaakLinkData.kt, src/main/kotlin/net/atos/zac/app/zaak/model/RestZaakUnlinkData.kt, src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt, src/test/kotlin/net/atos/zac/app/zaak/model/RestZakenFixtures.kt, src/test/kotlin/nl/info/zac/test/date/DateTestUtil.kt
Added integration test to unlink zaken.
Solves PZ-5373
=> chore: add integration test to unlink zaken

src/itest/kotlin/nl/info/zac/itest/ZaakafhandelParametersRestServiceTest.kt, src/itest/kotlin/nl/info/zac/itest/config/ItestConfiguration.kt, src/main/java/net/atos/zac/admin/ZaakafhandelParameterService.java, src/main/java/net/atos/zac/app/admin/converter/RESTZaakbeeindigRedenConverter.java, src/main/java/net/atos/zac/app/admin/model/RESTZaakbeeindigReden.java, src/main/kotlin/net/atos/zac/app/admin/ZaakafhandelParametersRestService.kt, src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt, src/main/kotlin/net/atos/zac/app/zaak/model/RESTZaakAfbrekenGegevens.kt, src/test/kotlin/net/atos/zac/admin/ZaakafhandelParameterBeheerServiceTest.kt, src/test/kotlin/net/atos/zac/admin/model/AdminFixtures.kt, src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt
Add niet ontvankelijk in abort causes
Handle missing zaakbeeindigRedenId as niet ontvankelijk
Solves: PZ-5044
=> fix: enable zaak abort with niet ontvankelijk

.github/workflows/build-test-deploy.yml
only bump ZAC version on main branch
Solves PZ-5408
=> fix: only bump ZAC version on main branch

.github/workflows/build-test-deploy.yml, charts/zac/Chart.yaml
Use floating tags in helm charts
Solves PZ-5423
=> fix: Use correct zac version in helm chart and introduce floating tag

.github/workflows/build-test-deploy.yml
Correct output of next-version job, so it can be used in provision trigger 
Solves PZ-5462
=> fix: setting the tag name for use in provision trigger

src/main/app/src/app/shared/material-form-builder/form-components/autocomplete/autocomplete.component.html, src/main/app/src/app/shared/material-form-builder/form-components/autocomplete/autocomplete.component.spec.ts, src/main/app/src/app/shared/material-form-builder/form-components/autocomplete/autocomplete.component.ts
Make sure to show the correct icon suffix based on the `autocomplete` state
Solves [PZ-5293](https://dimpact.atlassian.net/browse/PZ-5293)
=> fix(autocomplete.component): show correct suffix icon

src/main/app/src/app/shared/material-form-builder/form-components/autocomplete/autocomplete-validators.spec.ts, src/main/app/src/app/shared/material-form-builder/form-components/autocomplete/autocomplete-validators.ts, src/main/app/src/app/shared/material-form-builder/form-components/autocomplete/autocomplete.component.ts, src/main/app/src/app/shared/material-form-builder/model/abstract-choices-form-field.ts
Fix regressie issue for auto-complete fields in forms
Solves [PZ-5467](https://dimpact.atlassian.net/browse/PZ-5467)
=> fix(autocomplete.component): resolve observable to inform formControl

src/main/app/src/app/core/toolbar/toolbar.component.html, src/main/app/src/app/core/toolbar/toolbar.component.less, src/main/app/src/app/core/toolbar/toolbar.component.ts
Adding toolbar menu selected state
Solves [PZ-3674](https://dimpact.atlassian.net/browse/PZ-3674)
=> feat: added active state on toolbar menu

.github/workflows/build-test-deploy.yml, .github/workflows/check-spdx-license-headers.yml, .github/workflows/codeql.yml, .github/workflows/helm-chart-release.yml, .github/workflows/helm-chart-testing.yml
Add GitHub workflow concurrency group
Solves PZ-5481
=> fix: Only allow a single concurrent workflow run per branch

src/main/java/net/atos/zac/signalering/model/SignaleringTarget.java, src/main/java/net/atos/zac/signalering/model/SignaleringType.java, src/main/java/net/atos/zac/signalering/model/SignaleringZoekParameters.java, src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt, src/main/kotlin/net/atos/zac/signalering/SignaleringPredicateHelper.kt, src/main/kotlin/net/atos/zac/signalering/SignaleringService.kt, src/main/kotlin/nl/info/zac/notification/NotificationReceiver.kt, src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt, src/test/kotlin/net/atos/zac/app/zaak/model/RestZakenFixtures.kt, src/test/kotlin/net/atos/zac/signalering/SignaleringServiceTest.kt, src/test/kotlin/net/atos/zac/signalering/model/SignaleringFixtures.kt, src/test/kotlin/nl/info/zac/notification/NotificationReceiverTest.kt
Delete any zaak signaleringen from the ZAC database on receiving a 'zaak destroy' notification.
Solves PZ-5475
=> feat: delete zaak signaleringen on zaak destroy

renovate.json
Corrected manager name helm -> helm-values
Solves PZ-5489
=> fix: Update renovate.json

build.gradle.kts, docs/manuals/installation-guide/installation-guide.md
- De-duplicated targetExclude in spotlessApp task in build.gradle.kts 
- Fixed links in installation-guide.md
Solves PZ-5482
=> chore: boy scouting build.gradle.kts and installation-guide.md

src/itest/kotlin/nl/info/zac/itest/NotificationsZaakDestroyTest.kt, src/itest/kotlin/nl/info/zac/itest/client/ZacClient.kt, src/itest/kotlin/nl/info/zac/itest/config/ProjectConfig.kt, src/main/java/net/atos/zac/signalering/model/SignaleringVerzondenZoekParameters.java, src/main/java/net/atos/zac/signalering/model/SignaleringZoekParameters.java, src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt, src/main/kotlin/net/atos/zac/signalering/SignaleringPredicateHelper.kt, src/main/kotlin/nl/info/zac/notification/NotificationReceiver.kt, src/test/kotlin/nl/info/zac/notification/NotificationReceiverTest.kt
Delete any 'signalering verzonden' records for zaak on zaak destroy notification. #minor
Solves PZ-5486
=> feat: delete any signalering verzonden records for zaak on zaak destroy notification

renovate.json
force node constraints
Solves PZ-5497
=> fix: force node version constraints

renovate.json, src/e2e/package-lock.json, src/main/app/package-lock.json
Use latest v3 format for npm lock files
Solves PZ-5497
=> fix: bump locks files to version 3

src/main/kotlin/nl/info/zac/notification/NotificationReceiver.kt, src/test/kotlin/nl/info/zac/notification/NotificationReceiverTest.kt
Remove related tasks from solr index on zaak destroy.
Solves PZ-5494
=> feat: remove related tasks from solr index on zaak destroy

src/e2e/step-definitions/external-systems.ts
Changes to the PlayWright E2E test that involves the selecting of elements in the FE.
Solves PZ-5472
=> chore(e2e): improve document creation tests

scripts/README.md
Add readme for the scripts directory
Solves PZ-5438
=> feature: add scripts dir readme

src/itest/kotlin/nl/info/zac/itest/config/ItestConfiguration.kt, src/main/kotlin/net/atos/zac/app/klant/model/personen/RestPersoon.kt, src/test/kotlin/net/atos/zac/app/klant/model/personen/RestPersoonTest.kt
Add country name to foreign addresses
Solves PZ-5540
=> fix: add country to foreign addresses

.github/workflows/build-test-deploy.yml, renovate.json
Upgrade Renovate pinned version rule to allow for upgrade to OpenNotificaties 1.8.0.
Solves PZ-5549
=> chore: upgrade Renovate pinned version rule to allow for upgrade to OpenNotificaties 1.8.0

renovate.json
Pin Renovate OpenZaak Docker Compose version to 1.1.8.
Solves PZ-5544
=> chore: pin Renovate OpenZaak Docker Compose version to 1.1.8

docs/development/testing.md
Updated the documentation of the e2e testing with the improvements of selectors
Solves 5593
=> chore(e2e): Improve documention of selectors

src/main/app/src/assets/i18n/en.json, src/main/app/src/assets/i18n/nl.json, src/main/kotlin/net/atos/zac/app/admin/ZaakafhandelParametersRestService.kt, src/main/kotlin/nl/info/zac/exception/ErrorCode.kt, src/test/kotlin/net/atos/zac/app/admin/AppAdminFixtures.kt, src/test/kotlin/net/atos/zac/app/admin/ZaakafhandelParametersRestServiceTest.kt
Make sure the selected `behandelaar` is in the `group`.
Solves PZ-5067
=> feat(ZaakafhandelParameters): validate `behandelaar`

src/main/app/src/app/fout-afhandeling/fout-afhandeling.service.spec.ts, src/main/app/src/app/fout-afhandeling/fout-afhandeling.service.ts, src/main/kotlin/net/atos/zac/app/exception/RestExceptionMapper.kt
Fix the handling of main case to which open subcase(s) are linked no longer gives a clear message.
Solves PZ-5449
=> fix: fix the handling of main case error message

build.gradle.kts, gradle/libs.versions.toml
Upgraded WildFly Galleon to 6.0.5.Final.
Solves PZ-5714
=> chore: upgrade WildFly Galleon to 6.0.5.Final

src/main/app/src/app/zaken/zaak-details-wijzigen/zaak-details-wijzigen.component.ts
FE - Case details change form - fix assignment of group
Solves partly PZ-5688
=> fix(app): case details change form - fix assignment of group

src/main/app/src/assets/i18n/en.json, src/main/app/src/assets/i18n/nl.json, src/main/kotlin/net/atos/zac/app/admin/ZaakafhandelParametersRestService.kt, src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt, src/main/kotlin/net/atos/zac/identity/IdentityService.kt, src/main/kotlin/net/atos/zac/identity/exception/GroupNotFoundException.kt, src/main/kotlin/net/atos/zac/identity/exception/IdentityRuntimeException.kt, src/main/kotlin/net/atos/zac/identity/exception/UserNotFoundException.kt, src/main/kotlin/net/atos/zac/identity/exception/UserNotInGroupException.kt, src/main/kotlin/nl/info/zac/exception/ErrorCode.kt, src/test/kotlin/net/atos/zac/app/admin/ZaakafhandelParametersRestServiceTest.kt, src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt, src/test/kotlin/net/atos/zac/identity/IdentityServiceTest.kt, src/test/kotlin/nl/info/test/org/keycloak/representations/idm/KeycloakRepresentationsIdmFixtures.kt
Add user/group check to the identity service
Solves: PZ-5717
=> feature: check if user belongs to a group when patching zaak

build.gradle.kts, gradle/libs.versions.toml, pom.xml
Uprade to WildFly 35.0.1
Solves PZ-5711
=> chore: upgrade to WildFly 35.0.1

src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt, src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt
Check if user belongs to a group for toekennen endpoint
Solves PZ-5775
=> feature: add check for user in group for toekennen endpoint

src/e2e/step-definitions/external-systems.ts, src/e2e/step-definitions/hooks.ts, src/e2e/step-definitions/open-forms.ts, src/e2e/step-definitions/zaak.ts, src/e2e/utils/TestStorage.service.ts
Fixes to solve majority of causes for flaky tests
Solves PZ-5769
=> Fix(e2e): fix flaky tests

docker-compose.yaml, src/main/resources/policies/document-rechten.rego, src/main/resources/policies/overige-rechten.rego, src/main/resources/policies/taak-rechten.rego, src/main/resources/policies/werklijst-rechten.rego, src/main/resources/policies/zaak-rechten.rego
Updated the OPA client to 1.2.0 and updated the rego files (policies)
Solves: PZ-5108
=> feat(opa): PZ-5108 update docker compose setup to OPA 1.2.0 and update rego (rules) files

src/main/app/src/app/dashboard/dashboard-card/dashboard-card.component.ts, src/main/app/src/app/dashboard/taak-zoeken-card/taak-zoeken-card.component.ts, src/main/app/src/app/dashboard/zaak-zoeken-card/zaak-zoeken-card.component.ts, src/main/app/src/app/dashboard/zaken-card/zaken-card.component.ts, src/main/app/src/app/documenten/inbox-documenten-list/inbox-documenten-list.component.ts, src/main/app/src/app/formulieren/formulier/formulier.component.ts, src/main/app/src/app/formulieren/formulier/velden/documenten/documenten-formulier-veld.component.ts, src/main/app/src/app/formulieren/taken/abstract-taak-formulier.ts, src/main/app/src/app/formulieren/taken/model/aanvullende-informatie.ts, src/main/app/src/app/formulieren/zaken/abstract-zaak-formulier.ts, src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.ts, src/main/app/src/app/informatie-objecten/informatie-object.resolver.ts
Fixes some typescript linting issues
Solves [PZ-5778](https://dimpact.atlassian.net/browse/PZ-5778)
=> fix: typescript issues

src/main/app/src/app/formulieren/process/process-formulieren-builder.ts, src/main/app/src/app/formulieren/process/process-formulieren.service.ts, src/main/app/src/app/fout-afhandeling/fout-afhandeling.service.spec.ts, src/main/app/src/app/informatie-objecten/route-reuse-strategy.service.ts, src/main/app/src/app/klanten/bedrijf-view/bedrijf-resolver.service.ts, src/main/app/src/app/klanten/persoon-view/persoon-resolver.service.ts, src/main/app/src/app/klanten/zoek/klanten/klant-zoek.component.ts, src/main/app/src/app/klanten/zoek/personen/persoon-zoek.component.ts, src/main/app/src/app/mail/mail-create/mail-create.component.ts, src/main/app/src/app/mail/ontvangstbevestiging/ontvangstbevestiging.component.ts, src/main/app/src/app/plan-items/process-task-do/process-task-do.component.ts
fixes some typescript linting issues
Solves PZ-5778
=> chore: typescript issues

.github/workflows/remove-stale-branches.yml
Modify slack notification to include a link to GitHub branch page
Solves PZ-5838
=> feat: Add link to github branch overview to the stale branch notifications

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.html, src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.less
Changes to the document detail page to solve the beschrijving bug and follows figma design
Will be upodated in the future with the use of grids to make the page more clean 
Solves PZ-2964
=> fix(document): lange beschrijving-aanpassen

src/main/kotlin/net/atos/zac/productaanvraag/ProductaanvraagService.kt, src/test/kotlin/net/atos/zac/productaanvraag/ProductaanvraagServiceTest.kt
Do not use generiek name
Solves PZ-5852
=> fix: use correct name for initiator when using roltypeOmschrijving

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.html
Removed ! from detail page
Solves PZ-5854
=> fix: Removed exclamation points

.github/workflows/build-test-deploy.yml, .github/workflows/codeql.yml
Fix broken build.
Solves PZ-5862
=> chore: fix broken build

src/main/app/src/app/formulieren/taken/abstract-taak-formulier.ts
FE - Fix for replyEmail prop having 'undefined' string value - breaking submission of aanvullende informatie form
Solves PZ-5860
=> fix(app): fix/PZ 5860  FE  empty reply breaking submission of aanvullende informatie form

build.gradle.kts, src/main/java/net/atos/zac/productaanvraag/util/BetalingStatusEnumJsonAdapter.java, src/main/java/net/atos/zac/productaanvraag/util/GeometryTypeEnumJsonAdapter.java, src/main/java/net/atos/zac/productaanvraag/util/IndicatieMachtigingEnumJsonAdapter.java, src/main/java/net/atos/zac/productaanvraag/util/RolOmschrijvingGeneriekEnumJsonAdapter.java, src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt, src/main/kotlin/net/atos/zac/documentcreation/converter/DocumentCreationDataConverter.kt, src/main/kotlin/nl/info/zac/notification/NotificationReceiver.kt, src/main/kotlin/nl/info/zac/productaanvraag/ProductaanvraagService.kt, src/main/kotlin/nl/info/zac/productaanvraag/util/AanvraagToZgwConverter.kt, src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt, src/test/kotlin/net/atos/zac/documentcreation/converter/DocumentCreationDataConverterTest.kt, src/test/kotlin/nl/info/zac/notification/NotificationReceiverTest.kt, src/test/kotlin/nl/info/zac/productaanvraag/AanvraagFixtures.kt, src/test/kotlin/nl/info/zac/productaanvraag/ProductaanvraagServiceTest.kt
Move productaanvraag generated Java code and Kotlin backend code to nl info package. Cleaned up code a bit.
Solves PZ-5809
=> chore: move productaanvraag code to nl info package

README.md, docs/manuals/installation-guide/installation-guide.md
Link sysadmin and developer installation manuals.
Solves PZ-5888
=> chore: link sysadmin and developer installation manuals

pom.xml
Replace net.atos.common-ground by nl.info.common-ground in pom.xml.
Solves PZ-5937
=> chore: replace net.atos.common-ground by nl.info.common-ground in pom.xml

build.gradle.kts
Made npmRunLint Gradle task cacheable.
Solves PZ-5939
=> chore: make npmRunLint Gradle task cacheable

src/main/kotlin/nl/info/zac/configuratie/ConfiguratieService.kt, src/test/kotlin/nl/info/zac/configuratie/ConfiguratieServiceTest.kt
ADDITIONAL_ALLOWED_FILE_TYPES with no value causes ZAC to fail to start now
Solves PZ-5951
=> fix: make ADDITIONAL_ALLOWED_FILE_TYPES optional

src/main/kotlin/nl/info/zac/notification/Channel.kt, src/main/kotlin/nl/info/zac/notification/NotificationReceiver.kt, src/main/kotlin/nl/info/zac/notification/Resource.kt, src/test/kotlin/nl/info/zac/notification/NotificationReceiverTest.kt
Enable handling test callback url notification as no-op
Solves PZ-5952
=> feature: handle test callback url notification

charts/zac/Chart.yaml, charts/zac/README.md, charts/zac/templates/configmap-nginx.yaml
client_max_body_size in @ location segments is allowed but never used, it needs to be set on the location where the request is first processed.
Solves Groningen file upload issue
=> feat: move client_max_body_size to incoming location

src/main/kotlin/nl/info/zac/productaanvraag/ProductaanvraagService.kt, src/test/kotlin/nl/info/zac/productaanvraag/ProductaanvraagServiceTest.kt
Removed BPMN spike support in productaanvraag flow. proper BPMN support in productaanvraag flow will be added later.
Solves PZ-5961
=> chore: remove BPMN spike support in productaanvraag flow

src/main/app/src/app/informatie-objecten/informatie-object-edit/informatie-object-edit.component.ts
Added maxlength to new version document
Solves PZ-5930
=> Fix: added maxlength and fixed some typescript errors

.github/workflows/helm-chart-testing.yml
Fix an introduced indenting failure in helm-chart-testing workflow
Solves PZ-6006
=> fix: indenting in helm-chart-testing workflow

.github/workflows/validate-json-yaml-files.yaml, src/main/app/tsconfig.app.json, src/main/app/tsconfig.spec.json, src/main/resources/api-specs/bag/bag-openapi.yaml
Validate yam en json files in the repo. Should be required check after this is pushed
Solves PZ-6007
=> feat: add github workflow to validate json and yaml files

docker-compose.yaml
Update open-archiefbeheer to latest version
Solves PZ-5735
=> feat: update open-archiefbeheer in docker-compose to 1.0.0-rc0

src/main/java/net/atos/zac/app/gebruikersvoorkeuren/GebruikersvoorkeurenRESTService.java, src/main/java/net/atos/zac/app/gebruikersvoorkeuren/converter/RESTDashboardCardInstellingConverter.java, src/main/java/net/atos/zac/app/gebruikersvoorkeuren/converter/RESTZoekopdrachtConverter.java, src/main/java/net/atos/zac/app/inboxdocumenten/converter/RESTInboxDocumentConverter.java, src/main/java/net/atos/zac/app/ontkoppeldedocumenten/OntkoppeldeDocumentenRESTService.java, src/main/java/net/atos/zac/app/productaanvragen/InboxProductaanvragenRESTService.java, src/main/java/net/atos/zac/app/productaanvragen/converter/RESTInboxProductaanvraagConverter.java
Made more converters static for better testability.
Solves PZ-6012
=> chore: made more converters static for better testability

src/main/app/src/app/informatie-objecten/informatie-object-link/informatie-object-link.component.ts
FE - Doc link move Sidebar form  - Icoon fix
Solves PZ-6093
=> feat(app):  Doc link move Sidebar form  - Icoon fix

src/main/app/src/app/informatie-objecten/informatie-object-link/informatie-object-link.component.html, src/main/app/src/app/informatie-objecten/informatie-object-link/informatie-object-link.component.less, src/main/app/src/app/taken/taak-view/taak-view.component.html, src/main/app/src/app/taken/taak-view/taak-view.component.ts, src/main/app/src/app/zaken/zaak-view/zaak-view.component.html, src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts
FE - Task detail page - Add document link form
- form added
- refresh case history
- UX feedback: added a divider
Solves PZ-6146
=> feat(app): task detail page - add document link form

docs/solution-architecture/systemContext.md
Create a next minor release version.
Updated System Context diagram and table.
Solves PZ-6148
#minor
=> chore: next minor release

docs/solution-architecture/systemContext.md
Fixed incorrect links in system context diagram.
Solves PZ-6154
=> chore: fixed incorrect links in system context diagram

charts/zac/Chart.yaml, charts/zac/README.md, charts/zac/templates/deployment.yaml, charts/zac/values.yaml
feat: allow disabling initContainer and settings of initContainer image
Solves deployments to dimpact acceptance environments
=> feat: allow disabling initContainer and settings of initContainer image

scripts/docker-compose/imports/smartdocuments-wiremock/mappings/wsxmldeposit-wizard.json, src/main/kotlin/nl/info/zac/documentcreation/DocumentCreationService.kt, src/test/kotlin/nl/info/zac/documentcreation/DocumentCreationServiceTest.kt
Change SmartDocuments document creation output format to 'docx'.
Solves PZ-6073
=> fix: change SmartDocuments document creation output format to 'docx'

src/main/app/src/app/informatie-objecten/informatie-object-link/informatie-object-link.component.html, src/main/app/src/app/informatie-objecten/informatie-object-link/informatie-object-link.component.ts
FE: Document move form - alternate icon
Solves PZ-6160
=> fix(app): Document move form - alternate icon

src/test/kotlin/nl/info/zac/documentcreation/DocumentCreationServiceTest.kt, src/test/kotlin/nl/info/zac/healthcheck/model/ZaaktypeInrichtingscheckTest.kt, src/test/kotlin/nl/info/zac/signalering/SignaleringServiceTest.kt
Removed unnecessary static mocks in unit tests.
Solves PZ-6163
=> chore: removed unnecessary static mocks in unit tests

.env.example, charts/zac/Chart.yaml, charts/zac/README.md, charts/zac/values.yaml
Improved technical documentation about SMARTDOCUMENTS_FIXED_USER_NAME environment variable.
Solves PZ-6196
=> chore: improved technical documentation about SMARTDOCUMENTS_FIXED_USER_NAME environment variable

docker-compose.yaml
open-archiefbeheer 1.0.0 in docker-compose
Solves PZ-6100
=> feat: update to open-archiefbeheer 1.0.0 final version

src/main/app/src/app/formulieren/formio-wrapper/formio-wrapper.component.spec.ts, src/main/app/src/app/formulieren/formio-wrapper/formio-wrapper.component.ts, src/main/app/src/app/taken/taak-view/taak-view.component.ts
On group change an event with undefined for data is recieved
Solves PZ-6083
=> fix: filter out form.io change events

src/main/app/src/app/informatie-objecten/informatie-objecten.service.ts
FE - document add - missing fields added to form data creation object
Solves PZ-6086
=> fix(app): document add - missing fields added to form data creation object

docs/solution-architecture/accessControlPolicies.md
Update rights documentation
Solves PZ-6247
=> feat: update rights documentation

docs/development/testing.md, docs/solution-architecture/accessControlPolicies.md, src/main/app/src/app/zaken/zaak-details-wijzigen/zaak-details-wijzigen.component.ts, src/main/resources/policies/zaak-rechten.rego, src/test/resources/policies/zaak-rechten_test.rego
FE - role policies - case assignment adjustments
config changes:
1. Behandelaar - Toekennen alleen bij ‘Open’ zaak toestaan
2. Coordinator - Toekennen alleen bij ‘Open’ zaak toestaan
3. Record Manager - Toekennen als Zaak is ‘Afgehandeld’
4. Functioneel Beheerder - Toekennen als Zaak is ‘Afgehandeld’
Solves PZ-5867
=> fix(app): role policies - case assignment adjustments

src/main/app/src/app/informatie-objecten/informatie-object-add/informatie-object-add.component.less, src/main/app/src/app/zaken/zaak-view/zaak-view.component.less, src/main/app/src/assets/i18n/nl.json
FE - rename Voorvoegsel to Tussenvoegsel
Solves PZ-6192
=> fix(app): rename Voorvoegsel to Tussenvoegsel

src/main/kotlin/nl/info/client/zgw/ztc/ZtcClientService.kt, src/main/kotlin/nl/info/zac/app/util/UtilRestService.kt, src/test/kotlin/nl/info/client/zgw/ztc/ZtcClientServiceTest.kt, src/test/kotlin/nl/info/zac/app/util/UtilRestServiceTest.kt
Improved UtilRestService.kt by making caching and memory statistics more human-readable.
Solves PZ-6274
=> chore: improve UtilRestService.kt by making caching and memory statistics more human-readable

src/main/kotlin/nl/info/client/zgw/ztc/ZtcClientService.kt, src/main/kotlin/nl/info/zac/app/util/UtilRestService.kt
Increase maximum cache size in ZtcClientService.kt to increase performance.
Solves PZ-6275
=> feat: increase maximum cache size in ZtcClientService.kt to increase performance

build.gradle.kts, gradle/libs.versions.toml, src/main/java/net/atos/client/zgw/shared/cache/Caching.java, src/main/java/net/atos/zac/admin/ZaakafhandelParameterService.java, src/main/kotlin/nl/info/client/zgw/ztc/ZtcClientService.kt, src/main/kotlin/nl/info/zac/app/util/UtilRestService.kt, src/test/kotlin/nl/info/zac/app/util/UtilRestServiceTest.kt
Improved showing ZAC memory statistics in human-readable way.
Solves PZ-6276
=> chore: improved showing ZAC memory statistics in human-readable way

src/main/app/src/app/zaken/zaak-view/zaak-view.component.less
FE- edit button - prevent overlapping zaak detail field
Solves PZ-6311
=> fix(app): edit button - prevent overlapping zaak detail field

docker-compose.yaml, renovate.json, scripts/docker-compose/imports/objects-api/fixtures/demodata.json, src/main/resources/api-specs/or/objects-openapi.yaml
Upgrade to objecten v3 in local and integration test Docker Compose setup.
Solves PZ-6133
=> chore: upgrade to objecten v3 in docker compose

.github/workflows/helm-chart-release.yml
Add manual execution of Helm Chart release action.
=> chore(action): manual helm chart release

src/test/kotlin/net/atos/zac/flowable/ZaakVariabelenServiceTest.kt
Backfill unit tests
Solves PZ-6122
=> feature: add unit test for ZaakVariabelenService

src/itest/kotlin/nl/info/zac/itest/NotificationsTest.kt, src/itest/kotlin/nl/info/zac/itest/ReferenceTableRestServiceTest.kt, src/itest/kotlin/nl/info/zac/itest/ZaakafhandelParametersRestServiceTest.kt, src/itest/kotlin/nl/info/zac/itest/client/ZacClient.kt, src/itest/kotlin/nl/info/zac/itest/config/ItestConfiguration.kt, src/itest/kotlin/nl/info/zac/itest/config/ProjectConfig.kt
Added a domein to one of the zaakafhandelparameters in the integration tests so we can test domein-specific authorisation in future integration tests.
Solves PZ-6372
=> chore: add domein to zaakafhandelparameters in integration test

.junie/guidelines.md
Added basic Junie IntelliJ AI configuration file. See e.g. https://www.youtube.com/watch?v=oyKgaysS9_g
Solves PZ-6371
=> core: add Junie IntelliJ AI configuration file

charts/zac/Chart.yaml, charts/zac/README.md, charts/zac/templates/config.yaml, src/main/kotlin/nl/info/client/brp/exception/BrpPersonNotFoundException.kt
Added missing quote in Helm Chart.
Solves PZ-6441
=> fix: added missing quote in Helm Chart

charts/zac/Chart.yaml, charts/zac/README.md, charts/zac/values.yaml, renovate.json
Added tag for opentelemetry collector contrib image and pin version until https://github.com/open-telemetry/community/issues/2641 is solved.
Solves PZ-6458
=> chore: add tag for opentelemetry collector contrib image

charts/zac/Chart.yaml, charts/zac/README.md, charts/zac/templates/config.yaml, charts/zac/values.yaml
Simplify ZAC OTEL config in Helm Chart.
Solves PZ-6482
=> chore: simplify ZAC OTEL config in Helm Chart

charts/zac/Chart.yaml, charts/zac/README.md, charts/zac/templates/config.yaml
Fix setting OTEL_SDK_ENABLED var in Helm Chart.
Solves PZ-6486
=> fix: fix setting OTEL_SDK_ENABLED var in Helm Chart

.github/workflows/build-test-deploy.yml, .github/workflows/codeql.yml
Fixed skipping GitHub build on Helm Chart changes.
Solves PZ-6488
=> fix: fix skipping GitHub build on Helm Chart changes

src/main/kotlin/nl/info/zac/app/klant/KlantRestService.kt
Deal with possible NULL values in the klantcontactlist when converting.
Solves PZ-6490
=> fix: handle nulls on processing klantcontactlist

docs/development/testing.md
Added link to OPA testing doc
Solves PZ-6496
=> chore: update testing.md

src/e2e/step-definitions/zaak.ts
Fixed creating a case in the E2E tests
Solves PZ-6515
=> fix(E2E): create zaak

src/main/app/src/app/admin/parameter-edit/smart-documents-form/smart-documents-form-item/smart-documents-form-item.component.ts, src/main/app/src/app/core/websocket/websocket.service.ts, src/main/app/src/app/dashboard/dashboard-card/dashboard-card.component.ts, src/main/app/src/app/documenten/model/inbox-document-list-parameters.ts, src/main/app/src/app/documenten/model/ontkoppeld-document-list-parameters.ts, src/main/app/src/app/fout-afhandeling/fout-afhandeling.service.ts, src/main/app/src/app/gebruikersvoorkeuren/zoekopdracht/zoekfilters.model.ts, src/main/app/src/app/gebruikersvoorkeuren/zoekopdracht/zoekopdracht.component.ts, src/main/app/src/app/productaanvragen/model/inbox-productaanvraag-list-parameters.ts, src/main/app/src/app/zoeken/model/zoek-parameters.ts
This pull request introduces several updates to improve type safety, refactor code for better maintainability, and centralize shared models. The most significant changes include stricter type definitions across components and services, the extraction of `ZoekFilters` into a shared model, and adjustments to existing methods to align with the new type definitions.
* Updated `SmartDocumentsFormItemComponent` to use stricter type annotations for `@Input` properties and default initialization for optional variables (`src/main/app/src/app/admin/parameter-edit/smart-documents-form/smart-documents-form-item/smart-documents-form-item.component.ts`) [[1]](diffhunk://#diff-b748f3ac0738574d28c5bbe8cda28980fff6e1708d5ef150e8bac2c693b283a3L11-R29) …
=> chore: Refactors types and adds null safety checks

renovate.json
This PR will create the next ZAC major release.
Renovate dependency version checks have been updated to follow PodiumD. 
#major
Solves PZ-6577
=> feature(release): next ZAC major release and PodiumD version dependencies

.gitattributes
This PR will create the next ZAC minor release: 3.5.0
#minor
Solves PZ-6577
=> feat(release): next PodiumD minor release

src/main/app/src/app/informatie-objecten/informatie-object-add/informatie-object-add.component.spec.ts, src/main/app/src/app/informatie-objecten/informatie-object-add/informatie-object-add.component.ts
Fixes that there can be more than 100 chars inside the title when creating a document. The document title will be capped to 100 chars according to the file name
Solves PZ-6411
=> Fix: Te lange document naam

scripts/solr/reindex-zac-solr-data.sh
Fixed Solr indexing script for ZAC internal endpoints API key option.
Solves PZ-5698
=> fix: fixed Solr indexing script for ZAC internal endpoints API key option

src/main/app/src/app/informatie-objecten/informatie-object-verzenden/informatie-object-verzenden.component.html
FE - Fix for incorrect sidebar icon. Aligned with the menu action button.
Solves PZ-6607
=> chore(app): Fix for incorrect sidebar icon

src/main/webapp/WEB-INF/web.xml
Improved security in our web.xml file by explicitly denying access to unsupported HTTP methods and by changing the order of the security constraints from more specific to less specific as per best practise.
Solves PZ-6599
=> chore: improved security in our web.xml 

src/main/kotlin/nl/info/client/zgw/ztc/ZtcClientService.kt, src/main/kotlin/nl/info/client/zgw/ztc/model/CatalogusListParameters.kt, src/test/kotlin/nl/info/client/zgw/ztc/ZtcClientServiceTest.kt, src/test/kotlin/nl/info/client/zgw/ztc/model/ZtcFixtures.kt
Remove unused cache from ZtcClientService.kt. Added some unit tests just to improve test coverage.
Solves PZ-6632
=> chore: remove unused cache from ZtcClientService.kt

src/main/kotlin/nl/info/zac/app/admin/HealthCheckRestService.kt, src/main/kotlin/nl/info/zac/healthcheck/HealthCheckService.kt, src/main/kotlin/nl/info/zac/healthcheck/model/BuildInformation.kt, src/test/kotlin/nl/info/zac/app/admin/HealthCheckRestServiceTest.kt, src/test/kotlin/nl/info/zac/healthcheck/HealthcheckFixtures.kt
Added authorisation checks for healthcheck service.
Solves PZ-6406
=> feat: add authorisation checks for healthcheck service

src/main/kotlin/nl/info/zac/app/util/UtilRestService.kt, src/test/kotlin/nl/info/zac/app/util/UtilRestServiceTest.kt
Ddded authorisation check on util endpoints.
Solves PZ-6651
=> feat: add authorisation check on util endpoints

src/main/kotlin/nl/info/zac/app/signalering/SignaleringRestService.kt, src/test/kotlin/nl/info/zac/app/signalering/SignaleringRestServiceTest.kt, src/test/kotlin/nl/info/zac/signalering/model/SignaleringFixtures.kt
Added authorisation checks on 'beheren' permission for listing and updating group signalering instellingen.
Solves PZ-6652
=> feat: add authorisation for group signalering instellingen

src/main/kotlin/nl/info/zac/app/util/UtilRestService.kt, src/main/webapp/WEB-INF/web.xml
Secure util cache admin page with 403 error page for non-beheerders.
Solves PZ-6678
=> feat: secure util cache admin page with 403 error page for non-beheerders

docker-compose.yaml
Docker - BRP mock - update to version to 2.6..0
Solves PZ-6678
=> chore: Docker - BRP mock - update to version to 2.6..0

docker-compose.yaml
Docker - Redis - revert to previous version - v7.4.3
Solves PZ-6657
=> chore(docker): Redis - revert to previous version - v7.4.3

src/main/kotlin/nl/info/zac/app/zaak/ZaakKoppelenRestService.kt, src/test/kotlin/nl/info/zac/app/zaak/ZaakKoppelenRestServiceTest.kt
Check for all source and target zaak link combinations
Solves PZ-6682
=> fix: check for all source and target link cases

docs/manuals/inrichting-zaakafhandelcomponent/inrichting-zaakafhandelcomponent.md
Small update of the handleiding to add domeinen. Makes it more clear where to ad the role
Solves PZ-6664
=> feat(doc): update inrichting zaakafhandelcomponent

src/main/app/src/app/fout-afhandeling/dialog/actie-onmogelijk-dialog.component.html, src/main/app/src/app/fout-afhandeling/dialog/fout-detailed-dialog.component.html, src/main/app/src/app/fout-afhandeling/dialog/fout-dialog.component.html, src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.ts, src/main/app/src/app/shared/confirm-dialog/confirm-dialog.component.html, src/main/app/src/app/shared/dialog/dialog-data.ts, src/main/app/src/app/shared/dialog/dialog.component.html, src/main/app/src/app/shared/dialog/dialog.component.ts, src/main/app/src/app/zaken/besluit-view/besluit-view.component.ts, src/main/app/src/app/zaken/intake-afronden-dialog/intake-afronden-dialog.component.html, src/main/app/src/app/zaken/zaak-afhandelen-dialog/zaak-afhandelen-dialog.component.html, src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.ts, src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts, src/main/app/src/styles.less, src/main/app/src/variables.less
This pull request introduces several updates across multiple components to improve the dialog UI and refactor the `DialogData` class for better flexibility and maintainability. The changes include replacing `<div mat-dialog-title>` with `<mat-toolbar>` for improved styling, adding icons and dividers to dialog headers, and refactoring the `DialogData` class to use an `options` object for configuration.
* Replaced `<div mat-dialog-title>` with `<mat-toolbar>` in multiple dialog components for consistent styling, added icons where applicable, and included `<mat-divider>` for visual separation. [[1]](diffhunk://#diff-9f3dca931b507e330454d32af8efd6c05630069e966af098400ae2f5d755df56L6-R15) [[2]](diffhunk://#diff-a04ce314a8a10eb0af286b50ab7751f426ece1bce5a94109429bf7e555858781L6-R15) …
=> chore: fixes dialog icons

src/main/app/src/app/identity/identity.service.ts, src/main/app/src/app/taken/taak-view/taak-view.component.ts
Return promise
Solves: PZ-6694
=> fix: BPMN group listing

src/main/app/src/app/admin/parameter-edit/parameter-edit.component.html, src/main/app/src/assets/i18n/en.json, src/main/app/src/assets/i18n/nl.json
Changed the heading text in the ZAP's for koppelen of documents to look more like the approved design
Solves PZ-6691
=> fix: changed smartdocuments koppelingen text

docker-compose.yaml, renovate.json
Upgraded Docker Compose environment to Open Zaak 1.21.0.
Solves PZ-6669
=> chore: upgrade to Open Zaak 1.21.0

src/main/app/src/assets/i18n/en.json, src/main/app/src/assets/i18n/nl.json
A small PR which is a continuation of PZ-5829. This PR removes the unused translations from the files to keep them clean
Solves PZ-6815
=> Chore: Deleted unused bagobject translations

src/main/app/src/app/informatie-objecten/informatie-object-view/informatie-object-view.component.less, src/main/app/src/app/klanten/koppel/klanten/klant-koppel.component.ts, src/main/app/src/app/zaken/zaak-create/zaak-create.component.html, src/main/app/src/app/zaken/zaak-view/zaak-view.component.html, src/main/app/src/app/zaken/zaak-view/zaak-view.component.less, src/main/app/src/styles.less
FE - Zaak create - Initiator drawer width aligned to 900px
Solves PZ-6825
=> fix(app): Zaak create - Initiator drawer width aligned to 900px

docs/development/testing.md, src/main/resources/policies/notities-rechten.rego, src/main/resources/policies/policies, src/test/resources/policies/document-rechten_test.rego, src/test/resources/policies/notitie-rechten_test.rego, src/test/resources/policies/taak-rechten_test.rego, src/test/resources/policies/werklijst-rechten_test.rego, src/test/resources/policies/zaak-rechten_test.rego
Added OPA policies for notities. Not actually using them yet.
Solves PZ-6774
=> feat: add OPA policies for notities

src/main/app/src/app/admin/parameter-edit/smart-documents-form/smart-documents-form.component.ts, src/main/app/src/app/admin/parameters/parameters.component.spec.ts, src/main/app/src/app/admin/parameters/parameters.component.ts, src/main/app/src/app/admin/process-definitions/process-definitions.component.ts, src/main/app/src/app/admin/referentie-tabel/referentie-tabel.component.ts, src/main/app/src/app/core/ensure-module-loaded-once.guard.ts, src/main/app/src/app/core/service/util.service.spec.ts, src/main/app/src/app/core/service/util.service.ts, src/main/app/src/app/gebruikersvoorkeuren/zoekopdracht-save-dialog/zoekopdracht-save-dialog.component.ts, src/main/app/src/app/shared/dynamic-table/pipes/sort.pipe.ts
This pull request focuses on improving type safety, enhancing code clarity, and updating copyright information across multiple files. The most significant changes include refining type definitions, adding stricter type checks, and updating method implementations to align with modern TypeScript practices.
* Updated the `_transformer` method in `smart-documents-form.component.ts` to use stricter types (`Record<string, unknown>`), replaced direct property access with safe type assertions, and improved the `expandable` logic for better readability and correctness.
* Refactored methods in `util.service.ts` to use more precise types, including `getEnumAsSelectList`, `getUniqueItemsList`, and `getEnumKeyByValue`, ensuring better type inference and reducing reliance on `any`. …
=> chore: remove `any`s from codebase

docker-compose.yaml
Add missing variable to oab 
Solves PZ-6898
=> feat: added FRONTEND_URL to open-archiefbeheer in docker-compose

.github/config/json-yaml-validate-exclude.txt, .github/workflows/validate-json-yaml-files.yaml, src/main/resources/api-specs/zgw/zrc-openapi.yaml, src/main/resources/api-specs/zgw/ztc-openapi.yaml
Upgrade ZTC and ZRC ZGW OpenAPI specs as part of the OpenZaak 1.21.0 upgrade. DTC and BRC APIs to follow.
Solves PZ-6932
=> feat: upgrade ztc and zrc openapi specs

src/main/kotlin/nl/info/zac/app/task/TaskRestService.kt, src/main/kotlin/nl/info/zac/enkelvoudiginformatieobject/util/EnkelvoudigInformatieObjectCheckers.kt, src/main/resources/api-specs/zgw/drc-openapi.yaml
Upgraded DRC OpenAPI specs as part of OpenZaak 1.21.
Solves PZ-6938
=> chore: upgrade DRC OpenAPI specs as part of OpenZaak 1.21

src/main/resources/api-specs/zgw/brc-openapi.yaml
Upgraded BRC OpenAPI specs as part of OpenZaak 1.21.
Solves PZ-6939
=> chore: upgrade BRC OpenAPI specs as part of OpenZaak 1.21

.github/workflows/build-test-deploy.yml
Allows disabling the automatic provisioning trigger via GitHub vars. 
Solves PZ-6944
=> feat: add github vars flag to disable automatic deployment

docs/development/testing.md
Added developer docs about debugging integration tests.
Solves PZ-6946
=> doc: add developer docs about debugging integration tests

src/e2e/step-definitions/open-forms.ts, src/e2e/step-definitions/taken-verdelen.ts, src/e2e/step-definitions/zaak.ts, src/e2e/step-definitions/zaken-verdelen.ts
Fixed the E2E tests which all succeed in this PR. Removed `getByTitle` from code and replaced them with better selectors according to https://testing-library.com/docs/queries/about/#priority
Solves PZ-6691
=> fix: Cleaned up tests and removed getByTitle's

.github/workflows/build-test-deploy.yml, .github/workflows/codeql.yml
Fixed paths-filter configuration to make sure build is not done when only certain files have been changed.
Solves PZ-6952
=> fix: fix paths-filter configuration to make sure build is not done when only certain files have been changed

.github/workflows/helm-chart-release.yml, .github/workflows/helm-chart-testing.yml, charts/zac/Chart.yaml, charts/zac/README.md, charts/zac/README.md.gotmpl, charts/zac/ci/helm-testing-values.yaml, charts/zac/values.yaml, renovate.json
Remove Bitnami subchart from zac
Solves PZ-6969
=> feat: remove unused bitnami solr subchart

src/main/app/src/app/core/toolbar/toolbar.component.html
FE - prevent undefined console errors
Solves PZ-6995
=> fix(app): prevent undefined console errors

src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.ts
Fixes small translation bug that was introduced in https://github.com/infonl/dimpact-zaakafhandelcomponent/pull/3503/files#diff-e5fa18fbbabc6d05049b9bbd6d27c0dc10cbc35c4c120778c9a7d2c5b53b61b0L287
Solves PZ-6750
=> fix(taken-werkvoorraad): select correct translation

scripts/docker-compose/imports/smartdocuments-wiremock/mappings/wsxmldeposit-wizard.json, src/itest/kotlin/nl/info/zac/itest/config/ItestConfiguration.kt, src/itest/resources/bpmn/itProcessDefinition.bpmn, src/itest/resources/bpmn/testForm.json, src/main/app/src/app/taken/taak-view/formio/formio-setup-service.ts, src/main/app/src/app/taken/taak-view/taak-view.component.spec.ts, src/main/app/src/app/taken/taak-view/taak-view.component.ts
When document is created, reload just the history
Solves: PZ-7124
=> fix: do not reload task on document creation

build.gradle.kts
Simplify openapi generator config a little.
Solves PZ-7199
=> chore: simplify openapi generator config

charts/zac/Chart.yaml, charts/zac/README.md, charts/zac/templates/config.yaml, charts/zac/values.yaml
SmartDocuments new env var added
Solves PZ-7038
=> feat(helm): SmartDocuments new env var added

docs/manuals/bpmn-guide/README.md, src/itest/resources/bpmn/testForm.json, src/main/app/src/app/taken/taak-view/formio/formio-setup-service.ts
Use 'choicesjs' widget for Available Documents component   
Solves PZ-7245: multiple selection problem of the component, only one (latest) document is selected in the previous version
=> fix: use choicesjs widget

src/main/app/src/app/admin/inrichtingscheck/inrichtingscheck.component.html, src/main/app/src/app/admin/mailtemplate/mailtemplate.component.html, src/main/app/src/app/core/toolbar/toolbar.component.html, src/main/app/src/app/informatie-objecten/informatie-object-link/informatie-object-link.component.html, src/main/app/src/app/klanten/zoek/bedrijven/bedrijf-zoek.component.html, src/main/app/src/app/klanten/zoek/personen/persoon-zoek.component.html
A simple pull request to add a frame to 2 delete buttons
Solves PZ-6765
=> chore: added frame to delete buttons

Dockerfile
Bump version to 3.9.0
Solves PZ-7390
=> chore: No change update for bump #minor

src/e2e/features/7-taken-verdelen-vrijgeven.feature, src/e2e/step-definitions/taken-verdelen.ts, src/main/app/src/app/shared/notification-dialog/notification-dialog.component.html, src/main/app/src/app/taken/taken-verdelen-dialog/taken-verdelen-dialog.component.html, src/main/app/src/app/taken/taken-vrijgeven-dialog/taken-vrijgeven-dialog.component.html, src/main/app/src/app/zaken/zaak-ontkoppelen/zaak-ontkoppelen-dialog.component.html, src/main/app/src/app/zaken/zaken-verdelen-dialog/zaken-verdelen-dialog.component.html, src/main/app/src/app/zaken/zaken-vrijgeven-dialog/zaken-vrijgeven-dialog.component.html
FE - Align buttons with the Figma design (pattern)
Solves PZ-7526
=> feat(app): Align buttons with the Figma design (pattern)

scripts/docker-compose/imports/openzaak-database/database/5-setup-bpmn-evenementen-vooroverleg.sql
Use the '22 - Gebeurtenis organiseren' Selectielijst procestype 
Fix result type Selectielijst procestype links
Solves PZ-7521
=> fix: use correct selectielijst_procestype

scripts/docker-compose/imports/openzaak-database/database/5-setup-bpmn-evenementen-vooroverleg.sql, src/itest/kotlin/nl/info/zac/itest/HealthCheckRestServiceTest.kt
Add the missing BPMN Evenementen Vooroverleg statuses
Solves PZ-7543
=> fix: backfill the BPMN Evenementen Vooroverleg statuses

src/main/app/src/app/documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.html, src/main/app/src/app/documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.less, src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.html
FE - ontkoppelde documenten - fix the per row buttons UX
Solves PZ-7493
=> feat(app): ontkoppelde documenten - fix buttons UX

.github/workflows/build-test-deploy.yml
Ensure the code is rebuilt when a minor or major version build is requested, even when there is no code change.
Solves PZ-7623
=> fix(build): force building for non patch version

src/itest/kotlin/nl/info/zac/itest/ZaakRestServiceBpmnTest.kt, src/main/java/net/atos/zac/flowable/processengine/ProcessEngineLookupImpl.java, src/main/kotlin/net/atos/zac/flowable/bpmn/UserTaskCompletionListener.kt
Completed tasks are left in Solr and therefore in work lists
Solves PZ-7562
=> feature: remove completed BPMN tasks from Solr

src/main/app/src/app/admin/parameter-edit/parameter-edit.component.html, src/main/app/src/app/admin/parameter-edit/parameter-edit.component.ts
Filter out medewerker mail in from and replyTo in Automatische ontvangstbevestiging section
Solves PZ-7683
=> fix: filter out medewerker mail from Automatische ontvangstbevestiging

src/main/app/src/app/informatie-objecten/model/file-icon.ts, src/main/app/src/app/shared/document-icon/document-icon.component.ts, src/main/app/src/app/zoeken/model/datum-range.ts, src/main/app/src/app/zoeken/zoek/filters/date-filter/date-filter.component.ts, src/main/app/src/app/zoeken/zoek/filters/multi-facet-filter/multi-facet-filter.component.ts, src/main/app/src/app/zoeken/zoek/zoek.component.html, src/main/app/src/app/zoeken/zoek/zoek.component.ts
This pull request introduces several updates to improve type safety, simplify logic, and enhance maintainability across multiple components in the application. The key changes include making inputs optional where appropriate, replacing custom classes with generated types, and refactoring methods for better clarity and efficiency.
* Updated `DatumRange` to allow `null` values for `van` and `tot` properties and adjusted the constructor accordingly to handle `null` values. (`src/main/app/src/app/zoeken/model/datum-range.ts`)
* Replaced `DatumRange` and `FilterParameters` with `GeneratedType` counterparts in `DateFilterComponent` and `MultiFacetFilterComponent`, respectively, ensuring consistent type usage across the application. (`src/main/app/src/app/zoeken/zoek/filters/date-filter/date-filt …
=> refactor: fix a bunch of lint errors

docs/manuals/inrichting-zaakafhandelcomponent/inrichting-zaakafhandelcomponent.md, scripts/docker-compose/imports/smartdocuments-wiremock/mappings/wsxmldeposit-wizard.json, src/itest/kotlin/nl/info/zac/itest/BpmnDocumentCreationRestServiceTest.kt, src/itest/kotlin/nl/info/zac/itest/DocumentCreationRestServiceTest.kt, src/main/app/src/assets/i18n/en.json, src/main/app/src/assets/i18n/nl.json
Use correct spelling of SmartDocuments everywhere (with a capital 'D').
Solves PZ-7731
=> chore: use correct spelling of SmartDocuments everywhere

src/main/app/package-lock.json, src/main/app/package.json
Added (temporary) peer dependency to the form-data package to (hopefully) fix the security vulnerability https://github.com/infonl/dimpact-zaakafhandelcomponent/security/dependabot/100
Solves PZ-7748
=> chore: added (temporary) peer dependency to the form-data package to fix the security vulnerability 

renovate.json
Updated pinned PodiumD component versions for PodiumD release 4.2: https://dimpact.atlassian.net/wiki/spaces/PCP/pages/353894412/PodiumD+4.2
Solves PZ-7589
=> chore: update pinned PodiumD component versions for PodiumD release 4.2

src/main/app/src/app/admin/parameter-edit/parameter-edit.component.html
fixing the rendering of the list of groups in task details
Solves [PZ-7707]
=> fix: properly handle Observable in the template using async pipe

docker-compose.yaml
Simplified Keycloak Docker Compose configuration and fixed health check HTTP requests. Also re-ordered containers in Docker Compose file for consistency.
Solves PZ-7811
=> chore: simplified Keycloak Docker Compose configuration

src/main/kotlin/nl/info/zac/app/zaak/ZaakRestService.kt, src/main/kotlin/nl/info/zac/app/zaak/converter/RestZaakConverter.kt, src/main/kotlin/nl/info/zac/app/zaak/model/RestZaak.kt, src/test/kotlin/nl/info/zac/app/zaak/ZaakRestServiceTest.kt, src/test/kotlin/nl/info/zac/app/zaak/converter/RestZaakConverterTest.kt, src/test/kotlin/nl/info/zac/app/zaak/model/RestZakenFixtures.kt
Made part of RestZaakConverter.kt logic static and moved it to Kotlin extension functions in RestZaak.kt.
Solves PZ-7823
=> chore: made part of RestZaakConverter.kt logic static and moved it to Kotlin extension functions in RestZaak.kt

src/main/kotlin/nl/info/zac/search/IndexingService.kt
Handle generic Exception instead of individual exceptions
Solves: PZ-7868
=> fix: handle all exceptions during reindexing

src/itest/kotlin/nl/info/zac/itest/ZaakRestServiceBpmnTest.kt, src/itest/resources/bpmn/itProcessDefinition.bpmn, src/itest/resources/bpmn/summaryForm.json, src/itest/resources/bpmn/testForm.json, src/main/kotlin/net/atos/zac/flowable/delegate/ExpressionExtensions.kt, src/main/kotlin/net/atos/zac/flowable/delegate/SendEmailDelegate.kt, src/main/kotlin/net/atos/zac/flowable/delegate/UpdateZaakJavaDelegate.kt, src/test/kotlin/net/atos/zac/flowable/delegate/SendEmailDelegateTest.kt
Allow use of fixed value and JUEL expressions
Solves: PZ-7718, PZ-7735
=> feature: use generic Expression interface for SendEmailDelagate

src/main/kotlin/nl/info/zac/app/admin/ReferenceTableRestService.kt, src/main/kotlin/nl/info/zac/app/admin/ZaakafhandelParametersRestService.kt
Allow behandelaar to display tasks
Solves PZ-7890
=> fix: remove authorization in endpoints used by BPMN

src/main/app/package-lock.json
Update on-headers low vulnerability
Solves PZ-7594
=> fix: bump package-lock versions

.github/workflows/run-e2e.yml
Use correct Azure CLI GitHub action name.
Solves PZ-7933
=> chore: use correct Azure CLI GitHub action name

charts/zac/Chart.yaml, charts/zac/README.md, charts/zac/templates/config.yaml
PABC rest url not required for deployment
Solves [PZ-7689]
=> fix: make PABC rest url not required

docker-compose.yaml, renovate.json
Upgrade to OpenZaak 1.23.0 in Docker Compose setup.
Solves PZ-8020
=> chore: upgrade to OpenZaak 1.23.0 in Docker Compose setup

src/main/app/src/assets/i18n/en.json, src/main/app/src/assets/i18n/nl.json, src/main/kotlin/nl/info/zac/app/task/TaskRestService.kt, src/main/kotlin/nl/info/zac/exception/ErrorCode.kt, src/test/kotlin/net/atos/zac/flowable/ZaakVariabelenServiceTest.kt, src/test/kotlin/nl/info/client/zgw/drc/model/DrcFixtures.kt, src/test/kotlin/nl/info/test/org/flowable/cmmn/api/runtime/FlowableCmmnApiRuntimeFixtures.kt, src/test/kotlin/nl/info/test/org/flowable/task/api/FlowableTaskApiFixtures.kt, src/test/kotlin/nl/info/zac/app/documentcreation/DocumentCreationRestServiceTest.kt, src/test/kotlin/nl/info/zac/app/informatieobjecten/EnkelvoudigInformatieObjectUpdateServiceTest.kt, src/test/kotlin/nl/info/zac/app/signalering/converter/RESTSignaleringTaakConverterTest.kt, src/test/kotlin/nl/info/zac/app/task/TaskRestServiceTest.kt, src/test/kotlin/nl/info/zac/app/task/model/TaskRestFixtures.kt, src/test/kotlin/nl/info/zac/notification/NotificationReceiverTest.kt, src/test/kotlin/nl/info/zac/signalering/SignaleringServiceTest.kt
Fixed issue with signing documents via goedkeuren task. Refactored unit tests and fixtures.
Solves PZ-7987
=> fix: fix issue with signing documents via goedkeuren task

src/test/kotlin/nl/info/zac/app/zaak/converter/RestZaakConverterTest.kt, src/test/kotlin/nl/info/zac/documentcreation/converter/DocumentCreationDataConverterTest.kt, src/test/kotlin/nl/info/zac/search/converter/ZaakZoekObjectConverterTest.kt
Fixed Kotlin unit test compiler warnings (nullables).
Solves PZ-8085
=> fix: fixed Kotlin unit test compiler warnings (nullables)

.github/workflows/build-test-deploy.yml
Allows for manual build on `hotfix/*` branches where you can override the version number
Solves PZ-8117
=> feat: add hotfix flow to build pipeline

src/e2e/features/9-bpmn.feature, src/e2e/step-definitions/bpmn.ts
Adapt e2e tests to the new test BPMN process
Solves PZ-7433
=> feature: add status and result selection for BPMN test

src/main/app/src/assets/i18n/en.json, src/main/app/src/assets/i18n/nl.json
Set a translation anyway for ZGW validation errors.
Solves PZ-8155
=> fix: set a translation anyway for ZGW validation errors

.github/workflows/build-test-deploy.yml, src/itest/kotlin/nl/info/zac/itest/config/ProjectConfig.kt
Run the integration tests twice on GitHub: with and without the ZAC PABC feature flag integration.
Solves PZ-8206
=> chore: run the integration tests twice on GitHub: with and without the ZAC PABC feature flag integration

charts/zac/Chart.yaml, charts/zac/README.md, charts/zac/templates/deployment.yaml, charts/zac/templates/opa-deployment.yaml
Use less specific health check for opa to alleviate init on fresh install. Also removed potential scheduling issue
Solves PZ-8169
=> feat: modify health check for opa

src/main/kotlin/nl/info/zac/flowable/bpmn/model/ZaaktypeBpmnProcessDefinition.kt, src/main/resources/schemas/V76__add_product_aanvraag_type_zaaktype_omscrijving_to_zaaktype_bpmn_process.sql
Respective columns are required to start a BPMN zaaktype and getting authorized BPMN zaken
Solves [PZ-8050]
=> feat: Add zaaktype_omschrijving and product_aanvraag_type columns

src/itest/kotlin/nl/info/zac/itest/ZaaktypeBpmnProcessDefinitionRestServiceTest.kt, src/itest/kotlin/nl/info/zac/itest/config/ItestConfiguration.kt, src/main/kotlin/nl/info/zac/app/admin/ZaaktypeBpmnProcessDefinitionRestService.kt, src/main/kotlin/nl/info/zac/app/admin/model/RestZaaktypeBpmnProcessDefinition.kt, src/main/kotlin/nl/info/zac/authentication/UserPrincipalFilter.kt, src/main/kotlin/nl/info/zac/flowable/bpmn/ZaaktypeBpmnProcessDefinitionService.kt, src/main/kotlin/nl/info/zac/flowable/bpmn/model/ZaaktypeBpmnProcessDefinition.kt, src/main/resources/schemas/V77__make_zaaktype_omscrijving_not_null_in_zaaktype_bpmn_process.sql, src/test/kotlin/nl/info/zac/app/zaak/ZaakRestServiceTest.kt, src/test/kotlin/nl/info/zac/authentication/UserPrincipalFilterTest.kt, src/test/kotlin/nl/info/zac/flowable/bpmn/ZaaktypeBpmnProcessDefinitionServiceTest.kt, src/test/kotlin/nl/info/zac/flowable/bpmn/model/FlowableBpmnFixtures.kt, src/test/kotlin/nl/info/zac/mailtemplates/MailTemplateServiceTest.kt, src/test/kotlin/nl/info/zac/test/listener/MockkClearingTestListener.kt
BPMN zaaktypes are in a different DB table. Consider them too for authorization checks
Solves PZ-8293
=> feature: consider also BPMN zaaktypes for authorization

src/e2e/step-definitions/zaak.ts
E2E: align to recently adjusted Zaak create form
Solves PZ-8332
=> feat(e2e): align to recently adjusted Zaak create form

src/main/app/src/app/taken/taak-view/taak-view.component.ts
FE - fix missing zaak data on Aanvullende Informatie task view
- Fixes displaying of Hervatten/Resume radio buttons
Solves PZ-8381
=> feat(app): fix missing zaak data on Aanvullende Informatie task view

src/main/app/src/app/informatie-objecten/informatie-object-edit/informatie-object-edit.component.ts, src/main/app/src/app/zaken/zaak-ontkoppelen/zaak-ontkoppelen-dialog.component.html, src/main/app/src/app/zaken/zaak-opschorten-dialog/zaak-opschorten-dialog.component.html, src/main/app/src/app/zaken/zaken-vrijgeven-dialog/zaken-vrijgeven-dialog.component.html
FE - Documement detail - new version form - file upload field optional
Bonus: prevent submit on canceling dialog
Solves PX-8387
=> feat(app): Documement detail - New version form - file upload field optional

src/itest/kotlin/nl/info/zac/itest/NotificationsTest.kt, src/itest/kotlin/nl/info/zac/itest/SearchRestServiceTest.kt, src/main/kotlin/nl/info/zac/productaanvraag/ProductaanvraagEmailService.kt, src/main/kotlin/nl/info/zac/productaanvraag/ProductaanvraagService.kt, src/test/kotlin/nl/info/zac/flowable/bpmn/model/FlowableBpmnFixtures.kt, src/test/kotlin/nl/info/zac/productaanvraag/ProductaanvraagServiceTest.kt
Assign zaak to group and add betrokkenen to zaak in BPMN productaanvraag flow. Refactored code and tests a bit for better readability.
Solves PZ-8393
=> feat: assign zaak to group and add betrokkenen to zaak in BPMN productaanvraag flow

docs/manuals/bpmn-guide/README.md, src/itest/resources/bpmn/itProcessDefinition.bpmn, src/main/java/net/atos/zac/flowable/FlowableHelper.java, src/main/kotlin/net/atos/zac/flowable/delegate/ExpressionExtensions.kt, src/main/kotlin/net/atos/zac/flowable/delegate/ResumeZaakDelegate.kt, src/main/kotlin/net/atos/zac/flowable/delegate/SuspendZaakDelegate.kt, src/test/kotlin/net/atos/zac/flowable/delegate/ResumeZaakDelegateTest.kt, src/test/kotlin/net/atos/zac/flowable/delegate/SendEmailDelegateTest.kt, src/test/kotlin/net/atos/zac/flowable/delegate/SuspendZaakDelegateTest.kt, src/test/kotlin/net/atos/zac/flowable/delegate/UpdateZaakJavaDelegateTest.kt
Add the ability to suspend and resume zaken by using ServiceTasks
Solves PZ-7723, PZ-7724
=> feature: suspend and resume delegates for BPMN zaken

src/main/java/net/atos/zac/productaanvraag/InboxProductaanvraagService.java, src/main/java/net/atos/zac/productaanvraag/model/InboxProductaanvraagListParameters.java
Investigate "Could not resolve attribute 'initiator' of 'net.atos.zac.productaanvraag.model.InboxProductaanvraag': org.hibernate.query.sqm.PathElementException: Could not resolve attribute 'initiator' of 'net.atos.zac.productaanvraag.model.InboxProductaanvraag" exception
=> feat: log query parameters for InboxProductaanvraag

src/itest/kotlin/nl/info/zac/itest/KlantRestServiceTest.kt, src/main/app/src/app/klanten/bedrijf-view/bedrijf-resolver.service.spec.ts, src/main/app/src/app/klanten/bedrijf-view/bedrijf-view.component.html, src/main/app/src/app/klanten/bedrijf-view/bedrijf-view.component.ts, src/main/app/src/app/klanten/klanten.service.spec.ts, src/main/app/src/app/zaken/model/betrokkeneIdentificatie.ts, src/main/kotlin/nl/info/zac/app/klant/KlantRestService.kt, src/test/kotlin/nl/info/zac/app/klant/KlantRestServiceTest.kt
This PR solves the error that the KvK nummer is shown while not stored in openZaak. It will now correctly show an error which states that the KvK-nummer is unknown.
Solves PZ-8582
=> fix: Show kvk unknown error

scripts/docker-compose/imports/brp-personen-wiremock/mappings/proxy-requests-without-headers.json, src/itest/kotlin/nl/info/zac/itest/KlantRestServiceTest.kt, src/main/app/src/app/klanten/klanten.service.ts
Do not send null value in X-ZAAK-ID header
Solves PZ-8860
=> fix: klanten/persoon usage
