infonl/dimpact-zaakafhandelcomponent

.github/workflows/build-test-deploy.yml

As a separate step from the build step so that we can run multiple test steps in parallel later on.

feat: run unit tests in GitHub workflow. 

---

.github/workflows/build-test-deploy.yml

We currently have a GitHub Container registry with the name 'dimpact-zac'. Hence this is how we need to name our Docker image for now. Later on we should rename this to 'zaakafhandelcomponent'. Dimpact has no role to play in this. :-)

fix: fixed Docker push step by renaming Docker image 

---

build.gradle.kts

The trick was to set the outputDir in the OpenAPI Gradle plugin to the folder where the clients are generated. Before it would check the entire root folder of the project to see if things are up to data which of course they never were. Now it works like a charm.

feat: use Gradle up-to-date checking in OpenAPI plugin

---

docker-compose.yaml

to fix warnings when starting up Docker Compose on ARM machines

chore: add missing platform attributes for BRP and GBA containers 

---

.github/workflows/check-for-conventional-commits.yml

Do not run the conventional commit GitHub Action on the main branch.
Solves PZ-443

fix: do not run the conventional commit GitHub Action on the main branch

---

.github/workflows/build-test-deploy.yml

This should fix the new build step (again).
For now I added a secret token to the repository settings. You should be able to use the GITHUB_TOKEN but it doesn't work.
It also now passes the correct tag to the hook.

fix(build): change token and pass correct branch

---

src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java
src/test/kotlin/net/atos/zac/app/zaken/ZakenRESTServiceTest.kt

Switched back to using field injection because constructor injection is not working (yet at least) for the ZAC JAX-RS endpoints. Unfortunately had to refactor tje unit test in question accordingly which makes the unit test code more convoluted.
Solves PZ-449

feat: fixed ZAC startup error due to use of unsupported constructor injection

---

src/test/kotlin/net/atos/zac/aanvraag/AanvraagFixtures.kt
src/test/kotlin/net/atos/zac/app/zaken/ZakenRESTServiceTest.kt
src/test/kotlin/net/atos/zac/app/zaken/model/RESTZakenFixtures.kt
src/test/kotlin/net/atos/zac/authentication/AuthenticationFixtures.kt
src/test/kotlin/net/atos/zac/authentication/UserPrincipalFilterTest.kt
src/test/kotlin/net/atos/zac/identity/model/IdentityFixtures.kt
src/test/kotlin/net/atos/zac/policy/output/PolicyOutputFixtures.kt
src/test/kotlin/net/atos/zac/util/JsonbConfigurationTest.kt
src/test/kotlin/net/atos/zac/zaaksturing/model/ZaaksturingFixtures.kt

Added missing SPDX copyright headers for the newly added Kotlin backend unit tests.
Solves PZ-452

chore: added missing SPDX headers for backend unit tests

---

build.gradle.kts
gradle.properties

Added dependsOn from npmRunBuild to generateOpenApiSpec Gradle task so  that "./gradlew clean test" succeeds.
Solves PZ-454

chore: added missing dependency from npmRunBuild Gradle task and generateOpenApiSpec

---

src/main/app/tsconfig.spec.json

This pr will add missing types in the tsconfig.spec file. tests were failing because the google global was missing in the test environment
Solves: PZ-474

fix: add type to tsconfig.types

---

docker-compose.yaml
start-docker-compose-with-zac.sh
start-docker-compose.sh

Only pull ZAC Docker Image when starting Docker Compose since this is not needed for the other Docker images. Also upgraded OpenLDAP Docker Image.
Solves PZ-556.

chore: only pull ZAC Docker Image when starting Docker Compose

---

docker-compose.yaml
start-docker-compose-with-zac.sh
start-docker-compose.sh

No longer use container names in Docker Compose because for example the TestContainers framework does not support this. Use project name instead when starting up Docker Compose for more flexibility but still have fixed container names.
Solves PZ-569.

feat: no longer use container names in Docker Compose 

---

start-docker-compose.sh

Docker Compose without ZAC start script should not pull ZAC Docker image.
Solves PZ-574

chore: fix Docker Compose without ZAC start script 

---

.github/CODEOWNERS

This will add Rick and Joran explicitly to codeowners
Because they are not in the team

PZ-602 fix(codeowners): add Rick and Joran

---

.github/dependabot.yml
.github/workflows/clean-up-cache-on-pr-close.yml
.github/workflows/run-e2e.yml
.github/workflows/update-gradle-wrapper.yml

Added docs about the Update Gradle Wrapper GitHub Action workflow. Also added missing license headers.
Solves PZ-628

chore: added docs about the Update Gradle Wrapper GitHub Action workflow

---

.github/workflows/build-test-deploy.yml

Run the unit and integration tests in parallel in GitHub to improve performance a little bit (especially once we get more unit tests).
Solves PZ-617.

chore: run unit tests and itests in parallel

---

.github/workflows/build-test-deploy.yml
docker-compose.yaml

Use the Keycloak --hostname-url startup option so that Keycloak uses a different frontend URL vs backend URL and we do not need to change our /etc/hosts file for the connection to Keycloak in our Docker Compose set-up.
Solves PZ-645.

feat: use the Keycloak --hostname-url startup option

---

.github/workflows/build-test-deploy.yml
docs/development/INSTALL-DOCKER-COMPOSE.md

Cancel any existing GitHub build workflow runs on the same branch to save unnecessary time and resources. See: https://docs.github.com/en/actions/using-jobs/using-concurrency
Solves PZ-713.

chore: cancel any existing GitHub build workflow runs on the same branch

---

build.gradle.kts
src/itest/kotlin/io/kotest/provided/ProjectConfig.kt

Wait until ZAC is healthy before starting the integration tests to fix the issue that on fast machines the integration tests started before ZAC and/or Open Zaak were healthy. Note that the ZAC healthpoint also checks Open Zaak.
Solves PZ-712.

feat: wait until zac is ready before starting integration tests

---

.github/dependabot.yml

So that the Dependabot PRs do not interfere with our own PRs.
Solves PZ-733.

chore: set Dependabot workflow schedule time earlier 

---

src/itest/kotlin/io/kotest/provided/ProjectConfig.kt
src/itest/kotlin/nl/lifely/zac/itest/NotificationsTest.kt
src/itest/kotlin/nl/lifely/zac/itest/ZaakafhandelParametersTest.kt
src/itest/kotlin/nl/lifely/zac/itest/client/KeycloakClient.kt
src/itest/kotlin/nl/lifely/zac/itest/client/ZacClient.kt

In our integration tests always request a new access token from Keycloak using the refresh token to make sure the access token does not expire.
Solves PZ-692

chore: always request a new access token from Keycloak

---

startupwithenv.sh

Fixed crashing of WildFly when debug logging was enabled by disabling masking in the 1Password CLI tool which we use to run WildFly in IntelliJ. Also see: https://developer.1password.com/docs/cli/reference/commands/run
Solves PZ-847

fix: fix crash of WildFly in IntelliJ when debug logging is enabled in WildFly

---

src/main/java/net/atos/client/zgw/ztc/model/Informatieobjecttype.java
src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java
src/main/java/net/atos/zac/configuratie/ConfiguratieService.java
src/main/java/net/atos/zac/documentcreatie/DocumentCreatieService.java
src/main/java/net/atos/zac/documentcreatie/model/DocumentCreatieGegevens.java
src/main/java/net/atos/zac/documentcreatie/model/Registratie.java
src/test/kotlin/net/atos/client/zgw/zrc/model/ZrcFixtures.kt
src/test/kotlin/net/atos/client/zgw/ztc/model/ZtcFixtures.kt
src/test/kotlin/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTServiceTest.kt
src/test/kotlin/net/atos/zac/authentication/UserPrincipalFilterTest.kt
src/test/kotlin/net/atos/zac/documentcreatie/model/DocumentCreatieFixtures.kt

Send objectinformatietype to Smartdocuments when creating a new document because without this Smartdocuments cannot create the document in Open Zaak.
Solves PZ-856

feat: send objectinformatietype to Smartdocuments 

---

src/main/java/net/atos/zac/documentcreatie/DocumentCreatieService.java
src/main/java/net/atos/zac/documentcreatie/model/Registratie.java

Make informatieobjecttype field for Smartdocuments create document request lowercase because Smartdocuments expects this.
Solves PZ-863

fix: make informatieobjecttype field for Smartdocuments lowercase

---

src/main/app/src/app/identity/identity.service.ts
src/main/app/src/app/shared/http/zac-http-client.ts

Angular httpclient does not handle pathParams when you pass it to params. this was a missconception and was not tested correctly when ZacHttpClient was implemented. This pr will add some utility functions so the httpclient can deal with pathParams
Solves PZ-762

fix: fix zac http client not dealing with pathParams

---

src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java
src/test/kotlin/net/atos/zac/app/zaken/ZakenRESTServiceTest.kt
src/test/kotlin/net/atos/zac/app/zaken/model/RESTZakenFixtures.kt

Reindex Solr search index when zaak has been assigned from the 'toekennen' REST endpoint.
Solves PZ-949

feat: reindex Solr when zaak is assigned from 'toekennen' endpoint

---

build.gradle.kts
src/itest/kotlin/nl/lifely/zac/itest/IdentityServiceTest.kt
src/main/java/net/atos/zac/identity/IdentityService.java

Fix CodeQL security finding: "LDAP query built from user-controlled sources" by using UnboundID LDAP library to build LDAP filters and escape user input.
Solves PZ-966

fix: fix CodeQL security finding: "LDAP query built from user-controlled sources"

---

.github/workflows/codeql-analysis.yml

Added CodeQL analysis for 'javascript-typescript' (see: https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning-with-codeql) and only setup Java & Gradle for 'java-kotlin' analysis.
Solves PZ-968

chore: add typescript codeql analysis

---

.github/workflows/codeql.yml

To comply with GitHub default naming. Also added category to CodeQL analysis action.
Solves PZ-971

chore: rename CodeQL GitHub workflow file 

---

docs/development/README.md
scripts/wildfly/install-wildfly.sh

This will expose /metrics and /health on the wildlfy admin port (9990)
Note: You might need to run `./scripts/widlfly/install-wildfly.sh` to enable this

PZ-604: expose metrics

---

.github/workflows/build-test-deploy.yml
scripts/github/test-workflows.sh

Runners can't be set through environment variables, but can be set via a job output.
new line for build

fix: set the runners for github action jobs dynamically

---

.github/dependabot.yml

Added e2e folder to Dependabot to updates e2e NPM dependencies.
Solves PZ-1028

chore: add e2e folder to Dependabot to updates e2e NPM dependencies

---

.github/workflows/run-e2e.yml

Re-enabled the nightly e2e tests that were temporarily disabled since we switched off our Azure environment over xmas.
Solves PZ-1048

chore: re-enable e2e tests

---

.github/workflows/build-test-deploy.yml
.github/workflows/codeql.yml
build.gradle.kts
docs/development/INSTALL.md
docs/development/testing.md
scripts/github/.actrc
scripts/github/.secrets-sample
src/main/java/net/atos/zac/webdav/WebdavStore.java
src/main/webapp/WEB-INF/web.xml

Updated to latest nl.info version of WebDAV servlet lib, which is now published to Maven Central. Removed now obsolete references to GitHub 'read packages' tokens since the webdav-servlet JAR is now publicly available.
Solves PZ-1040

chore: use latest version of WebDAV servlet lib

---

docker-compose.yaml

Added workaround for the issue where both the BRP Proxy and GBA Mock Docker containers fail to start on an M3 Pro Mac. Also upgraded the BRP Proxy Docker image to the latest version.
Solves PZ-1147

fix: BRP Proxy and GBA Mock Docker containers fail to start on M3 Pro Mac

---

.github/workflows/trivy-code-scanning.yml

Added permission to upload Trivy reports to source code scanner workflow.
Solves PZ-1184

fix: added permission to upload Trivy source code reports

---

src/main/java/net/atos/client/zgw/zrc/model/GeometryCollection.java
src/main/java/net/atos/client/zgw/zrc/model/Point.java
src/main/java/net/atos/client/zgw/zrc/model/Point2D.java
src/main/java/net/atos/client/zgw/zrc/model/Polygon.java

Removed obsolete usage of Apache Commons hashcodebuilder and use the more standard Objects.hash() instead.
Solves PZ-973

chore: removed obsolete usage of Apache Commons hashcodebuilder

---

build.gradle.kts

Excluded generated Java code from JaCoCo test coverage report.
Fixes PZ-1315

chore: exclude generated Java code from JaCoCo test coverage report

---

.github/workflows/build-test-deploy.yml

Did not add auto-merge however because that unfortunately does not trigger our push workflow. See https://github.com/fastify/github-action-merge-dependabot/issues/134
Solves PZ-1420

chore: added auto-approve for Dependabot PRs

---

.github/dependabot.yml
pom.xml

Added Dependabot checks for the dependencies in our Maven pom.xml file to at least get notified of new WildFly releases (extra manual steps are also required for WildFly upgrades).
Solves PZ-1451

chore: added Dependabot Maven checks

---

.github/workflows/build-test-deploy.yml

To hopefully free up more disk space and fix the 'no space left on device' issue when saving the Docker images we use.
Solves PZ-1454

chore: use jlumbroso/free-disk-space GitHub action

---

docker-compose.yaml

Upgraded Solr in Docker Compose to 9.5.0. Also switched to slim version to reduce size and vulnerabilities. #minor
Solves PZ-1442

feat: upgraded Solr in Docker Compose to 9.5.0

---

scripts/docker-compose/imports/openzaak-database/database/3-setup-indienen-aansprakelijkstelling-zaaktype.sql
src/main/java/net/atos/zac/shared/helper/OpschortenZaakHelper.java
src/test/kotlin/net/atos/client/zgw/zrc/model/ZrcFixtures.kt
src/test/kotlin/net/atos/zac/shared/helper/OpschortenZaakHelperTest.kt

Fixed code so that you can now postpone and resume a zaak when the zaak/zaaktype does not have a 'streefdatum', which may be the case depending on how the zaaktype is configured.
Solves PZ-1407

fix: you cannot postpone and resume a zaak if the zaak has no streefdatum

---

Dockerfile
helm/templates/deployment.yaml

Removed no longer needed --enable-preview flag now that we are on JDK 21.
Solves PZ-1507

chore: removed no longer needed --enable-preview flag

---

Dockerfile

Switched to UBI9 Minimal base Docker image as it seems a more secure and better maintained image.
Solves PZ-1553

chore: switched to UBI9 Minimal base Docker image 

---

src/main/java/net/atos/zac/configuratie/ConfiguratieService.java
src/main/resources/wildfly/configure-wildfly.cli

To allow for max 80MB file uploads.
Solves PZ-1566

fix: increased max upload file size in Wildfly / RESTEasy 

---

build.gradle.kts

Because it was out of date and not in sync with the Node version we use in our package.json.
Solves PZ-1569

chore: upgraded Node in the Gradle Node plugin

---

Dockerfile

Set JVM max heap size in ZAC Docker container to 1GB.
Solves PZ-1562

fix: set max heap size in ZAC Docker container

---

.github/workflows/build-test-deploy.yml
.github/workflows/scheduled-container-scanning.yml
.github/workflows/trivy-code-scanning.yml

Only report high & severity level vulnerabilities in Trivy Docker image scans on GitHub.
Solves PZ-1614

chore: only report high & severity level vulnerabilities in Trivy Docker image scans on GitHub

---

src/main/java/net/atos/zac/websocket/event/ScreenEventObserver.java
src/main/resources/wildfly/configure-wildfly.cli

To hopefully solve websocket timeout issues and hopefully solve the issue of newly created tasks sometimes not appearing automatically in the zaak detail screen.
Solves PZ-1465

fix: set WildFly socket read and write timeouts to infinity 

---

src/e2e/features/5-external-systems.feature
src/e2e/step-definitions/zaak.ts

Add delay before clicking on create document to allow page to load

fix: add delay before clicking create document

---

README.md

Because now it shows failing if there is just one PR branch that is failing. We just want to show the status of the main branch in our badges.
Solves PZ-1631

chore: show GitHub CI status badge on our GitHub homepage for the main branch only

---

.github/workflows/build-test-deploy.yml

So that we can distinguish between unit- and integration test coverage in Codecov when we want to.
Solves PZ-1636

chore: added flags to Codecov reports 

---

build.gradle.kts
docs/development/testing.md
src/itest/kotlin/io/kotest/provided/ProjectConfig.kt
src/itest/kotlin/nl/lifely/zac/itest/AppContainerTest.kt
src/itest/kotlin/nl/lifely/zac/itest/IdentityServiceTest.kt
src/itest/kotlin/nl/lifely/zac/itest/InformatieObjectenTest.kt
src/itest/kotlin/nl/lifely/zac/itest/NotificationsTest.kt
src/itest/kotlin/nl/lifely/zac/itest/PlanItemsRESTServiceTest.kt
src/itest/kotlin/nl/lifely/zac/itest/ZaakafhandelParametersTest.kt
src/itest/kotlin/nl/lifely/zac/itest/ZakenRESTServiceTest.kt
src/itest/kotlin/nl/lifely/zac/itest/client/KeycloakClient.kt
src/itest/kotlin/nl/lifely/zac/itest/client/ZacClient.kt

Use the OkHttpClient lib everywhere in our integration tests in favour of the old no longer supported KHttp library.
Solves PZ-1644

chore: use okhttpclient in integration tests in favor of khttp

---

build.gradle.kts
src/main/java/net/atos/zac/aanvraag/ProductaanvraagService.java
src/main/java/net/atos/zac/app/zaken/ZakenRESTService.java
src/main/java/net/atos/zac/notificaties/NotificatieReceiver.java
src/main/resources/json-schema/productaanvraag-dimpact.json
src/test/kotlin/net/atos/client/or/object/model/ObjectRegistratieFixtures.kt
src/test/kotlin/net/atos/zac/aanvraag/AanvraagFixtures.kt
src/test/kotlin/net/atos/zac/notificaties/NotificatieFixtures.kt
src/test/kotlin/net/atos/zac/notificaties/NotificatieReceiverTest.kt

Added OpenAPI spec for new 'productaanvraag dimpact' object type so that Java model classes for this object type are generated. Added unit test for the NotifcatieReceiver class. And also moved these generated Java classes to a 'generated' subpackage. Note that in this PR this new productaanvraag type is not actually used yet. It is just preparing for that.
Solves PZ-1477

chore: generate Java model classes for new 'productaanvraag dimpact' object type

---

build.gradle.kts

Excluded generated coverage JSON reports from Spotless JSON check.
Solves PZ-1791

fix: exclude frontend coverage JSON report from Spotless

---

src/main/app/src/app/taken/taak-view/taak-view.component.ts
src/main/java/net/atos/zac/app/taken/TakenRESTService.java
src/test/kotlin/net/atos/zac/app/taken/TakenRESTServiceTest.kt

When clicking "Opslaan & afronden" for a Taak, the Toelichting is now correctly persisted.
Solves PZ-1570

fix: persist Toelichting when finishing a Taak

---

src/main/java/net/atos/zac/app/taken/TakenRESTService.java

`update` and `complete` methods do several changes to a task. Each one should be in a separate transaction
Solves PZ-1798

fix: change description and due-date in a separate transaction

---

src/main/java/net/atos/zac/event/AbstractEvent.java
src/main/java/net/atos/zac/notificaties/NotificatieReceiver.java
src/main/java/net/atos/zac/zoeken/IndexeerServiceHelper.java
src/main/java/net/atos/zac/zoeken/converter/ZaakZoekObjectConverter.java
src/main/java/net/atos/zac/zoeken/model/zoekobject/ZaakZoekObject.java
src/test/kotlin/net/atos/client/zgw/shared/model/SharedFixtures.kt
src/test/kotlin/net/atos/client/zgw/zrc/model/ZrcFixtures.kt
src/test/kotlin/net/atos/zac/identity/model/IdentityFixtures.kt
src/test/kotlin/net/atos/zac/notificaties/NotificatieReceiverTest.kt
src/test/kotlin/net/atos/zac/zoeken/converter/ZaakZoekObjectConverterTest.kt

Fixed the indexing of zaak stakeholders (betrokkenen, zaak-roles in the ZGW APIs) by ZAC where multiple roles of the same type were not added to the Solr index of a zaak.
Solves PZ-1603

fix: fixed Solr search indexing of zaak stakeholders(betrokkenen)

---

src/itest/kotlin/nl/lifely/zac/itest/InformatieObjectenTest.kt
src/main/java/net/atos/zac/app/informatieobjecten/InformatieObjectenRESTService.java

When first uploading a document, OpenZaak initializes it with an empty signature (not null). This is now supported by ZAC when signing documents.
Solves PZ-1584

fix: handle the initial empty signature when signing documents

---

.gitignore
src/main/app/src/app/admin/formulier-defintie.service.ts
src/main/app/src/app/admin/health-check.service.ts
src/main/app/src/app/admin/mailtemplate-beheer.service.ts
src/main/app/src/app/admin/mailtemplate-koppeling.service.ts
src/main/app/src/app/admin/referentie-tabel.service.ts
src/main/app/src/app/admin/zaakafhandel-parameters.service.ts
src/main/app/src/app/bag/bag.service.ts
src/main/app/src/app/fout-afhandeling/fout-afhandeling.service.spec.ts
src/main/app/src/app/fout-afhandeling/fout-afhandeling.service.ts
src/main/app/src/app/identity/model/logged-in-user.ts
src/main/app/src/app/identity/model/user.ts
src/main/app/src/app/informatie-objecten/informatie-objecten.service.ts
src/main/app/src/app/klanten/klanten.service.ts
src/main/app/src/app/mailtemplate/mailtemplate.service.ts
src/main/app/src/app/zaken/zaken.service.ts

The FoutAfhandelingService was returning `Observable<any>`, which effectively removed the type checking on any observable that got passed to it. All mistyping that came to light have been fixed as well.
Resolves PZ-1882

fix: typings for FoutAfhandelingService were broken

---

build.gradle.kts
gradle/libs.versions.toml
src/itest/kotlin/io/kotest/provided/ProjectConfig.kt
src/itest/kotlin/nl/lifely/zac/itest/NotificationsTest.kt
src/itest/kotlin/nl/lifely/zac/itest/ZakenRESTServiceTest.kt
src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt
src/main/kotlin/net/atos/zac/app/zaken/ZakenRESTService.kt
src/main/kotlin/net/atos/zac/app/zaken/model/RESTZakenVerdeelGegevens.kt
src/main/kotlin/net/atos/zac/zaken/ZakenService.kt
src/test/kotlin/net/atos/client/zgw/zrc/model/ZrcFixtures.kt
src/test/kotlin/net/atos/zac/app/zaken/ZakenRESTServiceTest.kt

The 'assign zaken from list' REST endpoint now returns immediately while the process is started in the background using Kotlin coroutines. There is no feedback of this process to the client yet. This will come in a follow-up PR.
Solves PZ-1750

feat: made the 'assign zaken from list' REST endpoint asynchronous

---

src/main/java/net/atos/zac/signalering/model/SignaleringType.java
src/test/kotlin/net/atos/zac/app/signaleringen/SignaleringenRestServiceTest.kt
src/test/kotlin/net/atos/zac/app/zaken/model/RESTZakenFixtures.kt
src/test/kotlin/net/atos/zac/signalering/model/SignaleringFixtures.kt

Unit test to allow us test order of elements and partially execution time
Increasing maxDelay to 1000 ms shows that by using parallelStream:
* we do not lose order or elements
* execution time is reduced from 50-60 seconds to 1-2 seconds
Note that in real-life the difference would not be that big since common thread pool is busier and REST requests might take longer

chore: PZ-1868: add unit test

---

src/main/java/net/atos/zac/app/audit/converter/zaken/AuditZaakobjectWijzigingConverter.java
src/test/kotlin/net/atos/zac/audit/model/AuditZaakobjectWijzigingConverterTest.kt

Audittrailrecords over ZaakobjectProductaanvraag bevatten geen nuttige informatie voor de eindgebruiker. Daarom gaan we deze uitfilteren.
Resolves PZ-1696

feat: filter wijzigingen in ZaakobjectProductaanvraag uit de historie

---

src/main/kotlin/net/atos/zac/app/zaken/ZakenRESTService.kt
src/main/kotlin/net/atos/zac/app/zaken/model/RESTBesluit.kt
src/main/kotlin/net/atos/zac/zaken/ZakenService.kt
src/test/kotlin/net/atos/zac/app/zaken/ZakenRESTServiceTest.kt

Use construction injection for ZakenRESTService and no longer field injection as constructor injection is preferred, mainly for better testability. See e.g. https://www.baeldung.com/java-spring-field-injection-cons
Solves PZ-1942

chore: use construction injection for ZakenRESTService 

---

config/detekt.yml
src/itest/kotlin/nl/lifely/zac/itest/ZakenRESTServiceTest.kt
src/itest/kotlin/nl/lifely/zac/itest/client/ZacClient.kt
src/main/kotlin/net/atos/zac/app/zaken/ZakenRESTService.kt
src/main/kotlin/net/atos/zac/app/zaken/converter/RESTOpenstaandeTakenConverter.kt
src/main/kotlin/net/atos/zac/app/zaken/converter/RESTZaakConverter.kt
src/main/kotlin/net/atos/zac/app/zaken/model/RESTBesluit.kt
src/main/kotlin/net/atos/zac/app/zaken/model/RESTBesluitIntrekkenGegevens.kt
src/main/kotlin/net/atos/zac/app/zaken/model/RESTBesluitVastleggenGegevens.kt
src/main/kotlin/net/atos/zac/app/zaken/model/RESTBesluitWijzigenGegevens.kt
src/main/kotlin/net/atos/zac/app/zaken/model/RESTBesluittype.kt
src/main/kotlin/net/atos/zac/app/zaken/model/RESTCommunicatiekanaal.kt
src/main/kotlin/net/atos/zac/app/zaken/model/RESTDocumentOntkoppelGegevens.kt
src/main/kotlin/net/atos/zac/app/zaken/model/RESTZaak.kt
src/main/kotlin/net/atos/zac/app/zaken/model/RESTZaakBetrokkeneGegevens.kt
src/main/kotlin/net/atos/zac/app/zaken/model/RESTZaakKoppelGegevens.kt
src/main/kotlin/net/atos/zac/app/zaken/model/RESTZaakOntkoppelGegevens.kt
src/main/kotlin/net/atos/zac/app/zaken/model/RESTZaakOverzicht.kt
src/main/kotlin/net/atos/zac/app/zaken/model/RESTZaakToekennenGegevens.kt
src/main/kotlin/net/atos/zac/zaken/ZakenService.kt
src/test/kotlin/net/atos/zac/aanvraag/ProductaanvraagServiceTest.kt
src/test/kotlin/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverterTest.kt
src/test/kotlin/net/atos/zac/app/informatieobjecten/model/InformatieObjectenRESTFixtures.kt
src/test/kotlin/net/atos/zac/app/taken/model/TakenRESTFixtures.kt
src/test/kotlin/net/atos/zac/app/util/UUIDReaderTest.kt
src/test/kotlin/net/atos/zac/app/zaken/model/RESTZakenFixtures.kt
src/test/kotlin/net/atos/zac/notificaties/NotificatieFixtures.kt
src/test/kotlin/net/atos/zac/zoeken/converter/ZaakZoekObjectConverterTest.kt

Default setting in Detekt is to allow this. See: https://ncorti.com/detekt/docs/rules/style#wildcardimport.
Solves PZ-1950

chore: do not allow java.util.* wildcard imports for Kotlin files

---

src/main/kotlin/net/atos/zac/app/zaken/ZakenRESTService.kt
src/main/kotlin/net/atos/zac/app/zaken/model/RESTZakenVerdeelGegevens.kt
src/main/kotlin/net/atos/zac/zaken/ZakenService.kt

Because this should be mandatory according to the frontend and the user manual.
Solves PZ-1952

chore: make groupId mandatory in the backend when assigning zaken from a list

---

src/e2e/step-definitions/zaak.ts

The BAG acceptance environment has been taken down. Until we find a solution, we need to skip searching for an address in the e2e tests.
Solves PZ-1973

fix: skip searching for address in BAG in e2e tests for now

---

src/main/java/net/atos/zac/signalering/event/SignaleringEventObserver.java

Events that do not result in signals are now logged with warning. Change that to fine
Increased severity introduced with c45295d6b9d9ac78f54c70afc7321243d1aa47e0

chore: reduce warning to fine for events we don't care about

---

src/e2e/features/6-zaken-verdelen.feature
src/e2e/features/7-taken-verdelen.feature
src/e2e/step-definitions/taken-verdelen.ts
src/e2e/step-definitions/zaken-verdelen.ts
src/main/app/src/app/taken/taken.service.ts

Het verdelen van taken naar een groep, zonder een gebruiker te selecteren, was stuk
Solves PZ-1963

fix: Verdelen van taken werkt niet als je alleen een groep opgeeft en geen behandelaar

---

src/test/kotlin/net/atos/client/zgw/ztc/ZTCClientServiceTest.kt

Wait 5 seconds at most to eviction to happen
Currently this test is flaky, depending on the VM/system load

fix: wait for async eviction to kick-in

---

src/e2e/features/6-zaken-verdelen.feature
src/e2e/features/7-taken-verdelen.feature
src/e2e/step-definitions/authentication.ts
src/e2e/step-definitions/common.ts

The end-to-end tests behave differently on the build server to when they are run locally. This change deals with this by making sure the user is logged in (as a Given) before running the test
Solves PZ-2094

fix: make new e2e tests work on the build server

---

CONTRIBUTING.md
LICENSE.md
build.gradle.kts
config/licenseHeader.txt

Because our new convention is that the the year in our SPDX headers indicates the initial year of contribution (i.e. it is not updated thereafter).
Solves PZ-2109

chore: no longer automatically update year in SPDX copyright header

---

.github/workflows/build-test-deploy.yml
.github/workflows/check-for-conventional-commits.yml
.github/workflows/codeql.yml
.github/workflows/snyk-code-scanning.yml
.github/workflows/trivy-code-scanning.yml

Added support to our GitHub Workflows for a GitHub Merge Queue by adding `on: merge_group:` to those workflows that perform a check. See: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
Solves PZ-2110

chore: add support to our GitHub Workflows for GitHub Merge Queue

---

src/itest/kotlin/nl/lifely/zac/itest/SignaleringenRestServiceTest.kt

Events and DB are populated asynchronously
Wait more time to avoid flakes on slower systems (GitHub)

fix: increase SignaleringenRestServiceTest timeouts

---

src/itest/kotlin/nl/lifely/zac/itest/SignaleringenRestServiceTest.kt

On empty DB we return empty list
In this case the test should retry listing

fix: retry listing signaleringen on empty list

---

docker-compose.yaml
gradle/libs.versions.toml
pom.xml
scripts/docker-compose/imports/otel-collector/otel-collector-config.yaml
scripts/wildfly/install-wildfly.sh
src/main/resources/wildfly/configure-wildfly.cli

Add standard Open Telemetry metrics to WildFly. Also added a Open Telemetry Collector in the Docker Compose setup. When deployed to an environment this does mean that an Open Telemetry Collector is required there as well or else WildFly will log many error messages about not being able to connect to Open Telemetry collector.
Solves PZ-604

feat: add OpenTelemetry to WildFly

---

build.gradle.kts

OPA does not recognize Windows 10 and 11:
https://github.com/Bisnode/opa-gradle-plugin/pull/120

feat: disable OPA plugin on Windows

---

build.gradle.kts
gradle/libs.versions.toml

See: https://opentelemetry.io/docs/languages/java/automatic/annotations/ E.g. you can now annotate a method or function with `@WithSpan`. Note that if you want to use these annotations on Kotlin service classes you will need to annotate these classes with the `@AllOpen` annotation.
Solves PZ-2177

chore: added support for Open Telemetry instrumentation annotations

---

src/main/java/net/atos/zac/shared/helper/OpschortenZaakHelper.java
src/main/kotlin/net/atos/zac/task/TaskService.kt
src/test/kotlin/net/atos/zac/app/planitems/PlanItemsRESTServiceTest.kt
src/test/kotlin/net/atos/zac/app/taken/TakenRESTServiceTest.kt
src/test/kotlin/net/atos/zac/app/zaken/ZakenRESTServiceTest.kt
src/test/kotlin/net/atos/zac/authentication/UserPrincipalFilterTest.kt
src/test/kotlin/net/atos/zac/shared/helper/OpschortenZaakHelperTest.kt
src/test/kotlin/net/atos/zac/task/TaskServiceTest.kt
src/test/kotlin/net/atos/zac/util/JsonbConfigurationTest.kt
src/test/kotlin/net/atos/zac/websocket/SessionRegistryTest.kt
src/test/kotlin/net/atos/zac/zaken/ZakenServiceTest.kt
src/test/kotlin/net/atos/zac/zoeken/IndexeerServiceTest.kt

Check for unnecessary stubs in some of our unit tests using mockk's `checkUnnecessaryStub`. Fixed resulting issues. Added `clearAllMocks` calls after `When` clauses in some of our tests.
Solves PZ-2179

chore: check for unnecessary stubs in unit tests

---

docker-compose.yaml

So that they are kept over restarts for local development.
Solves PZ-2194

chore: added Docker Compose volume mapping for Grafana settings 

---

gradle.properties
src/itest/kotlin/nl/lifely/zac/itest/NotificationsTest.kt
src/itest/kotlin/nl/lifely/zac/itest/config/ProjectConfig.kt
src/itest/resources/kotest.properties

Disable Kotest autoscanning for integration tests for faster test execution. See: https://kotest.io/docs/next/framework/project-config.html#runtime-detection
Solves PZ-2183

chore: disable Kotest autoscanning for integration tests

---

Dockerfile
docker-compose.yaml

Enable overriding of WildFly env vars by setting the WILDFLY_OVERRIDING_ENV_VARS env var in our Dockerfile.
Solves PZ-2218

fix: enable overriding of WildFly env vars 

---

scripts/docker-compose/imports/keycloak/realm.json

Appears to be unused as no code checks for it
Might be lefover from past iterations

chore: remove zaakbehandelaar composite role

---

src/main/java/net/atos/zac/zoeken/IndexeerService.java
src/main/kotlin/net/atos/zac/app/taken/TakenRESTService.kt
src/main/kotlin/net/atos/zac/app/zaken/ZakenRESTService.kt
src/main/kotlin/net/atos/zac/task/TaskService.kt
src/main/kotlin/net/atos/zac/zaken/ZakenService.kt
src/test/kotlin/net/atos/zac/app/zaken/ZakenRESTServiceTest.kt
src/test/kotlin/net/atos/zac/task/TaskServiceTest.kt
src/test/kotlin/net/atos/zac/zaken/ZakenServiceTest.kt
src/test/kotlin/net/atos/zac/zoeken/IndexeerServiceTest.kt

Perform hard Solr commit after assigning and releasing tasks so that the Solr index is updated immediately and the user quickly sees the results.
Solves PZ-2196

chore: perform hard Solr commit after assigning and releasing tasks 

---

scripts/docker-compose/imports/keycloak/realm.json

Make sure we use the same role uuids in our docker compose provisioning scripts as our test environment
Resolves PZ-2222

chore: consolidate keycloak role uuids between test and dev

---

src/e2e/step-definitions/taken-verdelen.ts

The end to end tests were counting on a typo in ZAC.
Solves PZ-2229

fix: typo in e2e test for task assignment

---

src/main/kotlin/net/atos/zac/app/taken/TakenRESTService.kt
src/main/kotlin/net/atos/zac/app/zaken/ZakenRESTService.kt
src/main/kotlin/net/atos/zac/task/TaskService.kt
src/main/kotlin/net/atos/zac/zaak/ZaakService.kt
src/test/kotlin/net/atos/zac/app/taken/TakenRESTServiceTest.kt
src/test/kotlin/net/atos/zac/app/zaken/ZakenRESTServiceTest.kt
src/test/kotlin/net/atos/zac/task/TaskServiceTest.kt
src/test/kotlin/net/atos/zac/zaak/ZakenServiceTest.kt

Clean up asynchronous zaken & tasks code after latest code refactoring. Also renamed ZakenService to ZaakService.
Solves PZ-2251

chore: clean up asynchronous zaken & tasks code after latest code refactoring

---

src/e2e/step-definitions/common.ts

This should make the end to end tests regarding the assignment / releasement of cases / tasks less flaky
Resolves PZ-2229

chore: increase timeout when waiting for zoeken result in e2e tests

---

src/main/java/net/atos/zac/notificaties/NotificatieReceiver.java

During the processing of OpenNotificaties, twebsocket messages were sent to the frontend before the indexing was actually done. Now these messages are postponed to the very end of the process.
Solves PZ-2283

fix: send websocket message at the very end of notification processing

---

src/main/kotlin/net/atos/zac/app/taken/TakenRESTService.kt
src/main/kotlin/net/atos/zac/app/zaken/ZakenRESTService.kt
src/main/kotlin/net/atos/zac/signalering/SignaleringenService.kt

Do not reuse Kotlin coroutine scope at class level because in case of exceptions the entire scope gets cancelled and cannot be reused.
Solves PZ-2337

fix: do not reuse Kotlin coroutine scope at class level 

---

src/main/app/src/app/zaken/zaken-verdelen-dialog/zaken-verdelen-dialog.component.ts
src/main/app/src/app/zaken/zaken.service.ts

For consistency reasons, we want to send a screenEventResourceId when assigning / releasing tasks.
Solves PZ-2338

chore: add screenEventResourceId back when assigning / releasing cases

---

src/main/kotlin/net/atos/zac/task/TaskService.kt
src/test/kotlin/net/atos/zac/task/TaskServiceTest.kt

Continue releasing tasks when a specific open task cannot be found. In a future story we should add more error handling here and also send an actual error to the frontend when this happens I suggest.
Solves PZ:2349

fix: continue releasing tasks when a specific open task cannot be found

---

src/main/kotlin/net/atos/zac/task/TaskService.kt
src/test/kotlin/net/atos/zac/task/TaskServiceTest.kt

Always update search index and send screen event in assigning and releasing tasks.
Solves PZ-2353

fix: always update search index and send screen event in assigning and releasing tasks

---

src/main/java/net/atos/zac/websocket/WebSocketServerEndPoint.java

Decreased log level to get rid of the annoying `Open WebSocket denied for..` errors.
Solves PZ-2355

chore: decrease log level to get rid of the annoying `Open WebSocket denied for..` errors

---

src/main/app/src/app/shared/material-form-builder/form-components/input/input.component.html
src/main/app/src/app/taken/taken-verdelen-dialog/taken-verdelen-dialog.component.ts
src/main/app/src/app/taken/taken-vrijgeven-dialog/taken-vrijgeven-dialog.component.ts
src/main/app/src/app/zaken/zaken-verdelen-dialog/zaken-verdelen-dialog.component.ts
src/main/app/src/app/zaken/zaken-vrijgeven-dialog/zaken-vrijgeven-dialog.component.ts

Users were still able to fill in the Reason field while the assignment / releasement forms were being submitted.
Solves PZ-2131

chore: disable reason field when submitting form

---

src/main/java/net/atos/zac/signalering/event/SignaleringEventObserver.java
src/main/java/net/atos/zac/util/event/JobEventObserver.java

Replaced deprecated managed bean annotations. Managed beans are being deprecated and replaced with CDI beans. 
Solves PZ-2369

chore: replace deprecated managed bean annotations

---

src/main/app/src/app/shared/material-form-builder/form-components/input/input.component.html

We shouldn't allow clearing readonly fields by clicking the `X` icon
Solves PZ-2370

chore: don't allow clearing readonly fields

---

src/main/java/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverter.java
src/test/kotlin/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverterTest.kt

When a document is deleted from OpenZaak directly, we potentially still have a reference to that uuid in cases or tasks. In that case, we want to skip that document in stead of throwing an error.
Solves PZ-2168

chore: skip documents if not found by uuid in OpenZaak

---

src/main/app/src/app/klanten/koppel/klanten/klant-koppel.component.ts
src/main/app/src/app/policy/model/zaak-rechten.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.html
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts
src/main/java/net/atos/zac/app/policy/converter/RESTRechtenConverter.java
src/main/java/net/atos/zac/app/policy/model/RESTZaakRechten.java

In earlier stories, we have updated the rights of the different roles in ZAC. Now we hide the functionalities concerning bag / betrokkene / initiator in the front end if the user has no permission to use them.
Solves PZ-2288

chore: check for rights in frontend for bag / betrokkene / initiator

---

src/main/app/src/app/klanten/persoonsgegevens/persoonsgegevens.component.html

Fixed a bug in the persoonsgegevens component wich caused the unlink / change buttons for the initiator to always be visible
Solves PZ-2421

chore: hide unlink / edit buttons for initiator when not allowed

---

src/main/app/src/app/zaken/zaak-create/zaak-create.component.html

While working on another story we broke the functionality to add an initiator on the create case view. This is now restored.
Solves PZ-2432

fix: re-enable adding initiator in the create case view

---

Dockerfile
docker-compose.yaml

Prints GC logs like:
```
[2024-05-13T11:04:26.757+0000][84.867s] GC(22) Pause Young (Mixed) (G1 Humongous Allocation) 983M->346M(1024M) 14.214ms [2024-05-13T11:04:26.850+0000][84.960s] GC(23) Pause Young (Concurrent Start) (G1 Humongous Allocation) 414M->346M(1024M) 11.180ms 
[2024-05-13T11:04:26.850+0000][84.960s] GC(24) Concurrent Mark Cycle 
[2024-05-13T11:04:26.977+0000][85.087s] GC(24) Pause Remark 744M->744M(1024M) 27.817ms
[2024-05-13T11:04:27.019+0000][85.129s] GC(24) Pause Cleanup 744M->744M(1024M) 0.240ms
[2024-05-13T11:04:27.021+0000][85.131s] GC(24) Concurrent Mark Cycle 170.303ms
```
This helps determine when GC is running and how much memory it reclaims.

feat: add GC logs

---

.github/workflows/build-test-deploy.yml
build.gradle.kts
gradle.properties

Enable Gradle build cache for faster development speed when working locally (especially when switching branches) and minor improvements to our build scripts.
Solves PZ-2480

chore: enable Gradle build cache

---

src/main/java/net/atos/zac/policy/input/UserInput.java
src/test/kotlin/net/atos/zac/policy/input/UserInputTest.kt

Replaces 
```
Cannot invoke "net.atos.zac.authentication.LoggedInUser.getId()" because "loggedInUser" is null: java.lang.NullPointerException: Cannot invoke "net.atos.zac.authentication.LoggedInUser.getId()" because "loggedInUser" is null
```
with: 
```
java.lang.NullPointerException: No logged in user found. Please ensure that user did not log out and its session is still active
```
Solves: PZ-2487

feat: improve error message on missing user data

---

.github/workflows/build-test-deploy.yml
build.gradle.kts

Use Gradle build task for npmRunBuild task. Also added inputs and output to generateWildflyBootableJar task so that it only gets run when it is needed.
Solves PZ-2521

chore: use Gradle build task for npmRunBuild task

---

.github/workflows/build-test-deploy.yml

Cache built frontend artefacts across GitHub workflow jobs to hopefully avoid re-running the npmRunBuild task when running unit tests.
Solves PZ-2547

chore: cache built frontend artefacts across GitHub workflow jobs

---

src/main/kotlin/net/atos/zac/task/TaskService.kt
src/test/kotlin/net/atos/zac/task/TaskServiceTest.kt

By sending tasks to Solr individually during the releasement process, we can make it a bit more robust and give a more useful progress indication.
Solves PZ-2568

chore: send tasks to solr individually during the releasement process

---

build.gradle.kts
src/main/java/net/atos/zac/app/bag/BAGRESTService.java
src/main/resources/openapi-generator-templates/model.mustache

Unfortunately our current workarounds are still required it seems and neither was I able to find a solution to enable our `generateKlantenClient` Gradle task.
Solves PZ-2574

chore: updated docs on how we use the openapi-generator Gradle plugin

---

src/main/kotlin/net/atos/zac/mail/model/EMail.kt

replyTo can be empty, so we need it optional in the model
Solves PZ-2579

fix: make replyTo optional in MailService

---

src/main/app/src/app/shared/batch-progress/batch-process.service.ts
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts

By separating the batch processing logic from the zaken-werkvoorraad component, we can re-use it later for the assignment/releasement of tasks.
Solves PZ-2578

refactor: extract batch processing logic from zaken-werkvoorraad to separate component

---

src/main/kotlin/net/atos/zac/task/TaskService.kt
src/test/kotlin/net/atos/zac/task/TaskServiceTest.kt

By sending tasks to Solr individually during the assign process, we can make it a bit more robust and give a more useful progress indication.
Solves PZ-2585

chore: index tasks individually during the assign task process

---

src/main/app/package-lock.json
src/main/app/package.json
src/main/app/src/app/shared/http/zac.http-.client.spec.ts
src/main/app/src/setupJest.ts

A dependabot merge concerning `openapi-fetch` caused our front end tests to fail, because `jsdom` does not offer an implementation of `fetch` and it's `Request` class. To fix this, we import a fetch polyfill while running the tests.
Solves PZ-2591

chore: fix front end tests after dependabot merge

---

helm/Chart.yaml
helm/templates/config.yaml
helm/templates/secret.yaml
helm/values.yaml

zac should be set up to be able to handle the following environment variables for sendmail instead of mailjet (has not been removed yet):
SMTP_SERVER (required)
SMTP_PORT (required)
SMTP_USERNAME (can be empty)
SMTP_PASSWORD (can be empty)
see values.yml for more descriptions for these fields
zac should preferably not fail or get stuck when sending emails
not using relay servers from k8s always has the risk of 'losing' emails in case of connection issues

feat: configure smtp via environment variables

---

src/main/app/src/app/shared/batch-progress/batch-process.service.ts
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.ts
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.ts

After consolidating the UX for assigning/releasing cases/tasks, the progress snackbar no longer disappeared for cases.
Solves PZ-2604

chore: make sure the progress snackbar closes after assigning/releasing cases

---

.github/workflows/build-test-deploy.yml
build.gradle.kts
codecov.yml
docker-compose.yaml
gradle.properties

Turn off gradle build cache for jacoco integration test report task. Also added Codecov configuration to tell Codecov to wait until our two code cove results have been uploaded. 
Solves PZ-2636

fix: turn off gradle build cache for jacoco integration test report task

---

src/main/app/src/app/informatie-objecten/informatie-object-edit/informatie-object-edit.component.ts

The file for a new version of a document needs to be required in the front end, because the server expects it
Solves PZ-2314

chore: make file required for new version of document

---

src/main/app/src/app/informatie-objecten/informatie-object-edit/informatie-object-edit.component.ts
src/main/java/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverter.java
src/main/java/net/atos/zac/app/informatieobjecten/model/RESTEnkelvoudigInformatieFileUpload.java

It should be possible to create a new document version without uploading a new file.
Solves PZ-2644

chore: allow not uploading a file when adding a new document version

---

src/main/app/src/app/shared/dynamic-table/datasource/zoeken-data-source.ts

Users can enable/disable columns in the different `werkvoorraad` views. This is persisted in session storage. We also enable / disable the selection column based on the logged in user and OPA policies. When anybody switches between user logins within the same session, these two could get out of sync, causing bugs. This is resolved now.
Solves PZ-2621

fix: correctly handle switching between users in zoeken-data-source

---

src/main/java/net/atos/zac/zoeken/IndexeerService.java

In a few scenarios, closed tasks were being re-indexed so they showed up in the werkvoorraad, causing issues with assignment / releasement
Solves PZ-2425

fix: don't re-index closed tasks when a case updates

---

src/main/java/net/atos/zac/aanvraag/ProductaanvraagService.java

No longer support the zaak_omschrijving and zaak_toelichting productaanvraag form fields to set the zaakomschrijving and zaaktoelichting. See: https://dimpact.atlassian.net/wiki/spaces/PZW/pages/110166061/Mapping+productaanvraagtype+Dimpact+-+ZAC
Solves PZ-2768

feat: no longer support the zaak_omschrijving and zaak_toelichting productaanvraag form fields

---

src/itest/kotlin/nl/lifely/zac/itest/NotificationsTest.kt
src/itest/kotlin/nl/lifely/zac/itest/ZakenRESTServiceTest.kt
src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt
src/main/app/src/app/bag/bag-locatie/bag-locatie.component.ts
src/main/app/src/app/shared/location/location-util.ts
src/main/app/src/app/zaken/model/geometryCoordinate.ts
src/main/app/src/app/zaken/zoek/locatie-zoek/locatie-zoek.component.ts
src/main/java/net/atos/client/zgw/zrc/model/Point.java
src/main/java/net/atos/client/zgw/zrc/model/Point2D.java
src/main/java/net/atos/zac/app/bag/converter/RESTBAGConverter.java
src/main/kotlin/net/atos/zac/app/zaken/converter/RESTGeometryConverter.kt
src/main/kotlin/net/atos/zac/app/zaken/model/RESTCoordinates.kt
src/test/kotlin/net/atos/zac/aanvraag/ProductaanvraagServiceTest.kt

Mixed usage of (X,Y) and (latitude, longitude) coordinates caused confusion and bugs. This is now fixed.
Resolves PZ-2763

fix: correctly map latitude/longitude to y/x between OpenZaak and the ol map library

---

helm/templates/signaleren-delete-cron-job.yaml

Use HTTP DELETE method in delete old signaleringen cronjob.
Solves PZ-2786

fix: use HTTP DELETE method in delete old signaleringen cronjob

---

build.gradle.kts
gradle/libs.versions.toml
scripts/docker/build-docker-image.sh

No longer use the Gradle Docker Plugin because it is no longer actively maintained and because it is much slower compared to using the plain Docker command line command.
Solves PZ-2792

chore: no longer use the Gradle Docker Plugin

---

src/main/resources/policies/document-rechten.rego
src/test/resources/policies/document-rechten_test.rego

Recordmanager should be able to delete documents for closed cases.
Resolves PZ-2731

fix: allow recordmanager to delete documents for closed cases

---

scripts/docker-compose/imports/openzaak-database/database/4-setup-zac-config-after.sql

Update the primary key sequences for the tables in which we previously inserted data using fixed primary key values so that new records inserted manually via the OpenZaak UI do not conflict with the records we inserted.
Solves PZ-2913

chore: update the primary key sequences for the tables in which we previously inserted data

---

src/main/app/src/app/documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.html
src/main/app/src/app/documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.less
src/main/java/net/atos/zac/app/ontkoppeldedocumenten/converter/RESTOntkoppeldDocumentConverter.java
src/main/java/net/atos/zac/app/ontkoppeldedocumenten/model/RESTOntkoppeldDocument.java

When unlinked documents are locked, they first need to be unlocked before they can be deleted. We want to indicate this to the user.
Resolves PZ-2922

feat: indicate when unlinked documents are locked

---

.github/workflows/build-test-deploy.yml

Fixed path of generated Java client code in GitHub cache action so they can be cached again.
Solves PZ-2934

chore: fixed path of generated Java client code in GitHub cache action

---

.github/workflows/build-test-deploy.yml
build.gradle.kts

Fixed issue with Gradle Build cache usage in generate Java clients tasks where starting with an empty Gradle cache the project did not build because empty folders were being cached. Cleaned up Gradle build file. Added dependency from itest to buildDockerImage task.
Solves PZ-2939

chore: fix issue with gradle build cache usage in generate Java clients

---

src/main/kotlin/net/atos/zac/app/util/exception/RestExceptionMapper.kt
src/test/kotlin/net/atos/zac/app/util/exception/RestExceptionMapperTest.kt

Only map exceptions in ZGW clients to specific ZGW error messages when the exception cause is either a HttpHostConnectException or an UnknownHostException. To prevent incorrect error messages when other types of exceptions are thrown in the ZGW clients.
Solves PZ-2965

chore: only map exceptions in ZGW clients to specific ZGW error messages in specific cases

---

pom.xml

Upgraded to WildFly 31.0.1 and Galleon 6. To prepare for the upgrade to WildFly 32.
Solves PZ-2978

chore: upgraded to WildFly 31.0.1 and Galleon 6

---

src/main/java/net/atos/zac/app/policy/converter/RESTRechtenConverter.java
src/main/java/net/atos/zac/app/policy/model/RESTZaakRechten.java

There was a typo causing the `E-mail versturen` button to never appear
Solves PZ-2984

chore: fix typo

---

build.gradle.kts
docs/development/updatingDependencies.md
gradle/libs.versions.toml
pom.xml
src/main/java/net/atos/client/zgw/drc/DrcClientService.java
startupwithenv.bat
startupwithenv.sh

Upgraded ZAC to WildFly 32.0.1. Still using Galleon CLI tooling and the WildFly JAR Maven Plugin. Those will be upgraded to WildFly Glow and the WildFly Maven Plugin in a future PR 
Solves PZ-2805

chore: upgrade to wildfly 32.0.1

---

src/main/app/src/app/shared/navigation/navigation.service.ts

Keep the url in the address bar when a route resolver fails during a full browser navigation.
Resolves PZ-2988

chore: keep the url in the address bar when a route resolver fails during a full browser navigation

---

build.gradle.kts

Remove outputs setting in generate Java clients Gradle tasks again as this seems not needed after all and makes the tasks uncacheable by Gradle..
Solves PZ-2997

chore: make sure generate Java clients Gradle tasks can be cached

---

docker-compose.yaml

Updated the BRP proxy and Redis versions to the latest versions. Note that on our test environment we were already using a Redis 7.x version.
Solves PZ-3039

chore: update the BRP proxy and Redis versions to the latest versions

---

src/main/app/src/app/informatie-objecten/informatie-object-edit/informatie-object-edit.component.ts
src/main/java/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverter.java
src/main/kotlin/net/atos/zac/app/zaken/converter/RESTZaakConverter.kt
src/test/kotlin/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverterTest.kt
src/test/kotlin/net/atos/zac/app/informatieobjecten/model/InformatieObjectenRESTFixtures.kt

Fixed issue with vertrouwelijkheidsaanduidingenum conversion. Frontend was converting default value to uppercase when creating a new document version but was using lowercase (correctly) elsewhere.
Solves PZ-3043

fix: fix issue with vertrouwelijkheidsaanduidingenum conversion

---

scripts/docker-compose/imports/objects-api/fixtures/demodata.json
scripts/docker-compose/imports/smartdocuments-wiremock/mappings/wsxmldeposit.json
src/itest/kotlin/nl/lifely/zac/itest/PlanItemsRESTServiceTest.kt
src/itest/kotlin/nl/lifely/zac/itest/ZakenRESTServiceCompleteTest.kt
src/itest/kotlin/nl/lifely/zac/itest/client/ZacClient.kt
src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt
src/itest/kotlin/nl/lifely/zac/itest/config/ProjectConfig.kt
src/main/kotlin/net/atos/zac/app/zaken/ZakenRESTService.kt

Made adding a besluit to a zaak more robust by checking if the informatieobjecten in the besluit are present or not. Also added an integration test for adding a besluit to a zaak, using our second zaaktype which has besluittypes configured in OpenZaak.
Solves PZ-3050

chore: make add besluit to zaak more robust

---

scripts/docker-compose/imports/openldap/zac-scripts/zac-ldap-setup-template.ldif
scripts/docker-compose/imports/smartdocuments-wiremock/mappings/wsxmldeposit.json
src/itest/kotlin/nl/lifely/zac/itest/InformatieObjectenTest.kt
src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt
src/main/java/net/atos/zac/util/IndexRewriteFilter.java
src/main/java/net/atos/zac/util/JsonbConfiguration.java
src/main/kotlin/net/atos/zac/app/util/filter/CharsetInterceptorFilter.kt

Use default UTF8 charset for multipart formdata by adding a ContainerRequestFilter because currently JBoss/RESTEasy does not yet default to UTF8 when the charset is not explicitly set by the client.
Solves PZ-2744

fix: use default UTF8 charset for multipart form data

---

src/itest/kotlin/nl/lifely/zac/itest/ZaakHistorieTest.kt
src/main/java/net/atos/client/zgw/zrc/ZRCClientService.java

Directly map toelichting field to auditToelichting in OpenZaak for Rol, so we don't clutter the Case History.
Resolves PZ-3118

chore: directly map toelichting field to auditToelichting in OpenZaak for Rol

---

src/main/kotlin/net/atos/zac/app/zaken/converter/historie/MapUtils.kt
src/test/kotlin/net/atos/zac/app/zaken/converter/historie/RESTZaakHistorieRegelConverterTest.kt

When comparing arrays in the case history, we should check the length of the array before indexing into it.
Solves PZ-3210

fix: index out of range error when comparing array

---

docker-compose.yaml

Upgraded Grafana in Docker Compose setup. Note: I did not upgrade the OTEL Collector because upgrading that to the latest version (0.104.0) seems to break the ZAC metrics flow to Tempo. To be looked at later.
Solves PZ-3147

chore: upgraded Grafana in Docker Compose setup

---

src/main/java/net/atos/zac/app/informatieobjecten/model/RESTEnkelvoudigInformatieFileUpload.java

Allow adding a new version of a document without uploading a new file
Solves PZ-3149

fix: allow file to be empty for new version of document

---

Dockerfile

Fix reported Docker warnings
```
2 warnings found (use --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 36)
```
Solves: PZ-3151

fix: Docker warnings

---

src/itest/kotlin/nl/lifely/zac/itest/ZaakHistorieTest.kt
src/main/kotlin/net/atos/zac/app/zaken/converter/historie/RESTZaakHistorieRegelConverter.kt
src/test/kotlin/net/atos/zac/app/zaken/converter/historie/RESTZaakHistorieRegelConverterTest.kt

In the case history, fixed a regression in the mapping of zaakobjects in the case history. The `object type` / `object type overig` is now correctly used in the resource, the value is no longer prepended and objects of type ProductAanvraag are completely ignored.
Solves PZ-3158

fix: zaakobjecten mapping regression in case history

---

src/main/kotlin/net/atos/zac/app/zaken/converter/historie/RESTZaakHistoriePartialUpdateConverter.kt
src/test/kotlin/net/atos/zac/app/zaken/converter/historie/RESTZaakHistorieRegelConverterTest.kt

Fixed a hoofdzaak / relevanteAndereZaken regression in the case history. We now fetch the case to show its identification.
Solves PZ-3159

fix: hoofdzaak / relevanteAndereZaken regression in case history

---

src/itest/kotlin/nl/lifely/zac/itest/config/ProjectConfig.kt

If `REMOVE_DOCKER_COMPOSE_VOLUMES` not set, delete volumes
Solves: PZ-3181

fix: delete integration tests Docker Compose volumes by default

---

.github/workflows/update-gradle-wrapper.yml

The GitHub action to update the Gradle Wrapper should use conventional commit format.
The `pr-title-template` is configured so that the title of PRs will match conventional commit checks.

chore(actions): set pr title in update-gradle-wrapper

---

src/itest/kotlin/nl/lifely/zac/itest/KlantRestServiceTest.kt
src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt
src/main/app/src/app/klanten/bedrijf-view/bedrijf-view.component.html
src/main/app/src/app/klanten/bedrijfsgegevens/bedrijfsgegevens.component.html
src/main/app/src/app/klanten/model/bedrijven/bedrijf.ts
src/main/app/src/app/klanten/model/bedrijven/list-bedrijven-parameters.ts
src/main/app/src/app/klanten/model/bedrijven/vestigingsprofiel.ts
src/main/app/src/app/klanten/zoek/bedrijven/bedrijf-zoek.component.html
src/main/app/src/app/klanten/zoek/bedrijven/bedrijf-zoek.component.ts
src/main/app/src/app/shared/validators/customValidators.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json
src/main/java/net/atos/zac/app/klanten/KlantRestService.java
src/main/java/net/atos/zac/app/klanten/converter/RestBedrijfConverter.java
src/main/java/net/atos/zac/app/klanten/converter/RestVestigingsprofielConverter.java
src/main/java/net/atos/zac/app/klanten/model/bedrijven/RESTVestigingsprofiel.java
src/main/java/net/atos/zac/app/klanten/model/bedrijven/RestBedrijf.java
src/main/java/net/atos/zac/app/klanten/model/bedrijven/RestListBedrijvenParameters.java
src/main/java/net/atos/zac/app/klanten/model/bedrijven/RestVestigingsprofiel.java
src/test/kotlin/net/atos/zac/app/klanten/KlantRestServiceTest.kt

Use 'naam' instead of 'handelsnaam' for searching and showing KVK companies since this is how the KVK APIs work (https://developers.kvk.nl/nl/documentation/migration-zoeken-v2). Note that the result of a KVK search is always a 'vestiging' in our case but currently the code does not actually use the 'eersteHandelsnaam' of the vestiging as returned by the 'vestigings profiel'. 
Solves PZ-3186

chore: use naam instead of handelsnaam for kvk vestiging

---

scripts/docker-compose/imports/objects-api/fixtures/demodata.json
src/itest/kotlin/nl/lifely/zac/itest/ZaakHistorieTest.kt
src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt
src/main/java/net/atos/client/zgw/shared/ZGWApiService.java
src/main/java/net/atos/client/zgw/shared/model/Results.java
src/main/java/net/atos/zac/app/klanten/KlantRestService.java
src/main/java/net/atos/zac/documentcreatie/converter/DocumentCreatieDataConverter.java
src/main/java/net/atos/zac/mailtemplates/MailTemplateHelper.java
src/main/java/net/atos/zac/signalering/event/SignaleringEventObserver.java
src/main/java/net/atos/zac/zoeken/converter/ZaakZoekObjectConverter.java
src/main/java/net/atos/zac/zoeken/model/zoekobject/ZaakZoekObject.java
src/main/kotlin/net/atos/client/zgw/ztc/ZtcClientService.kt
src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt
src/main/kotlin/net/atos/zac/app/zaak/converter/RESTZaakConverter.kt
src/main/kotlin/net/atos/zac/app/zaak/converter/RESTZaakOverzichtConverter.kt
src/main/kotlin/net/atos/zac/productaanvraag/ProductaanvraagService.kt
src/main/kotlin/net/atos/zac/zaak/ZaakService.kt
src/test/kotlin/net/atos/client/zgw/zrc/model/ZrcFixtures.kt
src/test/kotlin/net/atos/client/zgw/ztc/model/ZtcFixtures.kt
src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt
src/test/kotlin/net/atos/zac/productaanvraag/ProductaanvraagServiceTest.kt
src/test/kotlin/net/atos/zac/zaak/ZaakServiceTest.kt
src/test/kotlin/net/atos/zac/zoeken/converter/ZaakZoekObjectConverterTest.kt

Added support for creating other types of betrokkenen roles (besides initiator) in the productaanvraag-dimpact handling. Extended integration and unit tests. Refactored code and added code documentation. #minor
Solves PZ-2955

feat: add productaanvraag mapping for other betrokkenen

---

src/main/java/net/atos/zac/admin/ReferenceTableService.java
src/main/kotlin/net/atos/zac/signalering/SignaleringService.kt
src/main/kotlin/nl/lifely/zac/persistence/EntityManagerProducer.kt
src/main/kotlin/nl/lifely/zac/util/NoArgConstructor.kt
src/test/kotlin/net/atos/zac/admin/ReferenceTableServiceTest.kt
src/test/kotlin/net/atos/zac/admin/model/AdminFixtures.kt
src/test/kotlin/net/atos/zac/app/admin/ReferenceTableRestServiceTest.kt
src/test/kotlin/net/atos/zac/signalering/SignaleringServiceTest.kt

Added unit test for reference table service. Added an EntityManagerProducer so that we can use constructor injection for entity managers for easier testing.
Solves PZ-3333

chore: add unit test for reference table service

---

src/e2e/support/worlds/world.ts

Fixed e2e tests not starting by adding missing argument to World constructor.
Solves PZ-3564

fix: fix e2e tests not starting

---

src/main/app/src/app/fout-afhandeling/fout-afhandeling.service.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json
src/main/java/net/atos/zac/policy/output/OverigeRechten.java
src/main/kotlin/net/atos/zac/app/util/exception/RestExceptionMapper.kt
src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt
src/main/kotlin/net/atos/zac/app/zaak/model/RestZaakAssignmentData.kt
src/main/kotlin/net/atos/zac/app/zaak/model/RestZaakAssignmentToLoggedInUserData.kt
src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt
src/test/kotlin/net/atos/zac/app/zaak/model/RestZakenFixtures.kt

Improved error handling for server policy exceptions. These are now transformed into 403 Forbidden HTTP responses and a appropriate generic error message is shown to the user.
Solves PZ-3565

feat: improve error handling for server policy exceptions

---

.github/dependabot.yml

chore(dependabot): add group for typescript-eslint updates
Added a new group in Dependabot configuration to handle updates for typescript-eslint. This includes major, minor, and patch updates, ensuring that TypeScript ESLint dependencies are kept up-to-date.

chore(dependabot): add group for typescript-eslint updates

---

src/main/kotlin/net/atos/zac/authentication/UserPrincipalFilter.kt
src/test/kotlin/net/atos/zac/admin/model/AdminFixtures.kt
src/test/kotlin/net/atos/zac/authentication/UserPrincipalFilterTest.kt

Only get currently active zaakafhandelparameters on user login to determine the list of zaaktypes for which the user is authorised based on their domain role(s).
Solves PZ-3604

fix: only get active zaakafhandelparameters on user login

---

src/itest/kotlin/nl/lifely/zac/itest/ZaakRestServiceTest.kt
src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt
src/main/app/src/app/shared/pipes/vertrouwelijkaanduiding-to-translation-key.pipe.ts
src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt
src/main/kotlin/net/atos/zac/app/zaak/converter/RESTZaakConverter.kt

Fix vertrouwelijkheidaanduiding translation in werkvoorraden by using the correct casing in the zaak response. Extended integration test.
Solves PZ-3636

fix: fix vertrouwelijkheidaanduiding translation in werkvoorraden

---

.github/dependabot.yml

We want to use LTS versions only
Solves: PZ-3671

fix: ignore major node.js version bump

---

src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt
src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt

Additional Information tasks are not affected from zaak fatal date change
Solves: PZ-3678

fix: do not change fatal date of additional info tasks

---

src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt

Temporarily increase read timeout of itest HTTP client to allow for very slow document creation unattended endpoint which sometimes takes over 30 seconds.
Solves PZ-3699

fix: temporarily increase read timeout of itest HTTP client

---

src/itest/kotlin/nl/lifely/zac/itest/EnkelvoudigInformatieObjectRestServiceTest.kt
src/main/java/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjecttypeConverter.java
src/main/java/net/atos/zac/app/informatieobjecten/converter/RestInformatieobjectConverter.java
src/main/java/net/atos/zac/app/informatieobjecten/model/RestEnkelvoudigInformatieFileUpload.java
src/main/java/net/atos/zac/app/informatieobjecten/model/RestEnkelvoudigInformatieObjectVersieGegevens.java
src/main/java/net/atos/zac/app/informatieobjecten/model/RestEnkelvoudigInformatieobject.java
src/main/java/net/atos/zac/app/informatieobjecten/model/RestGekoppeldeZaakEnkelvoudigInformatieObject.java
src/main/java/net/atos/zac/app/informatieobjecten/model/RestInformatieobjecttype.java
src/main/java/net/atos/zac/app/informatieobjecten/model/validation/ValidRestEnkelvoudigInformatieFileUploadFormValidator.java
src/main/kotlin/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectRestService.kt
src/main/kotlin/net/atos/zac/app/signalering/SignaleringRestService.kt
src/main/kotlin/net/atos/zac/app/task/TaskRestService.kt
src/main/kotlin/net/atos/zac/app/task/model/RestTaskDocumentData.kt
src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt
src/main/kotlin/net/atos/zac/app/zaak/converter/RestBesluitConverter.kt
src/main/kotlin/net/atos/zac/app/zaak/model/RestBesluit.kt
src/test/kotlin/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectRestServiceTest.kt
src/test/kotlin/net/atos/zac/app/informatieobjecten/converter/RESTInformatieobjectConverterTest.kt
src/test/kotlin/net/atos/zac/app/informatieobjecten/converter/RestInformatieobjectConverterTest.kt
src/test/kotlin/net/atos/zac/app/informatieobjecten/model/InformatieObjectenRESTFixtures.kt
src/test/kotlin/net/atos/zac/app/informatieobjecten/model/InformatieObjectenRestFixtures.kt
src/test/kotlin/net/atos/zac/app/informatieobjecten/model/validation/ValidRestEnkelvoudigInformatieobjectFileUploadFormValidatorTest.kt
src/test/kotlin/net/atos/zac/app/task/TaskRestServiceTest.kt
src/test/kotlin/net/atos/zac/app/task/model/TaskRestFixtures.kt
src/test/kotlin/net/atos/zac/app/zaak/converter/RestBesluitConverterTest.kt

Fix failing vertrouwelijkheidsaanduiding translation due to incorrect enum conversion in getting current version of enkelvoudiginformatieobjecttype. Added tests.
Solves PZ-3768

fix: fix failing vertrouwelijkheidsaanduiding translation in getting current version of enkelvoudiginformatieobjecttype

---

src/main/java/net/atos/client/zgw/zrc/model/GeometryCollection.java
src/main/java/net/atos/client/zgw/zrc/model/Point.java
src/main/java/net/atos/client/zgw/zrc/model/Point2D.java
src/main/java/net/atos/client/zgw/zrc/model/Polygon.java
src/main/java/net/atos/client/zgw/zrc/util/GeometryJsonbDeserializer.java

Added missing default constructors for Polygon and GeometryCollection Java classes so that the deserialization proces at least can instantiate these classes and gives a better exception message. This avoids the 'could not find default constructor' errors and now gives an error that shows what is really going wrong.
Solves PZ-3823

chore: add missing default constructors for Polygon and GeometryCollection Java classes 

---

src/main/kotlin/net/atos/zac/zaak/ZaakService.kt
src/test/kotlin/net/atos/zac/zaak/ZaakServiceTest.kt

Filter on open zaken when assigning or releasing from list so that closed zaken cannot be assigned or released from the list.
Solves PZ-3876

fix: filter on open zaken when assigning or releasing from list

---

src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt
src/main/app/src/app/informatie-objecten/informatie-objecten.service.ts

Adapt to the new create-document endpoint name
Note that we now require template and template group, so it errors.
Solves: PZ-3905

fix: create-document endpoint

---

src/main/app/src/app/informatie-objecten/model/document-creation-data.ts
src/main/app/src/app/taken/taak-view/taak-view.component.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

Hardcoded template and template group for Create Document flow
This would be changed once we have a dedicated dialog to override some settings
Solves: PZ-3905

fix: use correct data structure for document-creation

---

src/main/app/src/app/informatie-objecten/informatie-object-edit/informatie-object-edit.component.ts

When editing information object, enable submit button on file select. This is achieved by making the title form field dirty.
As well both Title and Description fields now align with create form to have max length of 100.
Solves: PZ-3782

fix: information object edit - enable submit button on file select

---

.github/workflows/update-docker-compose.yml
docker-compose.yaml

Fixed issues with Docker Compose update GitHub workflow. Made all Docker image URLs absolute so that https://github.com/sbe-arg/simple-compose-service-updates can update them. Ignored https://github.com/eugenmayer/officeconverter because that has 'vX.X.X' versions which are deemed newer while they are not.
Solves PZ-4193

chore: fix issues with docker compose update GitHub workflow

---

.github/workflows/build-test-deploy.yml
.github/workflows/run-e2e.yml
.github/workflows/snyk-code-scan.yml
.github/workflows/trivy-docker-image-scan.yml
.github/workflows/update-trivy-scanner-cache.yml

Use a separate GitHub Workflow to download the Trivy databases and add them to the cache. As advised in: https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#cache
Solves PZ-4192

chore: use a separate GitHub Workflow to download the Trivy databases

---

.github/workflows/update-docker-compose.yml

Use a GitHub Personal Access Token in the GitHub Docker Compose update workflow so that Pull Requests created from this workflow will automatically trigger our default build workflows. See: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow
Solves PZ-4221

chore: use a GitHub Personal Access Token in the GitHub Docker Compose update workflow

---

.mvn/wrapper/maven-wrapper.properties

Upgraded Maven to 3.9.9 since Dependabot does not support upgrading Maven in a Maven wrapper.
Solves PZ-4239

chore(deps): upgrade Maven to 3.9.9

---

renovate.json

Added Renovate config with only the docker-compose manager enabled so that we can use the GitHub Renovate App to upgrade dependencies in our Docker Compose file.
Solves PZ-4241

chore: added Renovate config with only the docker-compose manager enabled

---

src/main/kotlin/net/atos/zac/smartdocuments/SmartDocumentsTemplatesService.kt
src/main/kotlin/net/atos/zac/smartdocuments/templates/model/SmartDocumentsTemplate.kt
src/main/kotlin/net/atos/zac/smartdocuments/templates/model/SmartDocumentsTemplateGroup.kt

Do not load ZAP when fetching SD template mappings. Reduces SQL queries twice (from 11 to  5)
Solves: PZ-4189

feature: mark ZAP as lazy

---

.github/workflows/trivy-docker-image-scan.yml
.github/workflows/update-trivy-scanner-cache.yml

Changed schedule of Trivy update cache and scanner from evening to morning because other stuff is already running in the evening and because we want Trivy to run on Monday morning before the working week starts.
Solves PZ-4252

chore: changed schedule of Trivy update cache and scanner GitHub workflows

---

.github/workflows/snyk-code-scan.yml

Disabled Snyk scan in build pipeline since it is broken at the moment but kept the nightly cron job. Maybe we don't even want to have this as part of the build pipeline.
Solves PZ-4271

fix: disabled Snyk scan in build pipeline since it is broken at the moment

---

docs/development/updatingDependencies.md
renovate.json

Added renovate configuration that will:
- create pin docker digests
- add a schedule to update the digests once a month (to refresh images with unchanged tags)
- Added package rule for postgres with a upper version limit
closes PZ-4315

feat: limit proposed version updates in renovate. 

---

.github/workflows/build-test-deploy.yml

The GitHub workflow condition needs the expression syntax to be evaluated correctly.

fix: workflow release condition to avoid infinite releases

---

.github/workflows/check-for-conventional-commits.yml

No longer perform conventional commit check on the merge queue since this now fails with our updated GitHub configuration.
Solves PZ-4430

fix: no longer perform conventional commit check on the merge queue

---

src/main/app/src/app/informatie-objecten/informatie-object-create-attended/informatie-object-create-attended.component.ts
src/main/app/src/app/informatie-objecten/informatie-object-verzenden/informatie-object-verzenden.component.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.html
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

The form gets fully reloaded after the sidebar is closed. The same fix applied for the Document Create form.
Solves: PZ-3740

feat: reset form after document is sent

---

src/itest/kotlin/nl/lifely/zac/itest/SignaleringRestServiceTest.kt
src/main/kotlin/net/atos/zac/app/signalering/SignaleringRestService.kt

Use dash to split words in query parameters
Solves: PZ-4459

fix: comply with rest conventions for naming

---

.github/workflows/codeql.yml

No longer run CodeQL on 'push: main:' since we already run this workflow as a check in GitHub in the merge queue.
Solves PZ-4463

chore: no longer run CodeQL on 'push: main:'

---

build.gradle.kts
src/e2e/step-definitions/external-systems.ts
src/main/app/src/app/informatie-objecten/informatie-object-create-attended/informatie-object-create-attended.component.ts
src/main/app/src/app/klanten/zoek/personen/persoon-zoek.component.ts

Gradle fixes to make it future proof by removing use of deprecated var `rootDir`.
Applied recommended Detekt fixes for some typescript imports.
Resolves: PZ-4471

chore(build): fix gradle and detekt warnings

---

src/main/kotlin/net/atos/zac/zaak/ZaakService.kt
src/test/kotlin/net/atos/zac/zaak/ZaakServiceTest.kt

Send SKIPPED screen event for closed zaken during releasing zaken from the list.
Solves PZ-4468

feat: send SKIPPED screen event for closed zaken during releasing zaken from the list

---

src/main/app/src/app/dashboard/zaken-card/zaken-card.component.html
src/main/app/src/app/dashboard/zaken-card/zaken-card.component.ts
src/main/app/src/app/signaleringen.service.ts

With this PR the web socket providing all the open signals is replaced by paginated requests. On navigating to a next page a new request to the server is executed. And when a general signalering signal arrives, the current page is refetched. Making a new signal shift the whole list. This shifting behaviour is identical to the previous web socket solution behaviour.
Solves: PZ-2612

feat: FE zaken signalering - paginated requests

---

.github/workflows/codeql.yml

Do not run codeql on merge-group when only markdown files have changed.
Solves PZ-4497

fix: do not run codeql on merge-group when only markdown files have changed

---

gradle.properties

Use Gradle configuration cache for improved build performance.
Solves PZ-4505

chore: use Gradle configuration cache for improved build performance

---

src/e2e/step-definitions/zaak.ts

Somehow the locator for the name and clicking it was not working anymore; I don't see why. The most important thing is that the name is there. Clicking other part of that header is fine as well. Now clicking text 'initiator'
Solves: PZ-4506

feat: E2E - fix test creating a zaak

---

.github/workflows/codeql.yml

Use https://github.com/kunitsucom/github-actions-paths-ignore-alternative GitHub action to skip CodeQL analysis when only Markdown files have been changed.
Solves PZ-4537

chore: use GitHub action to skip CodeQL when only Markdown files have been changed

---

scripts/docker-compose/imports/smartdocuments-wiremock/mappings/download-document.json
scripts/docker-compose/imports/smartdocuments-wiremock/mappings/wsxmldeposit-wizard.json
src/main/kotlin/net/atos/zac/documentcreation/DocumentCreationService.kt
src/main/kotlin/net/atos/zac/documentcreation/converter/DocumentCreationDataConverter.kt
src/test/kotlin/net/atos/zac/documentcreation/DocumentCreationServiceTest.kt
src/test/kotlin/net/atos/zac/smartdocuments/SmartDocumentsServiceTest.kt

Fixed SmartDocuments docx media type so that frontend recognizes .docx files created by SmartDocuments as Office documents and shows edit and convert buttons.
Solves PZ-4414

fix: fix SmartDocuments docx media type

---

.github/workflows/build-test-deploy.yml
.github/workflows/trivy-docker-image-scan.yml
Dockerfile

The latest trivy scanning fails. Downgrading the trivy action from master (0.28.0) to 0.27.0.

feature(build): set trivy action version to 0.27.0

---

src/main/kotlin/net/atos/zac/app/klant/KlantRestService.kt
src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt
src/main/kotlin/net/atos/zac/zaak/Betrokkenen.kt
src/main/kotlin/net/atos/zac/zaak/ZaakService.kt
src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt
src/test/kotlin/net/atos/zac/zaak/ZaakServiceTest.kt

Refactoring only to prepare for: 'do not allow multiple betrokkenen of same type in backend'. Moved some more logic from the ZaakRestService to the ZaakService. Translated some stuff to English.
Solves PZ-4518

chore: refactoring to prepare for do not allow multiple betrokkenen of same type in backend

---

.github/workflows/codeql.yml
.github/workflows/snyk-code-scan.yml
.github/workflows/trivy-docker-image-scan.yml

Instead of the master version, we should use explict version numbers, so that we can track version changes better. And will be able to roll back in case of a break.
Use kunitsucom/github-actions-paths-ignore-alternative version 0.0.4. 
Use snyk/actions/* version 0.4.0.
Solves PZ-4576

chore(build): use explicit action versions

---

.github/workflows/build-test-deploy.yml
.github/workflows/codeql.yml

Do not run GitHub build & test workflows when only Markdown files have been changed _and_ we are not on the main branch.
Solves PZ-4581

chore: do not run GitHub build & test workflows in PRs when only Markdown files have been changed

---

src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json
src/main/kotlin/net/atos/zac/app/exception/ErrorCodes.kt
src/main/kotlin/net/atos/zac/app/exception/RestExceptionMapper.kt
src/main/kotlin/net/atos/zac/app/klant/KlantRestService.kt
src/main/kotlin/net/atos/zac/zaak/ZaakService.kt
src/main/kotlin/net/atos/zac/zaak/exception/BetrokkeneIsAlreadyAddedToZaakException.kt
src/main/kotlin/net/atos/zac/zaak/model/Betrokkenen.kt
src/test/kotlin/net/atos/zac/zaak/ZaakServiceTest.kt

Use 409 HTTP response with translated error message when betrokkene is added to zaak but the betrokkene was already added to the zaak with this role type/
Solves PZ-4517

feat: use 409 HTTP response when betrokkene was already added to the zaak

---

src/main/app/src/app/taken/taak-view/taak-view.component.ts

We do not know the `informatieobject.uuid` from the update so we can not push it to list of documents. We have to reload the whole `Taak` to update the list.
Solves PZ-4412

fix: update `taak` after document created update from open forms

---

.github/workflows/build-test-deploy.yml

Use 'INFO push to protected branch' GitHub App in our GitHub workflow to be able to push the generated `publiccode.yaml` file to our protected main branch. See https://github.com/orgs/community/discussions/25305#discussioncomment-8256560 for details.
Solves PZ-4631

fix: use 'INFO push to protected branch' GitHub App to be able to push the generated `publiccode.yaml` file to our protected main branch

---

src/main/app/src/app/taken/taak-view/taak-view.component.spec.ts

Added component tests to validate the behaviour of the `documentCreated` functionality in a "taak". 
Forces websocket-traffic which usually goes via `open-formulieren` -> `open-zaak` -> `zaakafhandelcomponent` to validate behaviour when such traffic is received
Solves PZ-4551

test(taak-view.component): Validate communication for `documentCreated`

---

.github/workflows/build-test-deploy.yml

Use GitHub Deploy Key to be able to commit and push generated publiccode.yaml file. See: https://github.com/sbellone/release-workflow-example for details.
Solves PZ-4649

chore: use GitHub Deploy Key to be able to commit and push generated publiccode.yaml file

---

.licenserc.yaml
src/main/resources/schemas/V34__mail_template_defaults.sql
src/main/resources/schemas/V38__mail_template_defaults_revisited.sql
src/main/resources/schemas/V39__mail_template_defaults_revisited2.sql
src/main/resources/schemas/V40__taken_streef_naar_fataal.sql

Fixed failing deployment on existing environments by reverting adding SPDX copyright headers to Flyway database migration scripts.
Solves 4692

fix: fixed failing deployment on existing environments by reverting adding SPDX copyright headers to Flyway database migration scripts

---

src/main/kotlin/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectUpdateService.kt
src/test/kotlin/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectUpdateServiceTest.kt

Add unit tests to cover the behaviour of createZaakInformatieobjectForZaak with task
Solves: PZ-4646

fix: do not allow concurrent modification of task documents

---

src/itest/kotlin/nl/lifely/zac/itest/DocumentCreationRestServiceTest.kt
src/main/app/src/app/informatie-objecten/informatie-object-create-attended/informatie-object-create-attended.component.ts
src/main/app/src/app/informatie-objecten/model/document-creation-data.ts
src/main/kotlin/net/atos/zac/app/documentcreation/DocumentCreationRestService.kt
src/main/kotlin/net/atos/zac/app/documentcreation/model/RestDocumentCreationAttendedData.kt
src/main/kotlin/net/atos/zac/app/documentcreation/model/RestDocumentCreationAttendedResponse.kt
src/main/kotlin/net/atos/zac/app/documentcreation/rest/RestDocumentCreationAttendedData.kt
src/test/kotlin/net/atos/zac/app/documentcreation/DocumentCreationRestServiceTest.kt
src/test/kotlin/net/atos/zac/app/documentcreation/model/DocumentCreationFixtures.kt

Fixed creation date not set when creating document by using correct field id in frontend. Made author and creation dates mandatory in backend when creating a SmartDocuments document.
Solves PZ-4676

fix: fix creation date not set when creating document

---

scripts/docker-compose/imports/smartdocuments-wiremock/mappings/wsxmldeposit-wizard.json
src/itest/kotlin/nl/lifely/zac/itest/NotificationsTest.kt
src/itest/kotlin/nl/lifely/zac/itest/ZaakRestServiceHistoryTest.kt
src/itest/kotlin/nl/lifely/zac/itest/ZoekenRESTServiceTest.kt
src/main/kotlin/net/atos/zac/productaanvraag/ProductaanvraagService.kt
src/test/kotlin/net/atos/zac/productaanvraag/ProductaanvraagServiceTest.kt

Added a full stop characters to the automatically generated "Aangemaakt vanuit xxx met kenmerk 'yyy'" substring in the zaak explanation from a productaanvraag.
Solves PZ-4711

chore: added a full stop characters to the automatically generated "Aangemaakt vanuit xxx met kenmerk 'yyy'" substring 

---

helm/templates/config.yaml

feat: corrected boolean handling and set false by default

---

src/main/app/src/app/admin/parameter-edit/smart-documents-form/smart-documents-form-item/smart-documents-form-item.component.html
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json

FE - add no document type option to deselect
Solves PZ-4726

feat: FE - add no document type option to deselect

---

helm/Chart.yaml
helm/values.yaml

Added SPDX copyright headers to some Helm Chart files to test if this change indeed skips our pull request build workflow.
Solves PZ-4732

chore: added SPDX copyright headers to some Helm Chart files

---

src/main/kotlin/net/atos/zac/app/documentcreation/DocumentCreationRestService.kt
src/main/kotlin/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectUpdateService.kt
src/main/kotlin/net/atos/zac/documentcreation/DocumentCreationService.kt
src/test/kotlin/net/atos/zac/app/documentcreation/DocumentCreationRestServiceTest.kt
src/test/kotlin/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectUpdateServiceTest.kt
src/test/kotlin/net/atos/zac/documentcreation/DocumentCreationServiceTest.kt

When SmartDocuments callback is invoked we might not have logged in user
Keycloak token expires usually 60-90 seconds after SmartDocuments dialog is opened
Solves: PZ-3731

fix: do not check for task document creation policy

---

src/main/java/net/atos/zac/admin/ZaakafhandelParameterService.java
src/main/java/net/atos/zac/notificaties/NotificatieReceiver.java
src/main/java/net/atos/zac/util/UriUtil.java
src/main/kotlin/net/atos/zac/admin/ZaakafhandelParameterBeheerService.kt
src/main/kotlin/net/atos/zac/app/admin/ZaakafhandelParametersRestService.kt
src/test/kotlin/net/atos/client/zgw/ztc/model/ZtcFixtures.kt
src/test/kotlin/net/atos/zac/admin/ZaakafhandelParameterBeheerServiceTest.kt

Fixed the error in the logs on certain zaaktype changes when we tried to insert a new record in the zaakafhandelparameters database table when we already had a zaakafhandelparameters for the given zaaktype UUID.
Solves PZ-4521

chore: fix error in logs on certain zaaktype changes

---

src/main/app/src/app/taken/taak-view/taak-view.component.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

FE - Taak detail - Show Document Create button only when SmartDocuments is enabled
The Zaak data is loaded after Taak data is loaded; so that is why there is a menu update needed. Discussed with Karin about order of buttons; Create should be the bottom one.
Solves PZ-3406

feat: FE - Taak detail - Show Document Create button only when SmartDocuments is enabled

---

.licenserc.yaml
helm/templates/_helpers.tpl
helm/templates/config.yaml
helm/templates/configmap-nginx.yaml
helm/templates/deployment.yaml
helm/templates/extra-deploy.yaml
helm/templates/hpa.yaml
helm/templates/ingress.yaml
helm/templates/nginx-deployment.yaml
helm/templates/nginx-service.yaml
helm/templates/office-converter-deployment.yaml
helm/templates/office-converter-service.yaml
helm/templates/opa-deployment.yaml
helm/templates/opa-service.yaml
helm/templates/secret.yaml
helm/templates/service.yaml
helm/templates/serviceaccount.yaml
helm/templates/signaleren-cron-job.yaml
helm/templates/signaleren-delete-cron-job.yaml

Reverted adding SPDX headers to Helm Chart files because that breaks our deployment script. The 'Bake deployment' provisioning step failed because it generates a corrupt Helm Chart file with SPDX headers:
```
#
#apiVersion: v1
kind: ServiceAccount
metadata:
name: zac-dev-zaakafhandelcomponent
```
Solves PZ-4778

chore: reverted adding SPDX headers to Helm Chart files because that breaks our deployment script

---

src/main/java/net/atos/zac/notificaties/NotificatieReceiver.java
src/main/kotlin/net/atos/zac/admin/ZaakafhandelParameterBeheerService.kt
src/test/kotlin/net/atos/zac/admin/ZaakafhandelParameterBeheerServiceTest.kt

Reverted changes made in PZ-4521 in the ZaakafhandelParameterBeheerService.kt to see if that solves an issue where new zaakafhandelparameters created from a new zaaktype are sometimes empty.
Solves PZ-4521

chore: revert changes made in PZ-4521 in the ZaakafhandelParameterBeheerService.kt

---

src/main/app/src/app/zaken/besluit-edit/besluit-edit.component.ts

FE -  Besluit edit form -  Publication Date fields were incorrectly prefilled with a testing value. In this PR it is reading the by the backend newly provided fields.
Solves: PZ-4829

feat:  FE -  Besluit edit form -  Publication Date fields incorrectly prefilled

---

.github/workflows/remove-stale-branches.yml

Rename GitHub owner to current name, which hopefully fixes renovate lookup
Solves PZ-4855

chore: Update remove-stale-branches.yml

---

renovate.json

Renovate has to follow the component versions per PodiumD releases, including for open-notificaties. This has been configured to follow only updates up-to the current PodiumD version.
Solves PZ-4823

fix(deps): renovate open-notificaties config

---

src/main/app/src/app/gebruikersvoorkeuren/zoekopdracht-save-dialog/zoekopdracht-save-dialog.component.html
src/main/app/src/app/shared/confirm-dialog/confirm-dialog.component.html
src/main/app/src/app/shared/dialog/dialog.component.html
src/main/app/src/app/shared/material-form-builder/form/form/form.component.html
src/main/app/src/app/taken/taken-verdelen-dialog/taken-verdelen-dialog.component.html
src/main/app/src/app/taken/taken-vrijgeven-dialog/taken-vrijgeven-dialog.component.html
src/main/app/src/app/zaken/intake-afronden-dialog/intake-afronden-dialog.component.html
src/main/app/src/app/zaken/intake-afronden-dialog/intake-afronden-dialog.component.less
src/main/app/src/app/zaken/zaak-afhandelen-dialog/zaak-afhandelen-dialog.component.html
src/main/app/src/app/zaken/zaak-koppelen/zaak-koppelen-dialog.component.html
src/main/app/src/app/zaken/zaak-ontkoppelen/zaak-ontkoppelen-dialog.component.html
src/main/app/src/app/zaken/zaken-verdelen-dialog/zaken-verdelen-dialog.component.html
src/main/app/src/app/zaken/zaken-vrijgeven-dialog/zaken-vrijgeven-dialog.component.html

FE - reduce size of spinner  to fit in its box. Available box space is 17.9883px. So took 18px.
Solves PZ-4454

fix: FE - reduce size of spinner to fit in its box

---

Dockerfile
build.gradle.kts
docker-compose.yaml
pom.xml
src/itest/kotlin/nl/lifely/zac/itest/config/ProjectConfig.kt

Switch to new WildFly Maven Plugin because the old WildFly JAR Maven Plugin is old and deprecated.
Solves PZ-4902

chore: switch to wildfly maven plugin

---

src/main/java/net/atos/client/zgw/zrc/ZrcClientService.java
src/main/java/net/atos/client/zgw/zrc/model/Rol.java
src/main/java/net/atos/client/zgw/zrc/model/RolMedewerker.java
src/main/java/net/atos/zac/formulieren/FormulierRuntimeService.java
src/main/java/net/atos/zac/mailtemplates/MailTemplateHelper.java
src/main/kotlin/net/atos/client/zgw/shared/ZGWApiService.kt
src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt
src/main/kotlin/net/atos/zac/app/zaak/converter/RestZaakConverter.kt
src/main/kotlin/net/atos/zac/app/zaak/converter/RestZaakOverzichtConverter.kt
src/main/kotlin/net/atos/zac/app/zaak/model/RestZaakBetrokkene.kt
src/main/kotlin/net/atos/zac/documentcreation/converter/DocumentCreationDataConverter.kt
src/main/kotlin/net/atos/zac/zoeken/converter/ZaakZoekObjectConverter.kt
src/test/kotlin/net/atos/client/zgw/shared/ZGWApiServiceTest.kt
src/test/kotlin/net/atos/client/zgw/zrc/model/ZrcFixtures.kt
src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt
src/test/kotlin/net/atos/zac/app/zaak/converter/RestZaakConverterTest.kt
src/test/kotlin/net/atos/zac/app/zaak/model/RestZakenFixtures.kt
src/test/kotlin/net/atos/zac/documentcreation/converter/DocumentCreationDataConverterTest.kt
src/test/kotlin/net/atos/zac/mailtemplates/MailTemplateHelperTest.kt
src/test/kotlin/net/atos/zac/zoeken/converter/ZaakZoekObjectConverterTest.kt

Ignore medewerker rol without medewerker because this is possible in the ZGW APIs and it does occur in certain scenarios.
Solves PZ-4904

fix: ignore medewerker rol without medewerker

---

src/main/app/src/app/zaken/intake-afronden-dialog/intake-afronden-dialog.component.html

FE- fix showing fields. The checkbox to send/not send emails only appeared after selecting the ontvankelijk yes/no radio and taking focus of the radio by clicking somewhere outside it. Very confusing for user. After this change the checkbox shows up directly after selecting 1 of the radio buttons.
Solves PZ-4909

feat: FE- fix showing fields

---

build.gradle.kts
src/itest/kotlin/nl/lifely/zac/itest/AppContainerTest.kt
src/itest/kotlin/nl/lifely/zac/itest/config/ItestConfiguration.kt

Ensure the end-2-end tests are hard-coded dependent on the year.
Also some minor boy-scouting on build file and fixed a warning in the tests on duplicate test names.
Solves PZ-4925

feature(e2e): tests dependency on year

---

helm/Chart.lock
helm/Chart.yaml

Revert otel to previous version as 0.111 requires changes in helm chart values/overrides
Solves: PZ-4845

fix: revert otel 0.110 helm chart change

---

.github/workflows/build-test-deploy.yml

Removed concurrency setting in our GitHub build workflow because this causes our automatically generated changelog to miss pull request commits when there are multiple concurrent pull request builds on the main branch.
Solves PZ-4993

fix: removed concurrency setting in our GitHub build workflow

---

.github/workflows/codeql.yml

With codeql [gaining support](https://github.blog/security/application-security/how-to-secure-your-github-actions-workflows-with-codeql/
) for GitHub Actions, let's enable this 
Solves PZ-5005

feat: add actions to codeql workflow

---

.github/workflows/build-test-deploy.yml

Do a git force push when updating the publiccode.yaml in our GitHub workflow to avoid most git push errors "error: failed to push some refs to 'github.com:infonl/dimpact-zaakafhandelcomponent.git'"
Solves PZ-5009

fix: do a git force push when updating the publiccode.yaml in our GitHub workflow

---

.github/workflows/check-for-conventional-commits.yml
.github/workflows/clean-up-cache-on-pr-close.yml
.github/workflows/clean-up-old-zac-docker-images.yml
.github/workflows/codeql.yml
.github/workflows/remove-stale-branches.yml
.github/workflows/run-e2e.yml

pin workflow runner to ubuntu 24.04 instead of latest. Will be kept up-to-date using renovate
Solves PZ-5021

chore(build): pin workflow runner to ubuntu 24.04 instead of latest. 

---

src/main/app/src/app/zaken/zaak-create/zaak-create.component.ts

Fixes accessing arrays when not initialised yet
```
ERROR TypeError: Cannot read properties of undefined (reading 'find')
at n.getMedewerkerGroupFormField (main.0557c498deab72c3.js:1:3132266)
at n.ngOnInit (main.0557c498deab72c3.js:1:3129427)
at nD (main.0557c498deab72c3.js:1:253754)
at jC (main.0557c498deab72c3.js:1:253901)
at tg (main.0557c498deab72c3.js:1:253659)
at Mv (main.0557c498deab72c3.js:1:253383)
at pce (main.0557c498deab72c3.js:1:287099)
at BL (main.0557c498deab72c3.js:1:288354)
at gB (main.0557c498deab72c3.js:1:288184)
at pB (main.0557c498deab72c3.js:1:288115)
```
Solves [PZ-5059](https://dimpact.atlassian.net/browse/PZ-5059)

fix(zaak-create.component): initialize `medewerkers` and `groepen`

---

src/main/app/src/app/fout-afhandeling/dialog/fout-detailed-dialog.component.html
src/main/app/src/app/fout-afhandeling/dialog/fout-dialog.component.html

FE - add missing icon in error dialogs
When implementing new Opschorten and Vwerlenger dialogs, also the Error dialogs were aligned with the new styling. But there were no icons in the nav header added; so after remark and suggestion of Camiel added it thorough this PR
Solves PZ-5060

feat(app): add missing icon in error dialogs

---

src/main/java/net/atos/zac/notificaties/NotificatieReceiver.java
src/main/kotlin/net/atos/zac/admin/ZaakafhandelParameterBeheerService.kt
src/main/kotlin/net/atos/zac/app/admin/ZaakafhandelParametersRestService.kt
src/test/kotlin/net/atos/zac/admin/ZaakafhandelParameterBeheerServiceTest.kt
src/test/kotlin/net/atos/zac/app/admin/ZaakafhandelParametersRestServiceTest.kt
src/test/kotlin/net/atos/zac/notificaties/NotificatieReceiverTest.kt

Makes a difference between receiving an "update" from open-zaak on `zaaktypes` which we already know within `ZAC` and newly published `zaaktypen`
Solves [PZ-5014](https://dimpact.atlassian.net/browse/PZ-5014) and [PZ-4990](https://dimpact.atlassian.net/browse/PZ-4990)

fix: failure copying zaakafhandelparameters

---

src/main/java/net/atos/zac/app/zoeken/converter/RESTZaakZoekObjectConverter.java
src/main/kotlin/net/atos/zac/zoeken/ZoekenService.kt
src/main/kotlin/net/atos/zac/zoeken/model/zoekobject/ZaakZoekObject.kt
src/test/kotlin/net/atos/zac/zoeken/converter/ZaakZoekObjectConverterTest.kt

Fixed broken zaken werkvoorraad due to betrokkenen being null in zaakzoekobject. Perhaps caused by a recent upgrade to Solr.
Solves PZ-5065

fix: fixed broken zaken werkvoorraad due to betrokkenen being null

---

.github/workflows/build-test-deploy.yml

revert force push when updating publiccode.yaml because that can override PR commits altogether
Solves PZ-5081

fix: revert force push when updating publiccode.yaml

---

.github/workflows/helm-chart-release.yml

Looks like the GitHub action cannot fetch chart-releaser 1.7.0. So don't explicitly set a version to download. 
Solves PZ-5105

fix: Don't explicitly version chart-releaser

---

build.gradle.kts

No longer use deprecated indentWithSpaces Gradle setting.
Solves PZ-5117

chore: no longer use deprecated indentWithSpaces Gradle setting

---

src/itest/kotlin/nl/info/zac/itest/util/JsonHelpers.kt

Fixed deprecation warnings for our use of the shouldEqualJson function. Solution taken from: https://github.com/kotest/kotest/issues/3543
Solves PZ-5171

chore: fixed deprecation warnings for our use of the shouldEqualJson function

---

src/main/kotlin/net/atos/zac/app/exception/RestExceptionMapper.kt
src/main/kotlin/nl/info/zac/log/LogUtils.kt
src/main/kotlin/nl/info/zac/util/LoggerWrapper.kt
src/test/kotlin/net/atos/zac/app/util/exception/RestExceptionMapperTest.kt

Always log server errors in REST exception mapper so that uncaught exceptions do not get lost.
Solves PZ-5165

chore: always log server errors in REST exception mapper

---

docs/manuals/ZAC-gebruikershandleiding/ZAC-gebruikershandleiding.md
src/main/kotlin/net/atos/zac/app/klant/model/bedrijven/RestKlantenAdres.kt
src/main/kotlin/net/atos/zac/app/klant/model/bedrijven/RestVestigingsprofiel.kt
src/test/kotlin/net/atos/client/kvk/zoeken/model/KvkZoekenFixtures.kt
src/test/kotlin/net/atos/zac/app/klant/KlantRestServiceTest.kt

Added null handling to all fields in KVK vestigingsprofiel conversion. Added unit tests. Fixed some typos in the ZAC user manual while at it.
Solves PZ-5045

fix: add null handling to kvk vestigingsprofiel conversion

---

src/main/app/src/app/fout-afhandeling/fout-afhandeling.service.ts

No longer show error detail in error detail screen when it is not explicitly sent by the backend.
Solves PZ-5229

chore: no longer show error detail in error detail screen when it is not explicitly sent by the backend

---

.gitignore
docs/development/updatingDependencies.md
scripts/python/README.md
scripts/python/dependencies/brp_version_extractor.py
scripts/python/dependencies/docker_version_extractor.py
scripts/python/dependencies/github_tag_version_extractor.py
scripts/python/dependencies/kvk_version_extractor.py
scripts/python/dependencies/postgresql_version_extractor.py
scripts/python/dependencies/version_data.py
scripts/python/dependencies/versions-of-components.py
scripts/python/init-pyenv.sh
scripts/python/podiumd/component_version.py
scripts/python/podiumd/podiumd_version.py
scripts/python/podiumd/podiumd_version_builder.py
scripts/python/podiumd/podiumd_version_comparator.py
scripts/python/podiumd/podiumd_versions.py
scripts/python/requirements.txt

chore: add python scripts for version retrieval
To make it easier to find versions for individual components and for those used in a podiumd.
Solves: PZ-5197

chore(scripts): add some python scripts

---

src/e2e/step-definitions/zaak.ts

The selector to get "Aanvullende informatie nodig voor zaak" finds both the td cell and div tooltip. Now select specifically the first item from these 2, as that is the item to wait for to become visible.

fix(e2e): select correct for aanvullende informatie nodig voor zaak

---

.github/workflows/build-test-deploy.yml

Only run the Trivvy code scanner on the main branch because it quite often fails in the GitHub merge queue and does not add a lot of value there. May be related to: https://github.com/github/codeql-action/issues/1537
Solves PZ-5362

fix: only run the Trivvy code scanner on the main branch

---

.github/workflows/codeql.yml

Added missing on: main triggger in CodeQL workflow to fix warnings in GitHub about this in our builds.
Solves PZ-5419

chore: added missing on: main triggger in CodeQL workflow to fix warnings in GitHub about this

---

src/main/app/src/app/admin/parameter-edit/parameter-edit.component.html
src/main/app/src/app/admin/parameter-edit/parameter-edit.component.less
src/main/app/src/app/admin/parameter-edit/parameter-edit.component.ts

FE - Zaakafhandel-parameters - date fields number inputs - prevent characters
- scientific 'e' and '-' ignored
- some improved styling
- touching tab Gegevens + (not in Bug description) Tab the Human tasks field doorlooptijden
Solves PZ-5053

fix(app): Zaakafhandel-parameters - date fields number inputs - prevent characters

---

.github/workflows/run-e2e.yml

Add write permissions to e2e workflow to fix 403 on git push
Solves PZ-5425

fix: add write permissions to run-e2e workflow

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

We always have the hardcoded and unmanaged "Zaak is niet ontvankelijk" reason
Solves PZ-5434

fix: do not hide abort zaak button if no managed reasons exist

---

src/itest/kotlin/nl/info/zac/itest/AanvullendeInformatieTaskCompleteTest.kt
src/itest/kotlin/nl/info/zac/itest/CsvRESTServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/IndexingRestServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/NotificationsZaakDeleteTest.kt
src/itest/kotlin/nl/info/zac/itest/NotificationsZaakDestroyTest.kt
src/itest/kotlin/nl/info/zac/itest/ZaakRestServiceHistoryTest.kt
src/itest/kotlin/nl/info/zac/itest/ZoekenRESTServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/config/ItestConfiguration.kt

Add integration test for destroying zaak. For now only checks if the zaak gets correctly removed from the Solr index. To be extended later. Also refactored the order of the integration tests a bit so that we have somewhat less interdependencies between individual integration tests.
Solves PZ-3850

chore: add integration test for destroying zaak

---

.github/workflows/build-test-deploy.yml

Skip building the Docker image and running the integration tests in the merge queue in order to improve overall performance of our build pipeline. This slightly increases the risk of breaking the main branch but we think this is acceptable.
Solves PZ-5417

chore: skip building the Docker image and running the integration tests in the merge queue

---

renovate.json

Fix node version to 20 to prevent lock file format differences
Solves PZ-5497

fix: node version to 20 in renovate

---

src/main/kotlin/net/atos/zac/app/task/TaskRestService.kt
src/main/kotlin/net/atos/zac/app/zaak/ZaakRestService.kt
src/main/kotlin/nl/info/zac/util/CoroutineDispatcherProducer.kt
src/test/kotlin/net/atos/zac/app/task/TaskRestServiceTest.kt
src/test/kotlin/net/atos/zac/app/zaak/ZaakRestServiceTest.kt

Use Kotlin coroutines test dispatcher in unit test to hopefully fix flaky tests on GitHub.
Solves PZ-5570

chore: use Kotlin coroutines test dispatcher in unit test to hopefully fix flaky tests on GitHub

---

src/test/kotlin/net/atos/client/util/JWTTokenGeneratorTest.kt

Add JWTTokenGenerator unit test
Solves PZ-5694

feature: add JWTTokenGenerator test

---

docker-compose.yaml

Replace hashed secret key with human readable one
Solves: PZ-5706

fix: use human-readable secret key for local OAB

---

src/main/app/src/app/zaken/besluit-edit/besluit-edit.component.ts
src/main/app/src/app/zaken/zaak-details-wijzigen/zaak-details-wijzigen.component.ts

Revert some changed from https://github.com/infonl/dimpact-zaakafhandelcomponent/pull/2781 that caused regression in two components due to moving logic from `ngOnInit` to the constructor
Solves [PZ-5710](https://dimpact.atlassian.net/browse/PZ-5710)

fix: revert changes that moved code to constructor instead of `ngOnInit`

---

Dockerfile
docker-compose.yaml

Use non-privileged user in zac docker image and limit amounts of layers
Solves PZ-5719

feat: Use non-privileged user in zac docker image

---

.github/CODEOWNERS

Added Dax to codeowners file so that he is invited to review all pull requests. Also see: https://graphite.dev/guides/in-depth-guide-github-codeowners
Solves PZ-5803

chore: add Dax to codeowners file

---

docker-compose.yaml
start-docker-compose.sh

Make starting of Objecten optional in Docker Compose setup to save startup time and resources for local development.
Solves PZ-5805

chore: make starting of Objecten optional in Docker Compose setup

---

charts/zac/Chart.yaml
charts/zac/README.md
charts/zac/templates/deployment.yaml

Added missing `--addr` argument to ZAC Helm Chart when OPA is run as a side-car container.
Solves PZ-5833

fix: added missing `--addr` argument to ZAC Helm Chart when OPA is run as a side-car container

---

src/main/app/src/app/taken/taken-mijn/taken-mijn.component.html
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.html
src/main/app/src/app/zaken/zaken-afgehandeld/zaken-afgehandeld.component.html
src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.html
src/main/app/src/app/zaken/zaken-werkvoorraad/zaken-werkvoorraad.component.html
src/main/kotlin/net/atos/zac/search/SearchService.kt
src/main/kotlin/net/atos/zac/shared/model/SorteerRichting.kt
src/test/kotlin/net/atos/zac/search/SearchServiceTest.kt

Allows for tables to remove the sorting and add the ability for the backend to search with non-sorting
Solves [PZ-2783](https://dimpact.atlassian.net/browse/PZ-2783)

feat(search): allow for empty sorting

---

.env.example
.env.tpl
docker-compose.yaml
src/itest/kotlin/nl/info/zac/itest/ConfigurationRestServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/config/ItestConfiguration.kt
src/itest/kotlin/nl/info/zac/itest/config/ProjectConfig.kt

Added documentation and integration test for optional ADDITIONAL_ALLOWED_FILE_TYPES environment variable. Note that this env var is not currently used for backend validation when uploading a file. Also, it should in future probably be moved to a reference table instead of an environment variable.
Solves PZ-5883

chore: added documentation and integration test for optional ADDITIONAL_ALLOWED_FILE_TYPES environment variable

---

src/main/app/src/app/zaken/zaak-create/zaak-create.component.ts

Removed the default "E-Formulier" value for communicatie kanaal. It is now required when making a case(zaak)
Solves PZ-5889

Fix: removed default value for communicatie kanaal

---

.github/workflows/build-test-deploy.yml

Ensure the deployment provision workflow is kicked off after the GitHub release is created as it might result in an empty changelog
The release creation job is probably quicker now too as I think we can suffice with a shallow checkout here. 
Solves PZ-6003

feat: wait for provision trigger until release is created

---

.github/workflows/build-test-deploy.yml
.github/workflows/helm-chart-testing.yml

docker-cache is no longer compatible with github actions so we need to drop it. Setting up dockerhub authentication with limited PAT token on shared team account to hopefully avoid running into pull rate limits
Solves PZ-6005

feat: dropping docker-cache 

---

src/main/kotlin/nl/info/zac/productaanvraag/ProductaanvraagService.kt
src/test/kotlin/nl/info/zac/productaanvraag/ProductaanvraagServiceTest.kt

Do not log whole stack trace (except for debugging) when we fail to handle a productaanvraag-Dimpact object.
Solves PZ-6037

chore: muted productaanvraag error handling

---

src/main/app/src/app/shared/indicaties/zaak-indicaties/zaak-indicaties.component.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

Frontend:
- refresh case details page after resuming case (by REST requesting opschorten state)
- more understandable tooltip text on case Opschorten and Verlengen indications
Solves PZ-6182

fix(app): remove case opschorten details page after resuming the case

---

docker-compose.yaml
scripts/docker-compose/imports/prometheus/prometheus.yaml

Fixed WildFly Prometheus metrics scraping by adding a `fallback_scrape_protocol` setting. This fixes these errors in the Prometheus logs:
> "time=2025-04-14T15:26:03.921Z level=ERROR source=scrape.go:1609 msg="Failed to determine correct type of scrape target." component="scrape manager" scrape_pool=prometheus target=http://host.docker.internal:9990/metrics content_type="" fallback_media_type="" err="non-compliant scrape target sending blank Content-Type and no fallback_scrape_protocol specified for target" 
Solves PZ-6295

fix: fix WildFly Prometheus metrics scraping by adding a `fallback_scrape_protocol` setting

---

.github/workflows/run-e2e.yml

**Before merging this we should modify the GitHub Pages configuration to use actions as source.**
* Will **only** publish the latest report unfortunately. That is a limitation that exists because with the actions-publish method, you cannot merge content, only replace.  
* Added link to the artefact in the slack message, so we can still access the report for older runs (up to 180 days)
* After merging this older reports will be lost. 
Afterwards the gh-pages branch can be removed, which allows up to free up 3,5GB of data out of the repository (probably needs some history rewriting)
Solves PZ-6313

feat: stop using gh-pages branch for e2e report

---

.github/workflows/run-e2e.yml

This reverts commit 0dd38ab0dce6144d6a966d1aab57e998a1c0b977.
By changing over to the new way of publishing pages we also mangled publishing of the Helm Charts. 
Solves PZ-6367

feat: re-use gh-pages branch for e2e report

---

src/itest/kotlin/nl/info/zac/itest/IdentityServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/config/ItestConfiguration.kt
src/main/kotlin/nl/info/client/keycloak/KeycloakEmployeesAdminClientConfiguration.kt
src/main/kotlin/nl/info/zac/app/identity/IdentityRestService.kt
src/main/kotlin/nl/info/zac/authentication/UserPrincipalFilter.kt
src/main/kotlin/nl/info/zac/identity/IdentityService.kt
src/main/kotlin/nl/info/zac/identity/model/Group.kt
src/test/kotlin/nl/info/test/org/keycloak/representations/idm/KeycloakRepresentationsIdmFixtures.kt
src/test/kotlin/nl/info/zac/app/admin/ZaakafhandelParametersRestServiceTest.kt
src/test/kotlin/nl/info/zac/identity/IdentityServiceTest.kt
src/test/kotlin/nl/info/zac/identity/model/IdentityFixtures.kt

Add endpoint to return only those groups that have access to a certain zaaktype based on the ZAC Keycloak client (domein) roles and the configuration of a domein role in the zaakafhandelparameters for this zaaktype.
Solves PZ-6318

feat: add endpoint to return only those groups with access to a zaaktype

---

src/itest/kotlin/nl/info/zac/itest/ReferenceTableRestServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/config/ItestConfiguration.kt
src/main/resources/schemas/V69__delete_domein_overig_referentie_waarde.sql

Remove `domein_overig` reference value for clean environments and change into non-system value for existing environments.
Solves PZ-6433

chore: remove domein overig reference value for clean environments

---

src/main/kotlin/nl/info/client/zgw/shared/ZGWApiService.kt

Added code comment on why we set gebruiksrechten when adding a zaakinformatieobject so that we don't forget (again..).
Solves PZ-6451

chore: added code comment on why we set gebruiksrechten when adding a zaakinformatieobject

---

src/main/app/src/app/formulieren/formulier/velden/documenten/documenten-formulier-veld.component.ts
src/main/app/src/app/taken/taken-mijn/taken-mijn.component.ts
src/main/app/src/app/taken/taken-werkvoorraad/taken-werkvoorraad.component.ts
src/main/app/src/app/zaken/besluit-view/besluit-view.component.ts
src/main/app/src/app/zaken/model/zaak.ts
src/main/app/src/app/zaken/zaak-create/zaak-create.component.ts
src/main/app/src/app/zaken/zaak-details-wijzigen/zaak-details-wijzigen.component.ts
src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.ts
src/main/app/src/app/zaken/zaak-link/zaak-link.component.ts
src/main/app/src/app/zaken/zaakdata/zaakdata-form/zaakdata-form.component.ts

This pull request introduces several updates, primarily focused on improving type safety by replacing `any` with more specific types, adding `OnDestroy` lifecycle hooks to components, and updating copyright information. Below is a summary of the key changes:
* Replaced `any` with `unknown` or more specific types in multiple files, such as `BesluitViewComponent`, `Zaak`, `ZaakCreateComponent`, and `ZaakDocumentenComponent`. This ensures better type checking and reduces potential runtime errors. [[1]](diffhunk://#diff-df39433a1a2f46240f7cb8651588bc698070c90ec9025cc9818eeb80ee02a048L55-R55) [[2]](diffhunk://#diff-df39433a1a2f46240f7cb8651588bc698070c90ec9025cc9818eeb80ee02a048L151-R151) [[3]](diffhunk://#diff-cd4cd4a2dec784f00a9f51bf3594ba288435e2b6de28ca9d11001fadecab96c5L58-R58) …

chore: remove `any`

---

src/e2e/step-definitions/external-systems.ts

This pull request updates a test step definition in the `src/e2e/step-definitions/external-systems.ts` file to improve the reliability and clarity of element selection in the test.
Improvements to element selection:
* Replaced the use of `getByText` with `getByRole` for selecting the "Create Document" button. This change makes the selection more robust and accessible by targeting the button role with a regex for its name.
* Updated the logic for waiting for the "Document maken" sidebar to appear by using `getByRole` to target a heading with a specific name. This improves clarity and ensures the test waits for the correct element. And is according to the [testing librarty priority](https://testing-library.com/docs/queries/about/#priority)
Solves broken E2E test

fix: e2e test

---

charts/zac/Chart.yaml
charts/zac/README.md
charts/zac/templates/signaleren-cron-job.yaml
charts/zac/templates/signaleren-delete-cron-job.yaml
src/itest/kotlin/nl/info/zac/itest/SignaleringAdminRestServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/SignaleringRestServiceTest.kt
src/main/kotlin/nl/info/zac/app/admin/SignaleringAdminRestService.kt
src/main/webapp/WEB-INF/web.xml

Move the signaleringen endpoint to the /internal URI so we can manage internal endpoint security easier.
Solves PZ-2846

chore: move the signaleringen endpoint to /internal

---

src/main/kotlin/nl/info/zac/search/converter/DocumentZoekObjectConverter.kt
src/test/kotlin/nl/info/client/zgw/drc/model/DrcFixtures.kt
src/test/kotlin/nl/info/zac/app/informatieobjecten/converter/RestInformatieobjectConverterTest.kt
src/test/kotlin/nl/info/zac/search/converter/DocumentZoekObjectConverterTest.kt
src/test/kotlin/nl/info/zac/search/converter/ZaakZoekObjectConverterTest.kt

Fixed broken documents Solr reindexing by adding null handling on nullable fields.
Solves PZ-6601

fix: fixed broken documents Solr reindexing by adding null handling on nullable fields

---

src/itest/kotlin/nl/info/zac/itest/EnkelvoudigInformatieObjectRestServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/MailRestServiceTest.kt
src/main/java/net/atos/client/zgw/drc/DrcClientService.java
src/main/java/net/atos/client/zgw/shared/util/ZGWClientHeadersFactory.java
src/main/java/net/atos/client/zgw/zrc/ZrcClient.java
src/main/java/net/atos/client/zgw/zrc/ZrcClientService.java
src/main/java/net/atos/client/zgw/zrc/model/ZaakInformatieobject.java
src/main/java/net/atos/zac/app/admin/converter/RESTZaaktypeOverzichtConverter.java
src/main/java/net/atos/zac/app/bag/converter/RestBagConverter.java
src/main/java/net/atos/zac/app/inboxdocumenten/InboxDocumentenRESTService.java
src/main/java/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectDownloadService.java
src/main/java/net/atos/zac/app/informatieobjecten/converter/RestInformatieobjectConverter.java
src/main/java/net/atos/zac/app/informatieobjecten/converter/RestInformatieobjecttypeConverter.java
src/main/java/net/atos/zac/app/mailtemplate/MailtemplateRESTService.java
src/main/java/net/atos/zac/app/ontkoppeldedocumenten/OntkoppeldeDocumentenRESTService.java
src/main/java/net/atos/zac/documenten/InboxDocumentenService.java
src/main/java/net/atos/zac/documenten/OntkoppeldeDocumentenService.java
src/main/java/net/atos/zac/mailtemplates/MailTemplateHelper.java
src/main/java/net/atos/zac/policy/PolicyService.java
src/main/java/net/atos/zac/signalering/event/SignaleringEventObserver.java
src/main/java/net/atos/zac/signalering/model/Signalering.java
src/main/java/net/atos/zac/signalering/model/SignaleringVerzondenZoekParameters.java
src/main/java/net/atos/zac/signalering/model/SignaleringZoekParameters.java
src/main/java/net/atos/zac/websocket/event/ScreenEventType.java
src/main/kotlin/nl/info/client/zgw/util/ZgwUriUtils.kt
src/main/kotlin/nl/info/client/zgw/ztc/ZtcClientService.kt
src/test/kotlin/nl/info/client/zgw/ztc/ZtcClientServiceTest.kt

Removed custom JWT token generation that was used only for certain functions in the ZGW API clients.
Solves PZ-6618

chore: removed custom JWT token generation in ZGW API clients

---

src/main/kotlin/nl/info/client/zgw/shared/ZGWApiService.kt
src/main/kotlin/nl/info/zac/search/IndexingService.kt
src/test/kotlin/nl/info/client/zgw/model/ZrcFixtures.kt
src/test/kotlin/nl/info/client/zgw/shared/ZGWApiServiceTest.kt
src/test/kotlin/nl/info/zac/zaak/ZaakServiceTest.kt

Continue indexing zaken on IllegalStateException to fixed crashed indexing process when an IllegalStateException occurs. Improved error handling.
Solves PZ-6622

fix: continue indexing zaken on IllegalStateException

---

charts/zac/Chart.yaml
charts/zac/README.md
charts/zac/ci/helm-testing-values.yaml
charts/zac/templates/signaleren-cron-job.yaml
charts/zac/templates/signaleren-delete-cron-job.yaml
charts/zac/values.yaml
src/itest/kotlin/nl/info/zac/itest/SignaleringAdminRestServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/SignaleringRestServiceTest.kt
src/main/kotlin/nl/info/zac/app/admin/SignaleringAdminRestService.kt
src/main/kotlin/nl/info/zac/authentication/SecurityUtil.kt
src/test/kotlin/nl/info/zac/admin/SignaleringAdminRestServiceTest.kt

Added API token authentication to signaleringen admin service. Adjusted the ZAC Kubernetes signaleringen cronjobs accordingly.
Solves PZ-6589

feat: add API token authentication to signaleringen admin service

---

charts/zac/Chart.yaml
charts/zac/README.md
charts/zac/templates/signaleren-cron-job.yaml
charts/zac/templates/signaleren-delete-cron-job.yaml

Fixed broken Helm Chart deployment due to recent change with `zacInternalEndpointsApiKey` value.
Solves PZ-6624

fix: fixed broken Helm Chart deployment

---

src/main/app/src/app/zaken/zaak-koppelen/zaak-koppelen.service.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.html
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

FE - Remove old Linking button and prevent old linking code to be triggered
- PO has added the acceptation criterium to keep the old code for reference to implement Gerelateerde zaken
Solves PZ-6605

feat(app): Remove old Linking button and prevent old linking code to be triggered

---

src/itest/kotlin/nl/info/zac/itest/AppContainerTest.kt
src/itest/kotlin/nl/info/zac/itest/BagRestServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/ConfigurationRestServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/CsvRESTServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/DocumentCreationRestServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/EnkelvoudigInformatieObjectRestServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/KlantRestServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/MailRestServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/NotificationsTest.kt
src/itest/kotlin/nl/info/zac/itest/NotificationsZaakDestroyTest.kt
src/itest/kotlin/nl/info/zac/itest/PlanItemsRESTServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/SignaleringAdminRestServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/SignaleringRestServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/TaskRestServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/ZaakKoppelenRestServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/ZaakRestServiceBesluitTest.kt
src/itest/kotlin/nl/info/zac/itest/ZaakRestServiceBpmnTest.kt
src/itest/kotlin/nl/info/zac/itest/ZaakRestServiceCompleteTest.kt
src/itest/kotlin/nl/info/zac/itest/ZaakRestServiceExtensionTest.kt
src/itest/kotlin/nl/info/zac/itest/ZaakRestServiceLinkParentChildZaken.kt
src/itest/kotlin/nl/info/zac/itest/ZaakRestServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/ZaakafhandelParametersRestServiceSmartDocumentsTest.kt
src/itest/kotlin/nl/info/zac/itest/client/ItestHttpClient.kt
src/itest/kotlin/nl/info/zac/itest/client/KeycloakClient.kt
src/itest/kotlin/nl/info/zac/itest/client/OpenZaakClient.kt
src/itest/kotlin/nl/info/zac/itest/config/ItestConfiguration.kt
src/itest/kotlin/nl/info/zac/itest/config/ProjectConfig.kt
src/main/webapp/WEB-INF/web.xml

Added authorization check for 'beheerder' role only on /admin URI in `web.xml`. Added integration test for this in `AppContainerTest` class. Refactored other integration tests to use existing constants for HTTP status codes instead of using our own.
Solves PZ-6653

feat: added authorization check for 'beheerder' role only on /admin URI

---

src/main/app/src/app/shared/indicaties/zaak-indicaties/zaak-indicaties.component.ts
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts
src/main/app/src/assets/i18n/en.json
src/main/app/src/assets/i18n/nl.json

FE - 'No Confirmation Sent' - indication added
- added indicator
- for now no reason available but required in Indicator component; so fallback msg atm; we need to elaborate on proper solution
- Some TS error fixes
- base of branch is `feature/PZ-4440-add-isOntvangstbevestigingVerstuurd-value-as-indicator`
Solves PZ-4439

feature(app): No Confirmation Sent - indication added

---

src/main/app/src/app/zaken/zaak-view/zaak-view.component.html
src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts

This pull request updates the `ZaakViewComponent` to improve the logic for displaying the "Betrokkenen" tab in the user interface. The changes introduce a new method to encapsulate the display condition, making the code more readable and maintainable.
* [`src/main/app/src/app/zaken/zaak-view/zaak-view.component.html`](diffhunk://#diff-77b39b0f489ba66cfa831cae58da307ced947da86c4ff6982a2fd212c09db51cL527-R527): Replaced the inline condition for showing the "Betrokkenen" tab with a call to the new `showBetrokkeneKoppelingen()` method.
* [`src/main/app/src/app/zaken/zaak-view/zaak-view.component.ts`](diffhunk://#diff-14b5c3c4e0d3f425036177305b195cf3a0676481590bebf604ceba13ae75ecbdR1486-R1496): Added the `showBetrokkeneKoppelingen()` method to centralize the logic for determining whether the …

feat(zaak-view): hide `betrokkene` tab when settings are turned off

---

docker-compose.yaml

Switch to using latest tag for BRP personen mock Docker Image so that Renovate can update it.
Solves PZ-6699

chore: switch to using latest tag for BRP personen mock Docker Image so that Renovate can update it

---

src/main/app/src/app/informatie-objecten/informatie-object-create-attended/informatie-object-create-attended.component.html
src/main/app/src/app/zaken/zaak-opschorten-dialog/zaak-opschorten-dialog.component.html
src/main/app/src/app/zaken/zaak-verlengen-dialog/zaak-verlengen-dialog.component.html

This pull request updates the UI components in several files to improve consistency and accessibility. The changes include replacing `mat-dialog-title` with `mat-toolbar` for a more uniform header design and updating icons for better clarity.
* [`src/main/app/src/app/informatie-objecten/informatie-object-create-attended/informatie-object-create-attended.component.html`](diffhunk://#diff-2de747e628aa1f9225d61c080654213025b85942d255e4ed5e5cf871056ef0ccL7-R7): Changed the icon from `upload_file` to `note_add` to better reflect the purpose of the action.
* [`src/main/app/src/app/zaken/zaak-opschorten-dialog/zaak-opschorten-dialog.component.html`](diffhunk://#diff-846594bd13f281109eb823b5c24cf284d8cdb7677fcae328000ac44e670e4422L6-R15): Replaced the `<div>` with `mat-dialog-title` by a …

chore(dialog): consistent dialog headings

---

src/main/app/src/app/shared/material-form-builder/form-components/medewerker-groep/medewerker-groep.component.ts

This pull request refactors the `MedewerkerGroepComponent` class by reorganizing the order of operations for setting validators and updating form control validity.
* [`src/main/app/src/app/shared/material-form-builder/form-components/medewerker-groep/medewerker-groep.component.ts`](diffhunk://#diff-171f8ec6b0933ee9c47315ff8bd996d8899977b9bb2fef8151f76fa8c7e7364fL110-R116): Moved the `setValidators` and `updateValueAndValidity` calls for `this.data.groep` to occur after checking for the `Validators.required` condition, ensuring proper validator configuration order.
Solves PZ-6240

fix(medewerker-groep.component): make sure to apply validator

---

src/e2e/features/2-zaken-toevoegen.feature
src/e2e/step-definitions/zaak.ts

This pull request introduces a new feature to the end-to-end (E2E) tests for verifying that a user can see an indication when no acknowledgment has been sent for a "zaak" (case). The changes include updates to the feature file and the corresponding step definitions.
* [`src/e2e/features/2-zaken-toevoegen.feature`](diffhunk://#diff-9179cb8d57f529f7fb196d94e12294b29958874368cbb8b0e11c5ac9ea14d5b0R12): Added a new scenario step to check that "Bob" sees an indication when no acknowledgment has been sent for a created zaak.
* [`src/e2e/step-definitions/zaak.ts`](diffhunk://#diff-14162a669617ec1a3d444c5fbd477deb3e031abda24ac142b631cf818cf9ccffR259-R268): Implemented a new step definition to verify the visibility of the "Geen bevestiging verstuurd" (No acknowledgment sent) indication using the …

test(E2E): validate that the "no acknowledgement" indication is set

---

src/main/app/src/app/taken/taken-verdelen-dialog/taken-verdelen-dialog.component.html
src/main/app/src/app/taken/taken-vrijgeven-dialog/taken-vrijgeven-dialog.component.html
src/main/app/src/app/zaken/zaken-verdelen-dialog/zaken-verdelen-dialog.component.html
src/main/app/src/app/zaken/zaken-vrijgeven-dialog/zaken-vrijgeven-dialog.component.html

This pull request refactors the dialog headers in multiple components to improve accessibility and visual consistency by replacing `<h1>` elements with `mat-toolbar` components and adding icons and close buttons. Additionally, it includes minor updates to conditional checks for consistency.
* Replaced `<h1>` elements with `mat-toolbar` components in `taken-verdelen-dialog`, adding an `assignment_ind` icon, a close button, and a divider for improved accessibility and design. (`src/main/app/src/app/taken/taken-verdelen-dialog/taken-verdelen-dialog.component.html`)
* Updated the `taken-vrijgeven-dialog` to use `mat-toolbar` with a `clear_all` icon, a close button, and a divider for consistency with other dialogs. (`src/main/app/src/app/taken/taken-vrijgeven-dialog/taken-vrijgeven-dialog.compo …

chore(dialog): added consistent headers

---

src/main/app/src/app/formulieren/taken/taak-formulier-builder.ts

Small fix to ensure that only groups that belong to the zaaktype can be chosen when starting a taak in that zaaktype. This was forgotten/overlooked when working on PZ-6452
Solves PZ-6753

fix: Only shows groups of that zaaktype in taak starten

---

charts/zac/Chart.yaml
charts/zac/README.md

This PR will create the next ZAC minor release: 3.6.0
The change is in the Helm Chart to update the appVersion to pick this new release by default.
#minor
Solves PZ-6665

feat(release): next ZAC minor release

---

src/main/resources/schemas/V55__drop_table_zoek_index.sql
src/main/resources/schemas/V56__smartdocuments_templates.sql
src/main/resources/schemas/V57__smartdocuments_templates_zaakafhandelparameter.sql
src/main/resources/schemas/V58__smartdocuments_document_creation_templates.sql
src/main/resources/schemas/V59__referentie_tabel_server_error_pagina_tekst.sql
src/main/resources/schemas/V60__smartdocuments_informatie_object_type.sql
src/main/resources/schemas/V61__smartdocuments_remove_informatie_object_type_from_group.sql
src/main/resources/schemas/V62__referentie_tabel_communicatiekanaal.sql
src/main/resources/schemas/V63__referentie_waarde_systeem_column.sql
src/main/resources/schemas/V64__referentie_tabel_systeem_column.sql
src/main/resources/schemas/V65__referentie_tabel_constraint_upper_on_code.sql
src/main/resources/schemas/V67__zaakafhandelparameters_create_document_enable_column.sql
src/main/resources/schemas/V68__zaaktype_bpmn_process_definition_table.sql
src/main/resources/schemas/V69__delete_domein_overig_referentie_waarde.sql

Reverted copyright changes in flyway db migrations since this breaks the deployment on environments where these migrations have been run.
Solves PZ-6826

fix: revert copyright changes in flyway db migrations

---

src/main/app/src/assets/i18n/nl.json

This pull request includes a small change to the Dutch translations in the `src/main/app/src/assets/i18n/nl.json` file. The update corrects the wording in a message to reflect that `{{naam}}` becomes the "initiator" of the case instead of the "handler."
Solves PZ-1734

chore: small translation improvement

---

src/main/app/src/app/shared/dialog/dialog.component.ts

This pull request updates the behavior of the `DialogComponent` to ensure a default value is provided when closing the dialog. 
* [`src/main/app/src/app/shared/dialog/dialog.component.ts`](diffhunk://#diff-4f20afbe11ed85afd69c572c6d9a3b3a1452832cafd17a97c26861bb39216627L50-R50): Modified the `next` callback in the `callback(results).subscribe` method to close the dialog with `true` as the default value if `data` is null or undefined.
Solves [PZ-6903](https://dimpact.atlassian.net/browse/PZ-6903)

fix(dialog): when no data is returned, return `true` as a fallback

---

src/main/app/src/app/bag/zoek/bag-zoek/bag-zoek.component.html

Changed the hover text of BAG Object Koppelen from "Selecteren" to "Koppelen"
Solves PZ-6874

fix: changed Selecteren to Koppelen

---

src/main/app/src/app/formulieren/taken/abstract-taak-formulier.ts
src/main/app/src/app/formulieren/taken/model/aanvullende-informatie.ts
src/main/app/src/app/shared/material-form-builder/model/abstract-form-control-field.ts

* [`src/main/app/src/app/formulieren/taken/abstract-taak-formulier.ts`](diffhunk://#diff-4a3ad7d21d1c797f4bbdf7d0317153b59d7fb9c0496a5f92dda9d0cae260041aL175-R175): Updated the assignment of `dataElementen[key]` to use `value as string` instead of `String(value)`, which broke the _taak_-form
Solves a bug introduced in https://github.com/infonl/dimpact-zaakafhandelcomponent/pull/3394
* [`src/main/app/src/app/formulieren/taken/model/aanvullende-informatie.ts`](diffhunk://#diff-5c13e0919f777cd9b77d0b89e2f426924d5b42d95574a83d31b2e4bce177a46eL156-R156): Added optional chaining (`defaultMail?.mail`) to handle cases where `defaultMail` might be null or undefined.
* [`src/main/app/src/app/shared/material-form-builder/model/abstract-form-control-field.ts`](diffhunk://#diff-e9a6824655cb7dee9ec2e967 …

fix: do not make `null` and `undefined` into strings

---

src/main/app/src/app/zaken/zoek/locatie-zoek/locatie-zoek.component.ts

This pull request updates the `LocatieZoekComponent` to enhance type safety and handle null values more gracefully. The changes primarily affect the `@Output` property and the `save` method.
* Modified the `@Output` property `locatie` to emit `GeometryGegevens | null` instead of just `GeometryGegevens`, allowing it to handle cases where no location is selected.
* Updated the `save` method to emit `null` for the `locatie` event when `markerLocatie` is undefined
Solves PZ-6940

fix(locatie-zoek): emit empty (`null`) location on save

---

src/main/kotlin/nl/info/zac/authentication/SecurityUtil.kt
src/main/resources/policies/rollen.rego
src/test/kotlin/nl/info/zac/admin/SignaleringAdminRestServiceTest.kt
src/test/resources/policies/document-rechten_test.rego
src/test/resources/policies/overige-rechten_test.rego
src/test/resources/policies/taak-rechten_test.rego
src/test/resources/policies/werklijst-rechten_test.rego
src/test/resources/policies/zaak-rechten_test.rego

Use 'fakeRole' in OPA tests for more clarity.
Solves PZ-6960

chore: use 'fakeRole' in OPA tests for more clarity

---

src/main/resources/api-specs/zgw/brc-openapi.yaml

Support empty values in VervalredenEnum in ZGW BRC OpenAPI spec.
Solves PZ-6957

fix: support empty values in VervalredenEnum in ZGW BRC OpenAPI spec

---

charts/zac/Chart.yaml
charts/zac/README.md
charts/zac/templates/_helpers.tpl

truncate the name used for zaakafhandelcomponent.solrcloud.fullname quite a bit, to allow solr-operator and zookeeper suffixes
Solves PZ-6967

fix: truncate basename zaakafhandelcomponent.solrcloud.fullname in helm

---

src/main/kotlin/nl/info/zac/mail/MailService.kt
src/test/kotlin/nl/info/zac/mail/MailServiceTest.kt

Fixed issue with e-mail sending when an empty attachment string was provided. In the long run we should improve the ZAC endpoint in question and we should make sure our frontend no longer sends empty strings when no input is provided.
Solves PZ-6983

fix: fixed issue with e-mail sending when an empty attachment string was provided

---

src/main/app/src/app/zaken/zaak-locatie-wijzigen/zaak-locatie-wijzigen.component.ts

FE - Fix unlink location - prevent disabling reason field
Unlinked location could not be saved since Reason field was set to disabled; disabling now determined bij the subscription/compare of original value and new value. The way it should be.
Solves PZ-7011

feat(app): Fix unlink location - prevent disabling reason field

---

src/main/app/src/app/informatie-objecten/informatie-object-create-attended/informatie-object-create-attended.component.ts

templates are set based on the selected `templateGroup`
This pull request introduces a small enhancement to the `InformatieObjectCreateAttendedComponent` class. The change ensures that the `templates` property is updated with the correct value when the `templateGroup` form control's value changes.
Solves PZ-7081

fix(informatie-object-create-attended): set available `templates`

---

src/e2e/step-definitions/external-systems.ts

Template is already pre-selected as it is the only one in the group
Solves: PZ-7082

fix: do not select SmartDocuments template in e2e

---

src/main/kotlin/nl/info/zac/app/identity/model/RestGroup.kt
src/main/kotlin/nl/info/zac/app/zaak/model/RestZaak.kt
src/main/kotlin/nl/info/zac/app/zaak/model/RestZaakAssignmentData.kt
src/main/resources/openapi-generator-templates/beanValidationCore.mustache
src/main/resources/openapi-generator-templates/infonlBeanValidationConstants.mustache
src/main/resources/openapi-generator-templates/pojo.mustache

Generate constants for annotation validations in generated Java code using the OpenAPI Generator framework and use those in our own code.
Solves PZ-7198

chore: generate constants for annotation validations in generated Java code using the OpenAPI Generator framework

---

src/main/kotlin/nl/info/client/kvk/util/KvkValidators.kt
src/main/kotlin/nl/info/zac/productaanvraag/ProductaanvraagService.kt
src/test/kotlin/nl/info/client/kvk/model/KvkZoekenFixtures.kt
src/test/kotlin/nl/info/zac/productaanvraag/ProductaanvraagServiceTest.kt

Validate vestigingsnummer in productaanvraag flow so that we no longer accept invalid KVK vestingingsnummers in the productaanvraag flow. PS: OpenZaak does no validation on vestigingsnummer.
Solves PZ-7271

feat: validate vestigingsnummer in productaanvraag flow

---

src/main/kotlin/nl/info/zac/zaak/ZaakService.kt
src/test/kotlin/nl/info/zac/zaak/ZaakServiceTest.kt

Zaaktype wihtout domain should not be a valid assign target for group that has no DOMEIN_ELK_ZAAKTYPE
Solves PZ-7337

fix: regular group cannot be assigned to zaaktype without domein

---

scripts/docker-compose/imports/keycloak/zaakafhandelcomponent-realm.json

Set sslRequired to none in our ZAC Keycloak realm since we never require SSL in our local Docker Compose setup. Note that the `sslRequired` in the Keycloak master realm is still set to the default value: `external`. It is not trivial to change that so that is maybe for another PR. For details see: https://smartling.github.io/keycloak/docs/1.2.1.Smartling-SNAPSHOT/reference/en-US/html_single/#ssl_modes
This solves the intermittent issue that I have on my local machine where ZAC can no longer access our ZAC Keycloak realm because it suddently requires SSL for some reason. ZAC then fails to start up with the following error:
`11:04:24,175 WARN  [org.wildfly.security.http.oidc] (default task-1) ELY23005: Unable to load OpenID provider metadata from …

fix: set sslRequired to none in our ZAC Keycloak realm

---

src/main/java/net/atos/client/zgw/zrc/model/Rol.java
src/main/kotlin/nl/info/zac/app/zaak/converter/RestZaakConverter.kt
src/main/kotlin/nl/info/zac/documentcreation/converter/DocumentCreationDataConverter.kt
src/test/kotlin/nl/info/zac/app/zaak/converter/RestZaakConverterTest.kt
src/test/kotlin/nl/info/zac/documentcreation/converter/DocumentCreationDataConverterTest.kt

Add SmartDocuments aanvrager data for initiator of type niet-natuurlijk persoon with a vestigingsnummer. Fixed a bug in converting niet-natuurlijk persoon betrokkene with RSIN identification.
Solves PZ-7529

feat: add SmartDocuments aanvrager data for initiator of type niet-natuurlijk persoon with a vestigingsnummer

---

src/itest/kotlin/nl/info/zac/itest/ZaakRestServiceTest.kt
src/itest/kotlin/nl/info/zac/itest/config/ProjectConfig.kt
src/main/kotlin/nl/info/zac/app/zaak/ZaakRestService.kt
src/main/kotlin/nl/info/zac/app/zaak/model/RestZaakBetrokkene.kt
src/test/kotlin/nl/info/client/zgw/model/ZrcFixtures.kt
src/test/kotlin/nl/info/zac/app/zaak/ZaakRestServiceTest.kt
src/test/kotlin/nl/info/zac/zaak/ZaakServiceTest.kt

Added identification type to restzaakbetrokkene class for future use in frontend. Also filter out betrokkenen without an identification when retrieving betrokkenen since for us these are invalid/incomplete betrokkenen and the frontend breaks for such roles anyway.
Solves PZ-7535

feat: add identification type to restzaakbetrokkene class for future use in frontend

---

.github/workflows/build-test-deploy.yml

Using clean build for non-patch updates will ensure the application is rebuilt correctly and can still use cached libraries, as these tasks can still report up-to-date. The patch updates will therefore run as they did before, and non-patch updates will be a bit faster than when using rerun-tasks.
Solves PZ-7624

fix(build): clean build output for non patch version

---

src/main/app/src/app/fout-afhandeling/fout-afhandeling.service.spec.ts
src/main/app/src/app/fout-afhandeling/fout-afhandeling.service.ts
src/main/kotlin/nl/info/zac/app/exception/RestExceptionMapper.kt
src/main/kotlin/nl/info/zac/app/exception/RestExceptionResponseBuilder.kt
src/main/kotlin/nl/info/zac/shared/exception/ValidatieFoutExceptionMapper.kt

Handle `net.atos.client.zgw.shared.exception.ValidationErrorException` to propagate OpenZaak input validation errors to frontend
Solves [PZ-7314]

feat: show open zaak validation errors on UI

---

codecov.yml

Allow small drop in Codecov test coverage before failing the Codecov check to avoid false positives where the test coverage sometimes drops by 0.01% without any code changes. See e.g.: https://github.com/codecov/codecov-ruby/issues/62
Solves PZ-7808

chore: allow small drop in Codecov test coverage before failing Codecov

---

build.gradle.kts
src/main/resources/api-specs/pabc/pabc-openapi.json

Added generated Java client for PABC based on its OpenAPI spec. Included it in the generateJavaClients task and configured the output as a source directory.
Solves [PZ-7761]

feat: client code generation for pabc openapi spec

---

docker-compose.yaml

Fixed issue where you could no longer log in to the Keycloak master realm on a Mac using Docker Desktop. See: https://github.com/keycloak/keycloak/issues/30112
Solves PZ-7874

fix: fixed issue where you could no longer log in to the Keycloak master realm on a Mac using Docker Desktop

---

src/main/app/src/app/zoeken/zoek-object/zoek-object-link/zoek-object-link.component.ts

This pull request makes updates to the `ZoekObjectLinkComponent` in the Angular application, focusing on modernizing the code by removing unused imports, enforcing stricter type safety, and simplifying method definitions.
* Removed the unused `Router` import from `zoek-object-link.component.ts`, reducing unnecessary dependencies.
* Updated `@Input` properties `zoekObject` and `sideNav` to use the `required` decorator and non-null assertion (`!`), ensuring stricter type safety and preventing potential runtime errors.
* Simplified the `getName` method by removing the explicit return type, making the code more concise while maintaining functionality.
Solves PZ-7675

refactor(zoek-object): fix lint issues

---

renovate.json

Use SemVer versioning for PABC Renovate Docker image updates because now Renovate does not upgrade PABC pre-release versions. See: https://github.com/Platform-Autorisatie-Beheer-Component/PABC-API/pkgs/container/pabc-api/versions
Solves PZ-7935

chore: use SemVer versioning for PABC Renovate Docker image updates

---

src/main/app/src/app/zaken/besluit-view/besluit-view.component.ts

This pull request makes a minor update to the confirmation dialog messaging in the `BesluitViewComponent`. Specifically, it changes the translation key used for the withdrawal message to simplify or correct the displayed text.
* Updated the `melding` property in the confirmation dialog configuration to use the `msg.besluit.intrekken` translation key instead of `msg.besluit.intrekken.melding` in `besluit-view.component.ts`.

fix(besluit-view): use correct translation string

---

src/main/app/src/app/admin/parameter-edit/parameter-edit.component.html

Always show the zaakafhandelparameters koppeling tab so that the KVK and BRP koppelingen can be managed also if SmartDocuments is disabled globally.
Solves PZ-8094

chore: always show the zaakafhandelparameters koppeling tab

---

src/main/app/src/app/klanten/zoek/personen/persoon-zoek.component.ts

This pull request updates the `PersoonZoekComponent` to improve the way form value changes are handled and to enhance the logic for enabling/disabling form fields. The main changes involve adopting a more idiomatic Angular approach for subscription cleanup and refining the control update logic.
**Form value change handling and subscription management:**
* Replaced the manual `takeUntil(this.destroy$)` pattern with Angular's `takeUntilDestroyed()` for automatic subscription cleanup in the `valueChanges` observable. This makes the code cleaner and less error-prone. [[1]](diffhunk://#diff-1e1ba19c6ad9fb36d80181c90c9e76f970ec491599868f3234e17b8ff3bd8327R15) [[2]](diffhunk://#diff-1e1ba19c6ad9fb36d80181c90c9e76f970ec491599868f3234e17b8ff3bd8327L109-R115)
* Updated the `valueChanges` …

fix(persoon-zoek.component): enable all fields for no filled fields

---

src/main/app/src/app/signaleringen/signaleringen-settings.service.ts
src/main/app/src/app/signaleringen/signaleringen-settings/signaleringen-settings.component.ts

This pull request refactors the `SignaleringenSettingsService` to use a standardized HTTP client (`ZacHttpClient`) and streamlines related code in the `SignaleringenSettingsComponent`. The changes improve type safety, code consistency, and error handling by centralizing HTTP logic.
**Refactor to standardized HTTP client:**
* Replaced usage of `HttpClient` and custom error handling in `SignaleringenSettingsService` with the shared `ZacHttpClient`, simplifying HTTP calls and removing redundant dependencies. (`src/main/app/src/app/signaleringen/signaleringen-settings.service.ts`)
**Type safety and code consistency improvements:**
* Changed the `columns` property in `SignaleringenSettingsComponent` to use a `const` assertion for stronger type safety. …

refactor(signaleringen): make use of the `ZacHttpClient`

---

src/main/app/src/app/admin/health-check.service.ts

This pull request refactors the `HealthCheckService` to simplify its implementation by removing redundant dependencies and centralizing HTTP requests through the `ZacHttpClient`. Error handling is now managed within `ZacHttpClient`, resulting in cleaner and more maintainable code.
Refactoring and simplification:
* Replaced direct usage of `HttpClient` and manual error handling with `ZacHttpClient` for all HTTP requests, removing the need for `FoutAfhandelingService` and related imports. (`src/main/app/src/app/admin/health-check.service.ts`, [src/main/app/src/app/admin/health-check.service.tsL6-R31](diffhunk://#diff-8f4d711b6a291e6ad92b02a2e0799215ba02a386e916552c25981dd2cca174d6L6-R31))
* Simplified method implementations (`listZaaktypeInrichtingschecks`, …

refactor(health-check.service): make use of the `ZacHttpClient`

---

docs/development/fontCachingProcedures.md
src/main/kotlin/net/atos/zac/flowable/cmmn/EndCaseLifecycleListener.kt
src/main/kotlin/net/atos/zac/flowable/cmmn/exception/CmmnExceptions.kt
src/main/kotlin/nl/info/zac/app/exception/RestExceptionMapper.kt
src/main/resources/wildfly/configure-wildfly.cli
src/test/kotlin/net/atos/zac/app/util/exception/RestExceptionMapperTest.kt

No longer log ZGW validation errors inside a Flowable context as exceptions with log level ERROR.
Solves PZ-8163

chore: no longer log ZGW validation errors inside a Flowable context as exceptions with log level ERROR

---

src/main/kotlin/nl/info/zac/app/zaak/ZaakRestService.kt
src/main/kotlin/nl/info/zac/authentication/LoggedInUser.kt
src/main/kotlin/nl/info/zac/authentication/SecurityUtil.kt
src/main/kotlin/nl/info/zac/authentication/UserPrincipalFilter.kt
src/main/kotlin/nl/info/zac/configuratie/ConfiguratieService.kt
src/main/kotlin/nl/info/zac/search/SearchService.kt
src/test/kotlin/nl/info/zac/app/zaak/ZaakRestServiceTest.kt
src/test/kotlin/nl/info/zac/authentication/AuthenticationFixtures.kt
src/test/kotlin/nl/info/zac/authentication/LoggedInUserAuthorisationTest.kt
src/test/kotlin/nl/info/zac/authentication/UserPrincipalFilterTest.kt
src/test/kotlin/nl/info/zac/configuratie/ConfiguratieServiceTest.kt
src/test/kotlin/nl/info/zac/policy/PolicyServiceTest.kt
src/test/kotlin/nl/info/zac/search/SearchServiceTest.kt

Also for PABC enabled IAM authorization, filter roles based on the ones defined in PABC
Solves [PZ-8219]

fix: when pabc is disabled do not call policyService with zaaktypeOmschrijving

---

docker-compose.yaml

Reverted BRP Personen Mock Docker image upgrade because the new version crashes on a Mac (ARM).
Solves PZ-8279

fix: reverted BRP Personen Mock Docker image upgrade because the new version crashes on a Mac (ARM)

---

src/main/app/src/app/documenten/inbox-documenten-list/inbox-documenten-list.component.html
src/main/app/src/app/documenten/ontkoppelde-documenten-list/ontkoppelde-documenten-list.component.html
src/main/app/src/app/informatie-objecten/informatie-object-link/informatie-object-link.component.html
src/main/app/src/app/informatie-objecten/informatie-object-link/informatie-object-link.component.ts
src/main/app/src/app/taken/taak-view/taak-view.component.html
src/main/app/src/app/zaken/zaak-view/zaak-view.component.html

This pull request refactors the `zac-informatie-object-link` component and its usage across the application to simplify its API and improve form handling. The main changes include replacing the old custom form field with a reactive Angular form, updating the component inputs to use direct binding (instead of property binding for static values), and cleaning up unnecessary logic and subscriptions.
**Component API and Usage Simplification:**
- Updated all usages of `zac-informatie-object-link` to use direct input bindings for `actionLabel` and `source`, replacing property bindings for static string values. Also replaced closing tags with self-closing tags for clarity and consistency. [[1]](diffhunk://#diff-79ab06fa2e2febd4bcf229f5514aa67175e78535552786d69e884ec6cb0357eaL11-R14) …

refactor(InformatieObjectLinkComponent): make use of Angular `FormBuilder`

---

.github/workflows/build-test-deploy.yml

Should only apply on hotfix runs, as we explicitly add the tag ourselves for main branch runs. 
Solves PZ-8221

feat: allow the release action to create a tag on the commit sha if the chosen tag does not exists.

---

src/main/kotlin/nl/info/zac/app/informatieobjecten/EnkelvoudigInformatieObjectUpdateService.kt
src/main/kotlin/nl/info/zac/enkelvoudiginformatieobject/EnkelvoudigInformatieObjectLockService.kt
src/test/kotlin/nl/info/zac/app/informatieobjecten/EnkelvoudigInformatieObjectUpdateServiceTest.kt

Solved issue where we did not delete temporary locks that we create during uploading of a new version of an enkelvoudiginformatieobject. Do that any temporary locks that were accidentally created in OpenZaak because of this issue are need to be deleted manually still!
Solves PZ-8385

fix: solved issue where we did not delete temporary locks that we create during uploading of a new version of an enkelvoudiginformatieobject

---

src/itest/kotlin/nl/info/zac/itest/ZaaktypeBpmnProcessDefinitionRestServiceTest.kt
src/main/kotlin/nl/info/zac/app/admin/ZaaktypeBpmnProcessDefinitionRestService.kt
src/main/kotlin/nl/info/zac/app/admin/model/RestZaaktypeBpmnProcessDefinition.kt
src/main/kotlin/nl/info/zac/flowable/bpmn/model/ZaaktypeBpmnProcessDefinition.kt
src/main/kotlin/nl/info/zac/productaanvraag/ProductaanvraagService.kt
src/main/resources/schemas/V80__make_group_mandatory_in_bpmn_process_definition.sql
src/test/kotlin/nl/info/zac/flowable/bpmn/ZaaktypeBpmnProcessDefinitionServiceTest.kt

Made group name in zaaktype - BPMN process definitions mandatory. Renamed code a bit here and there for consistency.
Solves PZ-8392

feat: made group name in zaaktype - BPMN process definitions mandatory

---

src/main/app/src/app/zaken/zaak-create/zaak-create.component.ts

This pull request makes a small but important fix to the `ZaakCreateComponent` to ensure that the `initiatorIdentificatie` property is only set when a value is provided, preventing possible errors when the value is missing.
- Updated the assignment of `initiatorIdentificatie` in the `createZaak` method to set it to `null` if no value is provided, improving robustness when handling optional form input.

fix(zaak-create): only create class when value exists

---

docs/solution-architecture/iamArchitecture.md
scripts/docker-compose/imports/keycloak/realms/zaakafhandelcomponent-realm.json
scripts/docker-compose/imports/pabc-database/database/1-setup-applicatie.sql
src/main/kotlin/nl/info/zac/authentication/UserPrincipalFilter.kt

Use separate functional roles for new IAM architecture in our Docker Compose setup so that they are not confused with the roles used in the old legacy IAM architecture and so that we have more flexibility.
Solves PZ-8575

chore: use separate functional roles for new IAM architecture

---

src/main/resources/api-specs/pabc/pabc-openapi.json

Upgrade the PABC OpenAPI spec according to the most recent version to which we already upgraded. Source: https://github.com/Platform-Autorisatie-Beheer-Component/PABC-API/blob/main/PABC.Server/PABC.Server.json
This should have been done as part of the recent PABC upgrade but we forgot to do it back then.
Solves PZ-8726

chore: upgrade the PABC OpenAPI spec according to the most recent version to which we already upgraded

---

docs/solution-architecture/iamArchitecture.md
src/main/kotlin/nl/info/zac/authentication/LoggedInUser.kt
src/main/kotlin/nl/info/zac/authentication/UserPrincipalFilter.kt
src/main/kotlin/nl/info/zac/policy/PolicyService.kt

Make more legacy IAM code deprecated for better overview later on. Also use @Deprecated annotation instead of @deprecated JavaDoc/KDoc tag. And cleaned up new IAM diagram a little.
Solves PZ-8734

chore: make more legacy IAM code deprecated for better overview later on

---

src/main/app/src/app/zaken/zaak-documenten/zaak-documenten.component.ts

Fix a bug that was introduced by https://github.com/infonl/dimpact-zaakafhandelcomponent/pull/4335/files#diff-f0fd51e348bf68cd55b8d594d6c0cff97bc84670e76fbec025697af72ae5a7da
Solves [PZ-7129](https://dimpact.atlassian.net/browse/PZ-7129)

fix: event shows popup, always search `enkelvoudigeInformatieObjecten`
